### ISSUE TITLE
Build out Common Elements in the C Clamp

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#111]
Common Elements on the page:

- [x] Footer #135
- [x]  Language Toggle #117

- [x]  Mobile Site Nav
- [x]  Section navigation
- [x]  Mobile Section Navigation
- [x]  Main Nav/Megamenu

- [x]  Banner
- [x]  Notification Area
- [x]  Utility Bar
- [x]  Global Search Bar
- [x]  Microsite Name "Area"
- [x]  Linkback Bar Space

**Comment by amydugan** [comment]
Adding to an EPIC sprint, since the full set of Common Elements will not be built out in a specific two-week sprint. When the elements are built out, need to review with Michelle and Lindsay.
