### ISSUE TITLE
Image Media Type Epic

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#114]
Build [Image Media Type](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images)

**User Story:**
* As a content author, I would like to create an image media type.

**Acceptance Criteria:**
* I am required to enter the following field:
  * [Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#title)
* I have the option to enter the following fields:
  * [Caption](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#caption)
  * [Original Source](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#original-source)
  * [Alt text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#alt-text)
    * If an alt text field is left empty, the image should be rendered with alt=""
  * [Credit](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#credit)
  * [Actual Image + Crops](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#the-actual-image--crops-use-cropping-widget) (use cropping widget) - this is a future sprint
  * [Accessible Text Version](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#accessible-text-version)
    * If accessible text is provided, the text needs to generate a page with a URL.
    * If there's no accessible text provided, display a 404 error.

- [x] Create the common media fields (#416)
- [x] Build the Media Type (#420)
- [x] Create the Common Image reference fields (#421)
- [x] Create the image workflow (#431)
- [ ] Add Display Modes (#780)
  - [ ] Add Lead display mode for the image
  - [ ] Add template for Lead display mode 
- [ ] Add crops (#778 )
- [ ] Add Tests (#445)

**Comment by bryanpizzillo** [comment]
@VictoriaSunNIH or @nicolecrom Is the image itself not required? Like are we going to have a point when you can create an image without an image?

**Comment by nicolecrom** [comment]
@bryanpizzillo It is required, I've update the wiki to reflect that. Discussing with @lburack now if there are another restrictions/requirements for this particular field.

**Comment by bryanpizzillo** [comment]
Yeah, I am pretty sure this got build. Closing.
