### ISSUE TITLE
Article Page Epic

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#116]
This story is to create an [Article Page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Article)

**User Story:**
- As a content author I would like to create an article page on cancer.gov. 

**Acceptance Criteria:**

- I am required to enter the following fields:
    * [Page Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#title-fields)
    * [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
    * [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
    * [Posted Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Updated Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Reviewed Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

- I have the option to enter the following:
    * [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
    * [Browser Title](#Browser-Title)
    * [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
    * [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
    * [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
    * [Date Display Mode](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Intro Text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Intro-Text)
    * [Body](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body)
    * [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Lead-Image)
    * [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)
    * [Related Resources](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Related-Resources)
    * [Citations](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Citations)
    * [Public Use Text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Public-Use)
       * Default to Checked
    * [Syndicate](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Syndicate)
       * Default to Checked
    * [Syndication Keywords](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Syndication-Keywords)

- I am required to select a section for the content.

**Tasks/Subtasks:**
- [x] Add common metadata fields to article content type #27 
- [x] Add text formats for content fields #142
- [x] Create body field #29
- [x] Add workflow transitions for Article content type #112 
- [x] Add content author and content reviewer permissions for Article content type  
- [x] Attach body field #250
- [ ] Attach related pages field  #248
- [x] Attach citations field #249
- [x] Attach Image Fields #245
- [x] Attach Intro Text Field #246
- [x] Attach Public Use Field #251
- [ ] Attach Syndication Fields #210
- [x] Implement front end look and feel #597

**Comment by adriancofie** [comment]
If were treating this as an Epic with multiple subtasks it needs to be assigned to a different sprint, and not as a blocker for the Section/URL tasks. 

If we're using this as a User Story it needs to be unassigned from a milestone.
