### ISSUE TITLE
View Article Page

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#138]
**User Story:**
- As a site visitor I would like to view an article page on www.cancer.gov. 

**Acceptance Criteria:**
**Example Pages:**

- https://www.cancer.gov/research/areas/treatment
- https://www.cancer.gov/grants-training/grants-funding/funding-opportunities/oia

**Tasks/Subtasks:**

- [x]  Replace hard-coded HTML in *node--cgov-article--full.html.twig* with fields 
- [x] Create Feature Card Template #149 
- [x] Add Thumbnail Card Template #172
- [x] Implement blocks for Article content type 
   - [x] Create  'block plugin' for page options
   - [x] (Implement Display Modes for Content Types #113)
   - [x] Look and feel of article #317 
   - [x] Implement static assets build process and include fonts and background images #331
