### ISSUE TITLE
Create Cancer Type Home Page

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#152]
This story is to create a [Cancer Type Home Page ](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-CTHP)content type.

**User Story:**
- As a content author, I would like to create a Cancer Type homepage on cancer.gov. 

**Acceptance Criteria:**
- I am required to enter the following common fields:
    * [Page Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Page-Title)
    * [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
    * [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
    * [Posted Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Updated Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Reviewed Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

- I have the option to enter the following common fields:
    * [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
    * [Browser Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Browser-Title)
    * [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
    * [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
    * [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
    * [Date Display Mode](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Body Text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body)
    * [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Lead-Image)
    * [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)
    * [Public Use Text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Public-Use)
       * Default to Unchecked
    * [Syndicate](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Syndicate)
       * Default to Unchecked
    * [Syndication Keywords](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Syndication-Keywords)

- I am required to enter the following local fields:
    * [Audience Toggle](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-CTHP#audience-toggle)

- I have the option to enter the following local fields:
    * [CTHP Overview Card](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-CTHP#cthp-overview-card)
    * [CTHP Guide Card](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-CTHP#cthp-guide-card)
    * [CTHP Feature Card](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-CTHP#cthp-feature-card)
    * [CTHP Raw HTML Card](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-CTHP#cthp-raw-html-card)
    * [CTHP Research Card](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-CTHP#cthp-research-card)
     * [CTHP Video Card](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-CTHP#cthp-video-card)
     * [CTHP Block Card](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-CTHP#cthp-block-card)

[Example of CTHP](https://www.cancer.gov/types/cervical)

**Tasks/Subtasks:**
- [ ] Add workflow transitions for Cancer Type Home Page content type 
- [ ] Add content author and content reviewer permissions for Cancer Type Home Page content type 
- [ ] Create Local Fields
- [ ] Attach All Fields
