### ISSUE TITLE
Create Blog Landing Page (Series Page)

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#153]
This story is to create a [Blog Landing Page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series).

**User Story:**
- As a content author, I would like to create a Blog Landing Page on cancer.gov. 

**Acceptance Criteria:**
- I am required to enter the following fields:
    * [Page Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Page-Title)
    * [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
    * [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
    * [Posted Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Updated Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Reviewed Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

- I have the option to enter the following:
    * [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
    * [Browser Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Browser-Title)
    * [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
    * [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
    * [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
    * [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)
    * [Public Use Text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Public-Use)

- Local Fields
    * [Allow Comments](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series#allow-comments)
    * [Blog Series Shortname](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series#blog-series-shortname)
    * [Number of Posts to Display](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series#number-of-posts-to-display)
    * [About Blog](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series#about-blog-streamlined-wysiwyg)
    * [Feedburner URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series#feedburner-url)
    * [Featured Posts](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series#featured-posts)
    * [Archive](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series#archive)
    * [Recommended Content Header (aka clickbait header)](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series#recommended-content-header-aka-clickbait-header)
    * [Banner Image (aka Body Header slot)](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series#banner-image-aka-body-header-slot)

- Other Features
  * Dynamic Listing

**Tasks/Subtasks:**
- [ ] Add workflow transitions for Blog Landing Page content type 
- [ ] Add content author and content reviewer permissions for Blog Landing Page content type 
- [ ] Create Local Fields
- [ ] Attach All Fields

**Comment by amydugan** [comment]
@daquinohd - I noticed that https://github.com/NCIOCPL/cgov-digital-platform/issues/697 is in the backlog. I believe it has a specific piece of this Landing Page story.

**Comment by lburack** [comment]
@daquinohd  - the blog series is displaying the first bit of text from the blog post, truncating the text with an ellipsis. The blog series _should_ pull in the **List Description of the blog post**, with a "Continue Reading >" link below it. 

If the "Continue Reading >" link is more complicated than it seems, I think the usefulness of that could be discussed with blog owners, since the title is already linked. LMK
