### ISSUE TITLE
Create Blog Post

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#154]
**User Story:**
- As a content author I would like to create a [Blog Post ](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Posts)on cancer.gov. 

**Acceptance Criteria:**

- I am required to enter the following fields:
    * [Page Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Page-Title)
    * [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
    * [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
    * [Posted Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

- I have the option to enter the following:
    * [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
    * [Browser Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Browser-Title)
    * [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
    * [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
    * [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
    * [Intro Text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Intro-Text)
    * [Body Text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body)
    * [Content Series Tag](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#content-series-tag---may-exist-on-cancergov-but-not-used-there--pending-dceg-analysis-for-usage-for-now)
    * [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Lead-Image)
    * [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)
    * [Related Resources](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Related-Resources)
    * [Citations](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Citations)
    * [Public Use Text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Public-Use)
       * Default to Checked
    * [Recommended Content](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Recommended-Content)

- Local Fields
  * [Blog Series](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Posts#blog-series)
  * [Author](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Posts#author)
  * [Blog Topics](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Posts#blog-topics)

- Other Features to Include
  * Blog Navigation (Prev/Next)
  * Commenting (Disqus)
  * Topic Taxonomy

**Tasks/Subtasks:**
- [ ] Add workflow transitions for Blog content type 
- [ ] Add content author and content reviewer permissions for Blog content type  
- [ ] Create Local Fields 
- [ ] Attach all Fields
