### ISSUE TITLE
Create Press Release Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#155]
This story is to create the content type for Press Release with all the fields and permissions.

**User Story:**
- As a content author I would like to create a [Press Release](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Press-Release) on cancer.gov. 

**Acceptance Criteria:**
- I am required to enter the following fields:
    * [Page Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#title-fields)
    * [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
    * [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
    * [Posted Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Updated Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Reviewed Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

- I have the option to enter the following:
    * [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
    * [Browser Title](#Browser-Title)
    * [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
    * [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
    * [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
    * [Date Display Mode](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Intro Text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Intro-Text)
    * [Body](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body)
    * [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Lead-Image)
    * [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)
    * [Citations](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Citations)
    * [Public Use Text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Public-Use)
       *  Default to Unchecked
    * [Syndicate](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Syndicate)
       *  Default to Unchecked
    * [Syndication Keywords](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Syndication-Keywords)

- [Things still to discuss](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Press-Release#things-to-discuss)

[Example of Press Release](https://www.cancer.gov/news-events/press-releases/2018/cll-ibrutinib-trial)
**Tasks/Subtasks:**
- [ ] Add workflow transitions for press release content type 
- [ ] Add content author and content reviewer permissions for press release content type  
- [ ] Create Local fields
- [ ] Attach all fields

**Comment by bgnih** [comment]
I have not added the following common fields that have not yet been created (slated for future sprints):

- Pretty URL 
- Lead Image
- Promotional Image
- Citations
- Public Use Text
- Syndicate
- Syndication Keywords

**Comment by bgnih** [comment]
Question:

Should Sort Date default to NOW() or another date field's value if left blank so it can be used in views easily?

**Comment by bgnih** [comment]
A few more questions/issues:

- The edit form field order is different between the Article content type's common fields and the order listed on https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Press-Release#form-display-order .   
- The Language selector field (English, Spanish) is not included in the field listing, so I have made it the first item on the page.  Is this acceptable?
- The Intro Text field is not listed on the edit form field order, should it be added above Body?
- We should have the exact same field order for all common fields across all content types, right?
