### ISSUE TITLE
Create Cancer Center Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#156]
### User Story:
- As a content author I would like to create a [Cancer Center](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center) page on cancer.gov. 

#### I am required to enter the following common fields:
 - [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
  - [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
  - [Posted Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
  - [Updated Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
  - [Reviewed Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
  - [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

#### I have the option to enter the following common fields:
 - [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
  - [Browser Title](#Browser-Title)
  - [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
  - [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
  - [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
  - [Date Display Mode](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
  - [Body](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body)
  - [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image) — this should display as the main image on the page, in the top left
  - [Related Resources](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Related-Resources)

#### I am required to enter the following local fields:

- [Institution Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#institution-name) 

#### I have the option to enter the following local fields: 
 - [Sort Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#sort-title)  
 - [Parent University/Institution Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#parent-universityinstitution-name)
 - [Organization Head Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#organization-head-name) 
- [Organization Head Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#organization-head-title) 
- [Address Line 1](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#address-line-1)
- [Address Line 2](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#address-line-2)    
- [City](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#city)
- [State](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#state-dropdown)
- [Zip Code](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#zip-code)
- [Region](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#region)
- [Phone 1 Label](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#phone-1-label) 
- [Phone 1 Number](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#phone-1-number) 
- [Phone 2 Label](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#phone-2-label) 
- [Phone 2 Number](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#phone-2-number) 
- [Website Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#website-title)
- [Website URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#website-url)
- [Institution Type](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#institution-type)

[Things Still to Discuss](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#things-to-discuss)

[Example of Cancer Center Page](https://www.cancer.gov/research/nci-role/cancer-centers/find/dfharvard)

**Tasks/Subtasks:**
- [ ] Add workflow transitions for cancer center page content type 
- [ ] Add content author and content reviewer permissions for cancer center page content type  
- [ ] Create local fields 
- [ ] Attach all fields

**Comment by VictoriaSunNIH** [comment]
@sarinapadilla  - please be aware that we just updated this with another new field (Region).  See https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center#region
