### ISSUE TITLE
Create Biography Page

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#157]
**User Story:**
- As a content author I would like to create a [Biography Page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography) on cancer.gov. (see [Form Display Order](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#Form-Display-Order))

**Acceptance Criteria:**

- I am required to enter the following common fields:
  * Site Section
  * Page Title (System Title)
  * Short Title
  * Meta Description
  * Posted Date
  * Updated Date
  * Reviewed Date
  * Search Engine Restrictions

- I have the option to enter the following common fields:
  * Pretty URL
  * Card Title
  * Browser Title
  * List Description
  * Feature Card Description
  * Body
  * Date Display Mode
  * Promotional Image
  * Related Resources
  * Recommended Content

- I am required to enter the following local fields:
  * [First Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#first-name)
  * [Last Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#last-name)

- I have the option to enter the following local fields
  * [Middle Name/Middle Initial](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#middle-namemiddle-initial)
  * [Prefix](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#prefix)
  * [Suffix](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#suffix)
  * [Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#title)
  * [Organization 1 Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#organization-1-name) (Cardinality question TBD)
  * [Organization 1 URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#organization-1-url) (Cardinality question TBD)
  * [Organization 2 Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#organization-2-name) (Cardinality question TBD)
  * [Organization 2 URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#organization-2-url) (Cardinality question TBD)
  * [Campus](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#campus)
  * [Building/Room Number](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#buildingroom-number)
  * [Phone Number](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#phone-number)
  * [Email Address](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#email-address)
  * [LinkedIn Profile handle](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#linkedin-profile-handle)
  * [Twitter Profile handle](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#twitter-profile-handle)
  * [Scientific Publications](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#scientific-publications)

- [Questions still to be addressed](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#things-to-discuss)
  * Recommended Content (without a header)

**Tasks/Subtasks:**
- [ ] Add workflow transitions for biography page content type 
- [ ] Add content author and content reviewer permissions for biography page content type  
- [ ] Create Local fields 
- [ ] Attach all fields
