### ISSUE TITLE
Create Event Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#158]
**User Story:**
- As a content author I would like to create an event page on cancer.gov. 

**Acceptance Criteria:**

- I am required to enter the following common fields:
    * [Event Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#title-fields)
    * [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
    * [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
    * [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)
- I have the option to enter the following common fields:
    * [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
    * [Browser Title](#Browser-Title)
    * [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
    * [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
    * [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
    * [Site Sections](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Vocabularies-Site-Sections)
       * Should default to Events -- can we make this field appear but not be editable? (or just hide the field)
    * [Body](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#body)
        * Full WYSIWYG
    * [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Lead-Image)
    * [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)
    * [Related Resources](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Related-Resources)
- I am required to enter the following local fields:
     * [Event Start Date & Time](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Event#event-start-date--time)
     * [Event End Date & Time](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Event#event-end-date--time)
- I have the option to enter the following local fields:
     * [Event Series](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Event#event-series)
     * [All Day Event](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Event#all-day-event)
     * [Venue](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Event#venue)
     * [Room Number](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Event#room-number)
     * [City/State/Country](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Event#citystatecountry)
- An outlook event is created for each event with a "Add to Outlook Button" that allows users to add the event to their calendar 

**Tasks/Subtasks:**
- [ ] Add workflow transitions for event page content type 
- [ ] Add content author and content reviewer permissions for event page content type  
- [ ] Create Local fields
- [ ] Attach all fields
