### ISSUE TITLE
Create General Page (Mix of navigational and content pages)

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#160]
**User Story:**
- As a content author I would like to create a General page on cancer.gov. 

**Acceptance Criteria:**

- I am required to enter the following common fields:

- I have the option to enter the following common fields:

- I am required to enter the following local fields:

- I have the option to enter the following local fields:

**Tasks/Subtasks:**
- [ ] Add workflow transitions for General page content type 
- [ ] Add content author and content reviewer permissions for General page content type  
- [ ] Create Local fields
- [ ] Attach all fields

**Comment by amydugan** [comment]
Per requirements discussion of 1/31/19, General Page content type is no longer needed. General Pages can be migrated to either Article or Mini-Landing Pages
