### ISSUE TITLE
Create Topic Page (Mix of navigational and content pages)

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#161]
**User Story:**
- As a content author I would like to create a [Topic page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Topic-Page) on cancer.gov. 

**Acceptance Criteria:**
- I am required to enter the following fields:
    * [Page Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#page-title)
    * [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#short-title)
    * [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
    * [Posted Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Updated Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Reviewed Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

- I have the option to enter the following:
    * [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
    * [Browser Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Browser-Title)
    * [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
    * [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
    * [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
    * [Body](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body)
    * [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Lead-Image)
    * [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)
    * [Related Resources](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Related-Resources)

- Local Fields (TBD)
  * Primary Feature Cards
  * Thumbnail Cards
  * Banner Image (aka Body Header slot)
 
- [Things to dicsuss](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Topic-Page)

**Tasks/Subtasks:**
- [ ] Add workflow transitions for Topic page content type 
- [ ] Add content author and content reviewer permissions for Topic page content type  
- [ ] Create Local fields
- [ ] Attach all fields

**Comment by nicolecrom** [comment]
Duplicate of #461
