### ISSUE TITLE
Create Cancer Research Page (Mix of navigational and content pages)

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#162]
**User Story:**
- As a content author I would like to create a [Cancer Research page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Research-Page) on cancer.gov.  See [Form Display Order](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Research-Page#form-display-order)

**Acceptance Criteria:**

- I am required to enter the following common fields:
    * [Site Section](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Vocabularies-Site-Sections)
    * [Page Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#title-fields)
    * [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
    * [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
    * [Posted Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Updated Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Reviewed Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

- I have the option to enter the following common fields:
    * [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
    * [Browser Title](#Browser-Title)
    * [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
    * [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
    * [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
    * [Date Display Mode](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Body](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body)
    * [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Lead-Image)
    * [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)

- I have the option to enter the following local fields:
   * [Selected Research Pages](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Research-Page#selected-research-pages)
     * Note that the most recent DATE of the selected item should display in between the item title and description 

 - [Issue to Discuss](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Research-Page#to-discussverify) – Whether to remove the following fields:
   * Public Use Text
   * Syndicate
   * Syndication Keywords

[Example of Cancer Research Page](https://www.cancer.gov/types/cervical/research)

**Tasks/Subtasks:**
- [ ] Add workflow transitions for Cancer Research page content type 
- [ ] Add content author and content reviewer permissions for Cancer Research page content type  
- [ ] Create Local fields
- [ ] Attach all fields
