### ISSUE TITLE
Define & Implement PDQ Workflow

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#166]
**Tasks/Subtasks:**
- [x] Document Overall PDQ Process for Loading Content into Drupal
   - [x] Content Information Summaries
   - [x] Drug Information Summaries
   - [x] What to do with media (images, audio, animations) files
- [x] Define Drupal Workflow for PDQ (#257)
- [x] Implement Drupal Workflow for PDQ (#258)

**Comment by bkline** [comment]
I started in on writing up the requested "approach" for this ticket, and it occurred to me partway through this exercise that there might be more than one interpretation of the issue title ("Define & Implement PDQ Workflow"). In addition to the interpretation for which I have started outlining an approach (the flow of PDQ Summaries from the system which maintains them to the WCMS, so: scheduler determines that a publishing job is needed, summary documents are identified for the job, the documents are assembled into denormalized XML, the denormalized XML is processed to extract the data needed for the WCMS, the WCMS APIs are invoked ..., etc.), this ticket might also have been intended to refer just to Drupal content moderation states and the transitions between those states for PDQ Summaries inside Drupal. Before I proceed any further, can someone tell me which interpretation was intended?

**Comment by nicolecrom** [comment]
@bryanpizzillo @VictoriaSunNIH  Can either of you clarify this?

**Comment by bryanpizzillo** [comment]
@bkline I think you need both that you asked for, I updated the description to break out the items.

**Comment by bkline** [comment]
The PDQ workflow will be implemented as a push from the CDR. APIs will be available in the WCMS which can be invoked to add, replace, and remove content nodes for PDQ Summaries (both Cancer Information Summaries and Drug Information Summaries), as well as query the WCMS to determine which PDQ Summaries it already contains. At a high level, the workflow looks like this.

1. A schedule manager in the system where the PDQ Summaries are maintained (the CDR) determines that a full or an incremental export of new or updated Summaries needs to take place.
1. The CDR determines which Summaries are to be included in this export job, also identifying Summaries which have been marked for removal from the WCMS.
1. For those Summaries which have been selected for export, the documents are assembled into denormalized XML.
1. The denormalized XML is process to extract the data needed for the WCMS.
1. The WCMS APIs are invoked to create new revisions in the `draft` state. New nodes are created as appropriate for summaries which are not already in the WCMS. Spanish PDQ summaries are imported as translations for the existing nodes created for the corresponding English versions, rather than being imported as separate nodes. It will be an error to attempt to import a Spanish Summary for which the node created for the English Summary does not exist.
1. The newly created revisions are flipped from the `draft` to the `published` state.
1. The nodes for English Summaries which have been marked for deletion will be deleted. It will be an error to attempt to delete an English Summary without also deleting the Spanish Summary, if the corresponding Spanish Summary exists. If a Spanish Summary is marked for deletion, but the English Summary is not, then the revisions for the Spanish Summary will be deleted, but the node will be retained. It will be an error to attempt to delete a Summary in either language if links from other non-PDQ content to it are detected. It will be the responsibility of the CDR to prevent deletion of PDQ content to which links from other published PDQ content exist.

**Comment by nicolecrom** [comment]
Copying in the question Bob reverenced 
"Are there any implications for a summary which references an image? Or for summaries which reference other summaries?

And a point for discussion: Would it be beneficial to tweak the process so once a summary (and all its dependencies) have been published, the entire dependency group is flipped to publish at that point rather than waiting for the end of the publishing run? (This is something which was periodically discussed for the legacy system, if it's desirable, it may be better to do it now rather than reworking it later.)"

**Comment by VictoriaSunNIH** [comment]
Media items should be handled separately, and in separate tickets.

As part of the export process, we need to make sure the images are available for the summary to be pushed out before the summary is published (make sure there are no broken images on the website).

**Comment by bkline** [comment]
DONE:

- implement `POST` for importing new PDQ CIS docs
- implement `GET` for retrieving PDQ CIS docs

TODO:

- [ ]  add support to CIS `POST` for updating existing docs
- [ ] add `POST` command to `pdq_core` for batch flipping of `draft` moderation state to `published`
- [ ] update POS version of CIS `DELETE` verb
- [ ] possibly move `GET` command taking CDR ID and returning Drupal node ID into `pdq_core`

**Comment by bkline** [comment]
As far as the "What to do with media (images, audio, animations) files" subtask for this ticket goes, we will be storing the media files in per-tier buckets we manage in Akamai.
