### ISSUE TITLE
Configure inactivity timeout to 120 minutes

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1700]
CGDP CMS instances need an activity timeout. Currently this is the default Drupal timeout of around 2 days. The security POAM says we should set a timeout at 60 minutes but the Okta timeout is at 2 hours. Setting less than 2 hours results in the user being logged out but then immediately logged back in again, which is an awkward user experience. We are currently planning to set the timeout to 120 minutes to align with Okta.

**Tasks**

- [x] Install and configure [autologout](https://www.drupal.org/project/autologout) module
- [x] Set autologout to only be available on SAML environments
- [ ] Verify timeouts work 

**Testing**

_Scenario 1_

- Log in to environment via SSO and go to a CMS admin page (i.e. all content)
- Set a timer for two hours
- Don't do anything else in the browser during those two hours
- Expected result: You are logged out and redirected to `/`
    - Note, if your computer goes to sleep during that two hour period you may not be redirected. But if you try to navigate to another CMS page you should find yourself logged out

_Scenario 2_

- Log in to environment via SSO and go to a CMS admin page (i.e. all content)
- Set a timer for 1 hour
- At 1 hour navigate to another CMS admin page
- Set a timer for 1 hour
- After another hour (2 hours total) navigate to another CMS admin page
- Expected result: You are still logged in and able to navigate because your session was extended

**Original from @VictoriaSunNIH:** 

> Security requirements require that the system will log a user out if they are inactive for 60 minutes.  Please confirm and configure this setting.

**Comment by jfrank-nih** [comment]
We believe that the timeout is. defined in SimpleSAMLphp: https://github.com/NCIOCPL/cgov-digital-platform/blob/63ad6f43909c08e6b2cd439270221da011442ac5/simplesamlphp/config/config.php#L489

We need to change this to be 1 hour instead of 8 for the CGDP ATO. Okta currently times out at 2 hours.

**Comment by blairlearn** [comment]
The `session.duration` setting only affects Drupal's session.  The SAML session needs to be configured in Okta.

https://support.okta.com/help/s/question/0D50Z00008Gghw9SAB/okta-session-timeout?language=en_US

**Comment by jfrank-nih** [comment]
We're not responsible for Okta's session duration/the SAML session. Particularly since, if I read that page correctly, it would affect the entirety of Okta not just our individual applications.

What we want to make sure is that Drupal does not allow a session to go beyond 1 hour without checking back in with Okta to confirm the session is live. _Imagining that Okta has a 1 hour time out,_ what we don't want is for the user to log in, wait over an hour, and then be allowed to continue working without first checking with Okta to verify the session is live. Ideally that flow is: log in, wait an hour, check with Okta, find the session is dead, re-log in.

_In reality, Okta is 2 hours at the moment._ But if Drupal checks with Okta after an hour, the session is still live, and the user ends up back in Drupal (all without even noticing that happened), so be it. We can certify that CGDP respects the hour timeout and if they want to enforce a shorter timeout in practice then that falls to the controls on the Okta system we inherit from.

**Comment by blairlearn** [comment]
@jfrank-nih My read was that you could set different verification limits on different application groups. Whether we set it that way (or actually, ask CBIIT to), I mainly wanted to leave a bookmark.

**Comment by jfrank-nih** [comment]
Noting [this comment](https://github.com/NCIOCPL/cgov-digital-platform/pull/3424#issuecomment-1203382405) which has what (I think) is the best solution.

**Comment by ramu-nih** [comment]
@jfrank-nih I looked at the below points as per your above comment.

1. Set session.duration to 1 hour
2. Somewhere in the Drupal bootstrapping, if logged in, call simplesamlphp's setAuthorityExpire function and extend the duration by another hour from the current time. Maybe do this only on full page loads or maybe on any call. I'm inclined to the latter.

The 1st one is already added.

Regarding the 2nd point, simplesamlphp_auth is not configured in local. I am not sure how to check this on local environment. Please advise.

@bryanpizzillo

**Comment by bryanpizzillo** [comment]
See PR #3424 for the last attempt.

**Comment by laurelthrash** [comment]
Added note to basic Drupal CMS user training that the inactivity timeout is 120 min. Cc: @santwuma @jfrank-nih
