### ISSUE TITLE
Citations Epic

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#206]
This story is to create [Citations](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#citations) common fields. 

- [ ] Citations Content Field #425
- [ ] Citation Pub Med ID #426
- [ ] Attach fields to Article #249 
- [ ] Attach fields to Press Release #390

**Comment by BrendanBeltzNIH** [comment]
"Max stepped into his private boat and waved goodbye and sailed back over a year and in and out of weeks and through a day and into the night of his very own room where he found his supper waiting for him—and it was still hot."
