### ISSUE TITLE
Create Infographic Multimedia Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#219]
This story is to create the [Infographic](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Infographic) Multimedia content type. 

Example URLs [here](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Infographic#example-urls)

#### I am required to enter the following common fields:

- [Page Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#title-fields)
- [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
- [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
- [Posted Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
- [Updated Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
- [Reviewed Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
- [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

#### I have the option to enter the following common fields:

- [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
- [Browser Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Browser-Title)
- [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
- [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
- [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
- [Date Display Mode](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
- [Body](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body)
- [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)
- [Public Use Text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Public-Use)
- [Syndicate](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Syndicate)
- [Syndication Keywords](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#syndication-keywords)

#### I am required to enter the following local fields:

- [The Actual Infographic](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Infographic#the-actual-infographic)

#### I have the option to enter the following local fields:
- [Accessible Text Version](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#accessible-text-version)

* The Infographic will automatically have an enlarge button which will allow the user to select and see the full sized infographic.

**Tasks/Subtasks:**
- [x] Add workflow transitions for Infographic Multimedia page type. 
- [x] Add content author and content reviewer permissions for Infographic Multimedia page type. 
- [x] Create Local fields
- [x] Attach all fields
