### ISSUE TITLE
Create Video Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#220]
This story is to create the [Video ](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Video)multimedia content type.

**User Story:**
- As a content author I would like to create a Videos that are able to be embedded inline in content, which also have their own video page on cancer.gov. 

**Acceptance Criteria:**

- I am required to enter the following common fields:
  * Site Section
  * Page Title
  * Short Title
  * Meta Description
  * Posted Date
  * Updated Date
  * Reviewed Date
  * Search Engine Restrictions

- I have the option to enter the following common fields:
  * Card Title
  * Browser Title
  * List Description
  * Feature Card Description
  * Pretty URL 
  * Body
  * Date Display Mode
  * Related Resources

- I am required to enter the following local fields:
  * [YouTube Video ID](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Video#youtube-video-id)

- I have the option to enter the following common media fields:
  * [Caption](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#caption)
  * [Original Source](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#original-source)

**Tasks/Subtasks:**
- [x] Add workflow transitions for video multimedia page type 
- [x] Add content author and content reviewer permissions for video multimedia page type  
- [x] Create local fields 
- [x] Attach all fields
