### ISSUE TITLE
Create Video Carousel Media Type 

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#221]
This story is to create the [Video Carousel](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Video-Carousel) supporting media type. See [Form Display Order](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Video-Carousel#Form-Display-Order)

**User Story:**
- As a content author I would like to create a Video Carousel on cancer.gov. 

**Acceptance Criteria:**

I am required to enter the following common fields:
* Site Section
* Page Title
* Short Title
* Meta Description
* Posted Date
* Updated Date
* Reviewed Date
* Search Engine Restrictions

I have the option to enter the following common fields:
* Card Title
* Browser Title
* List Description
* Feature Card Description
* Pretty URL 
* Date Display Mode
* Body 
* Related Resources

I am required to enter the following local fields:
  * [YouTube Video ID](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Video#youtube-video-id)

**Tasks/Subtasks:**
- [ ] Add workflow transitions for video carousel supporting media type 
- [ ] Add content author and content reviewer permissions for video carousel supporting media type   
- [ ] Create local fields 
- [ ] Attach all fields

**Comment by VictoriaSunNIH** [comment]
Backlogging this for future

**Comment by VictoriaSunNIH** [comment]
Closing this - we have a way to add via embed blocks.  That should be enough - not sure we need an actual content type.
