### ISSUE TITLE
Create Image Carousel Media Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#222]
This story is to create the [Image Carousel](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Image-Carousel) (wiki page TBD) supporting media type.

**User Story:**
- As a content author I would like to create an Image Carousel on cancer.gov. 

**Acceptance Criteria:**

- I am required to enter the following common media fields:

- I have the option to enter the following common media fields:

- I am required to enter the following local fields:

- I have the option to enter the following local fields:

**Tasks/Subtasks:**
- [ ] Add workflow transitions for image carousel supporting media type 
- [ ] Add content author and content reviewer permissions for image carousel supporting media type   
- [ ] Create local fields 
- [ ] Attach all fields

**Comment by VictoriaSunNIH** [comment]
Closing this - we have a way to add via embed blocks.  That should be enough - not sure we need an actual content type.
