### ISSUE TITLE
Create File Media Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#223]
This story is to create the [File](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-File) supporting media type.

**Tasks/Subtasks:**
- [ ] Add workflow transitions for file supporting media type 
- [ ] Add content author and content reviewer permissions for file supporting media type   
- [ ] Create local fields 
- [ ] Attach all fields

**Comment by adriancofie** [comment]
- What is this max size for a file upload?

- How are the Uploaded Filename and File Type, and File Size fields being used? Is it for programmatic purposes or Content Editor UX?

**Comment by VictoriaSunNIH** [comment]
Max file size is 500 MB for now.  New ticket to be created to set the actual size
