### ISSUE TITLE
Create App Module Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#235]
This story is to create the App Module special content type.

This content type will be used to create the following App Modules:

**Acceptance Criteria:**

- I am required to enter the following common fields:

- I have the option to enter the following common fields:

- I am required to enter the following local fields:

- I have the option to enter the following local fields:

**Tasks/Subtasks:**
- [ ] Add workflow transitions for event page content type 
- [ ] Add content author and content reviewer permissions for event page content type  
- [ ] Create Local fields
- [ ] Attach all fields

**Comment by bryanpizzillo** [comment]
This story was actually built as another ticket. So this is a duplicate.
