### ISSUE TITLE
Create Genetics Professional Application Form

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#238]
This story is to create the Genetics Professional Application Form using the Form content type #218

**User Story:**
- As a content author I would like to create the [Genetics Professional Application Form](https://www.cancer.gov/about-cancer/causes-prevention/genetics/directory/application-form) page on cancer.gov. 

**Acceptance Criteria:**

- I am required to enter the following common fields:

- I have the option to enter the following common fields:

- I am required to enter the following local fields:

- I have the option to enter the following local fields:

**Tasks/Subtasks:**
- [ ] Add workflow transitions for the Genetics Professional Application Form page
- [ ] Add content author and content reviewer permissions for the Genetics Professional Application Form page
- [ ] Create Local fields
- [ ] Attach all fields

**Comment by amydugan** [comment]
See #1105 for forms approach for Phase 1 (June)
