### ISSUE TITLE
Story: Set Language Toggle to Translated URL

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2690]
## As a search engine, I want to be able to index a link to a definition in another language, so that I may understand the content

> **ESTIMATE** 5

### Acceptance Criteria

```gherkin
Scenario: Toggle for a definition points to a translation
  Given I am viewing a definition with the pretty url "metastatic"
    And the app is within the www.cancer.gov site
  Then the language toggle should have the URL "https://www.cancer.gov/publications/dictionaries/cancer-terms/def/metastatic"
```

```gherkin
Scenario: Toggle for a expanded term points to the main page of the translation
  Given I am viewing the results for expanded letter "B"
    And the app is within the www.cancer.gov site
  Then the language toggle should have the URL "https://www.cancer.gov/espanol/publicaciones/diccionario"
```
```gherkin
Scenario: Toggle for a expanded term points to the main page of the translation
  Given I am viewing the search results for "cancer"
    And the app is within the www.cancer.gov site
  Then the language toggle should have the URL "https://www.cancer.gov/espanol/publicaciones/diccionario"
```

TODO: There may be some terms that have not been translated yet. I forget what happens.

### Notes

---

### Prerequisites
- [ ] Determine how to have app modules change the language toggle NCIOCPL/glossary-app#42

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- App module does not support updating the URL...

**Comment by bryanpizzillo** [comment]
This is no longer needed as the app is Javascript only
