### ISSUE TITLE
Story: Pretty URL Redirect for Terms

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2691]
##  As the system, I want to redirect users who enter a CDR ID into the term URL to a pretty URL of the dictionary term if it exists so that we can further enhance our SEO.

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: As the system, I need to redirect users to a pretty URL of a dictionary term if it exists.
  Given user is navigating to a specific term page
  Then URL Structure of a specific term is /publications/dictionaries/genetics-dictionary/def/[term] 
    And if term has multiple words, the words are separated by a hyphen (e.g. /publications/dictionaries/cancer-terms/def/chemoprotective-agent) 
```
```gherkin
Scenario: As a user, I would like to view a specific definition by entering the CDR ID into the URL as a parameter (instead of the definition term in the URL).
Given user enters a URL with a CDR ID (such as https://www.cancer.gov/publications/dictionaries/cancer-terms/def/797047)
  Then the system redirects user to a page with the corresponding “pretty URL” with the definition in the URL  
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- [ ] Basic Term Page (#15)

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
This is no longer needed as the app is Javascript only
