### ISSUE TITLE
Set up webpack entry point

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2692]
Set up webpack entry point - part of configuring the dictionary app module

Create entries for dictionary apps in 

Frontend globals: (
**Parent Issue:** NCIOCPL/glossary-app#5

### Sub-Tasks
- [ ] Webpack config: (cgov/cgov_common/webpack.entries.js)
- [ ] frontend globals:(cgov/cgov_common/webpack.entries.js)
- [ ] Create libraries folder and app js & scss (cgov_common/src/libraries/)
- [ ] update cgov_common.libraries to point to new library entries: (cgov/cgov_common/cgov_common.libraries.yml)
- [ ] Implement Unit Tests

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction
