### ISSUE TITLE
Story: Create Dictionary App Module in Drupal 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2694]
### Acceptance Criteria
```gherkin
Scenario: User is able to access a default (or “landing”) page that displays all of the expected Dictionary elements for the Dictionary of Cancer terms. 
  Given user is on home page
  When user navigates to “Dictionary” tab
  Then user is on landing page for the selected Dictionary
    And page displays left navigation 
    And page title is “NCI Dictionary of Cancer Terms”
    And the following introductory text appears below the page title: "The NCI Dictionary of Cancer Terms features 8,542 terms related to cancer and medicine. We offer a widget that you can add to your website to let users look up cancer-related terms. Get NCI’s Dictionary of Cancer Terms Widget." 
    And "8452" is a dynamic number generated by the API that has been inserted
    And "NCI's Dictionary of Cancer Terms Widget" links to /syndication/widgets
  And search bar is displayed below introductory text
  Then “Starts with” and “Contains” options are displayed
    And “Starts with” is selected by default
  Then “Browse” option is displayed below search bar
    And browse option contains all alphabetic letters  
    And “#” appears at the end of the list 
    And each option appears as a link 
    And the page is showing the expand results for letter “A”
    And the URL does not include expand=A
```

```gherkin
Scenario: User is able to access a default (or “landing”) page that displays all of the expected Dictionary elements for the Spanish dictionary. 
  Given user is on home page
  When user navigates to “Dictionary” tab and clicks on Espanol
  Then user is on landing page for Diccionario
    And page displays left navigation 
    And page title is “Diccionario de cáncer”
    And the following introductory text appears below the page title: "El diccionario de cáncer del NCI contiene 8,542 términos relacionados con el cáncer y la medicina.  Ofrecemos un widget que usted puede añadir a su sitio web para que sus usuarios puedan buscar términos de cáncer. Obtenga el widget de términos de cáncer del Diccionario del NCI."
    And "8,542" is a dynamic number generated by the API that has been inserted
    And "Obtenga el widget de términos de cáncer del Diccionario del NCI." links to /espanol/sindicacion/widgets
    Then “Empieza con” and “Contiene” options are displayed
    And “Empieza con” is selected by default
    And "keyword" search bar is displayed below introductory text and "Buscar" is displayed as the 
    submit button
  Then “Ojear” option is displayed below search bar
    And browse option contains all alphabetic letters  
    And “#” appears at the end of the list 
    And each option appears as a link 
    And the page is showing the expand results for letter “A”
    And the URL does not include expand=A
```

```gherkin
Scenario: User is able to access a default (or “landing”) page that displays all of the expected Dictionary elements for the Dictionary of Genetics terms. 
  Given user is on home page
  When user navigates to “Dictionary” tab
  Then user is on landing page for the Genetics Dictionary
    And page displays left navigation 
    And page title is “NCI Dictionary of Genetics Terms”
    And the following introductory text appears below the page title: "The NCI Dictionary of Genetics Terms contains technical definitions for XXX terms related to genetics and cancer. These definitions were developed by the PDQ® Cancer Genetics Editorial Board to support the evidence-based, peer-reviewed PDQ cancer genetics information summaries." 
    And "XXX" is a dynamic number generated by the API that has been inserted
    And "PDQ® Cancer Genetics Editorial Board" links to /publications/pdq/editorial-boards/genetics
    And "PDQ cancer genetics information summaries." links to /publications/pdq/information-summaries/genetics
  And search bar is displayed below introductory text
  Then “Starts with” and “Contains” options are displayed
    And “Starts with” is selected by default
  Then “Browse” option is displayed below search bar
    And browse option contains all alphabetic letters  
    And “#” appears at the end of the list 
    And each option appears as a link 
    And the page is showing the expand results for letter “A”
    And the URL does not include expand=A
```

```gherkin
Scenario: A user enters a bogus URL (like /chicken at the end of the dictionary URL
Given user has entered a bad URL (such as /publications/dictionaries/cancer-terms/chickens
  Then the user should be redirected to our 404 error page
```

### Sub-Tasks
- [ ] Create webpack entrypoint (#2692)
- [ ] Create `glossary_app` module
- [ ] Create AppModulePlugin
- [ ] Create "Builders"
- [ ] Create Template shells (#2693)
- [ ] Create YAML for the 3 existing glossary apps
- [ ] Update Glossary app build config (NCIOCPL/glossary-app#108)

### Notes

* The only valid routes for the app module are: 
   * English: `/`, `/expand/:expandChar`,  `/search/:searchText`, `/def/:idorname`
   * Spanish: `/`, `/expandir/:expandChar`, `/buscar/:searchText`, `/def/:idorname`
