### ISSUE TITLE
Story: Configure App Module for Dictionary Sources

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2695]
## As a developer, I would like to configure the app module so that I can select one of several dictionary sources for the app module to display in Drupal.

> **ESTIMATE** 5

### Acceptance Criteria

```gherkin
Scenario: As part of configuring the app module, the following options are available as the dictionary source: Dictionary of Cancer Terms, Dictionary of Genetics terms, Diccionario de Cancer
  Given user is on landing Cancer Terms page
  When user selects <dictionary_source>
  Then <url> page is loaded
  And page title is <page_title>
    Examples:
      |dictionary_source | url | page_title   |
      |Drug Dictionary | publications/dictionaries/cancer-drug |NCI Drug Dictionary|
      |Genetic Terms  | publications/dictionaries/genetics-dictionary |NCI Dictionary of Genetics Terms|
```

### Resources:
* Feature: https://tracker.nci.nih.gov/browse/CGOVWCMS-29

### Notes

On the Drupal sites, the hostname of the API server is exposed via the front end Global config.  It is accessible via `window.CDEConfig.general.apiServer`.

---

### Tasks
- [ ] Create Dictionary App Module in Drupal (#6)
- [ ] Create Templates for the Dictionary App Module (#7)
- [ ] Set up webpack entry point (#8)

### Technical Notes
- More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
This is no longer needed as we are Javascript only
