### ISSUE TITLE
Add promo image uploads to infographic content type

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/cgov-digital-platform#2702]
## As a content creator, I want to manually upload the promotional versions and their alternative text of an infographic to the same media type, so I can better create and maintain the infographic. 

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: Add alternative text to all the promotional image uploads
  Given User is in an infographic media type
  Then  a field titled “Promotional Images Alt Text” will appear in the CMS
    And that field will have a maximum of 125 characters
    And tooltip text appears under the field that says “Description of the image to be used by screen readers when the infographic promotional image appears (in feature cards).” 
  Then  when user clicks “Save” on the media type the alt text is saved and added to the infographic media type
```

```gherkin
Scenario: Upload the 4:3 promotional images associated with the infographic to the infographic media type – used for social media, feature cards, list thumbnails 
  Given User is in an infographic media type
  Then  A upload field titled “4:3 Promotional Image” will appear in the CMS
    And the user has the ability to browse their desktop for a file using the “Choose File” button
    And once the file has been added, the user should be able to click a button that says “remove” to remove the uploaded file and choose a new one 
    And a tooltip appears under the upload field that says “Used for social media, feature cards, and list thumbnails. One file only. 600x450px minimum dimensions. Keep 4:3 aspect ratio. 10 MB limit. Allowed types: png gif jpg jpeg.” 
  Then  when user clicks “Save” on the media type the file is saved and added to the infographic media type
```

```gherkin
Scenario: Upload the 16:9 promotional images associated with the infographic into the infographic media type  
  Given User is in an infographic media type
  Then  A upload field titled “16:9 Promotional Image” will appear in the CMS
    And the user has the ability to browse their desktop for a file using the “Choose File” button
    And once the file has been added, the user should be able to click a button that says “remove” to remove the uploaded file and choose a new one 
    And a tooltip appears under the upload field that says “Used for multimedia cards. One file only. 785x441px minimum dimensions. Keep 16:9 aspect ratio. 10 MB limit. Allowed types: png gif jpg jpeg.”
  Then  when user clicks “Save” on the media type the alt text is saved and added to the infographic media type
```

```gherkin
Scenario: Upload the 1:1 promotional images associated with the infographic to the infographic media type  
  Given User is in an infographic media type
  Then  A upload field titled “1:1 Promotional Image” will appear in the CMS
    And the user has the ability to browse their desktop for a file using the “Choose File” button
    And once the file has been added, the user should be able to click a button that says “remove” to remove the uploaded file and choose a new one 
    And a tooltip appears under the upload field that says “Used for multimedia cards. One file only. 800x800 px minimum dimensions. Keep 1:1 aspect ratio. 10 MB limit. Allowed types: png gif jpg jpeg.”
  Then  when user clicks “Save” on the media type the alt text is saved and added to the infographic media type
```

### Resources:
* Feature: https://tracker.nci.nih.gov/browse/CGOV-11460
* Mockups: https://publicis.invisionapp.com/share/CJW8VVAV87U
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*
* The current promo image field (that uses CGOV image) will need to be removed. This story is to add upload fields directly on the infographic.  

---

### Prerequisites
- N/A

### Tasks
- [ ] Add the promo image alt text field , export to config
- [ ] Add 4:3 promo image, export to config
- [ ] Add 16:9 promo image, export to config
- [ ] Add 1:1 promo image, export to config
- [ ] Create script or process to migrate existing images
-AC

### Technical Notes
- N/A

**Comment by claireblaustein** [comment]
Combined with  #2705
