### ISSUE TITLE
Add alt text field to the infographic

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/cgov-digital-platform#2703]
## As a content creator, I want to associate alt text with an infographic, so a user can see it when the infographic is in any context

> **ESTIMATE**  NEEDS ESTIMATE

#### Add Field

```gherkin
Scenario: add alt text field to desktop infographic upload
Given that the creator is on an infographic media type
	And there is an upload field titled "Infographic – Desktop Version" 
	And the creator uses the "Choose File" button to select a file
	And the file is attached to the media type
Then the alternative text field will appear
	And it will be a plain text field
	And it will not be required
	And tooltip text appears underneath that reads "Short description of the image used by screen readers and displayed when the image is not loaded. This is important for accessibility."
```

```gherkin
Scenario: Hide alt text field on mobile infographic upload
Given that the creator is on an infographic media type
	And there is an upload field titled "Infographic – Mobile Version"
	And the creator uses the "Choose File" button to select a file
	And the file is attached to the media type
Then no alternative text field will appear
```

#### View Page Source - Desktop 

```gherkin
Scenario: User wants to view alt text of inline infographic - has text
Given the user is viewing the desktop version infographic on a page at any template
	And the infographic has "Test alt text" in the Alt text field of the desktop file upload
When the user views the page source """alt text="Test alt text"" appears in the source code for the image
```

```gherkin
Scenario: User wants to view alt text of inline infographic - has text
Given the user is viewing the desktop version infographic on a page at any template
	And the infographic has no text in the Alternative text field of the desktop file upload
When  the user views the page source an empty alt text tag (alt text="") appears in the source code
```

#### View Page Source - Mobile 

```gherkin
Scenario: User wants to view alt text of inline infographic - has text
Given the user is viewing the mobile version of a infographic on a page
	And the infographic has "Test alt text" in the Alt text field of the desktop file upload
When the user views the page source """alt text="Test alt text"" appears in the source code for the image
```

```gherkin
Scenario: User wants to view alt text of inline infographic - has text
Given the user is viewing the mobile version of a infographic on a page
	And the infographic has no text in the Alternative text field of the desktop file upload
When  the user views the page source an empty alt text tag (alt text="") appears in the source code
```

#### View Page Source - Promo Image

```gherkin
Scenario: User wants to view alt text of promo image for infographic - has text
Given the user is viewing a list or card that links to the infographic
	And the infographic has "Test alt text" in the Alt text field of the desktop file upload
When the user views the page source """alt text="Test alt text"" appears in the source code for the image
```

```gherkin
Scenario: User wants to view alt text of promo image for infographic - has text
Given the user is viewing a list or card that links to the infographic
	And the infographic has no text in the Alternative text field of the desktop file upload
When  the user views the page source an empty alt text tag (alt text="") appears in the source code
```

### Resources

* Feature: https://tracker.nci.nih.gov/browse/CGOV-11460
* Mockups: https://publicis.invisionapp.com/share/CJW8VVAV87U
* Web Page: https://www.cancer.gov/research/areas/biology

### Notes

* Field will also need to be added to existing infographics - because it is not required, older infographics can be saved without adding alt text. HOWEVER, a cleanup effort should add alt text to infographics to ensure accessibility. 

---

### Prerequisites

*required dependency for identifying the problem, scope and then solution for this issue*

### Tasks

- [ ] Enable the built in alt text field for the desktop info graphic.
- [ ] Update the article_large article_medium and full templates
- [ ] Ensure there is a representative .YML content file.

**Comment by meglake** [comment]
@claireblaustein  please re-purpose this story to include acceptance criteria around adding alt text to the infographic when embedded in a page and on it's individual page. 

- Write criteria just for infographic use (same concept as: https://github.com/NCIOCPL/cgov-digital-platform/issues/972)
- Alt text connected to desktop image and also applied to mobile image
- Make clear that criteria applies to both medium and large templates

**Comment by claireblaustein** [comment]
@meglake @adriancofie @arcepaul - updated this story to account for adding an alt text field.

**Comment by adriancofie** [comment]
Promo image should still pull it's alt text from the cgov_image . If and when we move that image over to the infographic it should follow the same logic as the mobile image.

**Comment by meglake** [comment]
> Promo image should still pull it's alt text from the cgov_image . If and when we move that image over to the infographic it should follow the same logic as the mobile image.

@adriancofie thank you for noting, this makes sense, thank you!
