### ISSUE TITLE
Feature infographics in lists

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/cgov-digital-platform#2705]
## As a content creator, I want the infographic to have promotional images, so I can feature it in cards and lists 

> **ESTIMATE** 3

#### Uploads

```gherkin
Scenario: Upload the 4:3 promotional images associated with the infographic to the infographic media type – used for social media, feature cards, list thumbnails 
  Given User is in an infographic media type
  Then  A upload field titled “4:3 Promotional Image” will appear in the CMS
    And the field name is "field_img_4_3"
    And that field is not required
    And the user has the ability to browse their desktop for a file using the “Choose File” button
    And once the file has been added, the user should be able to click a button that says “remove” to remove the uploaded file and choose a new one 
    And a tooltip appears under the upload field that says “Used for social media, feature cards, and list thumbnails. One file only. 600x450px minimum dimensions. Keep 4:3 aspect ratio. 10 MB limit. Allowed types: png gif jpg jpeg.” 
  Then  when user clicks “Save” on the media type the file is saved and added to the infographic media type
```

```gherkin
Scenario: Upload the 16:9 promotional images associated with the infographic into the infographic media type  
  Given User is in an infographic media type
  Then  A upload field titled “16:9 Promotional Image” will appear in the CMS
    And the field name is "field_img_16_9"
    And that field is not required
    And the user has the ability to browse their desktop for a file using the “Choose File” button
    And once the file has been added, the user should be able to click a button that says “remove” to remove the uploaded file and choose a new one 
    And a tooltip appears under the upload field that says “Used for multimedia cards. One file only. 785x441px minimum dimensions. Keep 16:9 aspect ratio. 10 MB limit. Allowed types: png gif jpg jpeg.”
  Then  when user clicks “Save” on the media type the alt text is saved and added to the infographic media type
```

```gherkin
Scenario: Upload the 1:1 promotional images associated with the infographic to the infographic media type  
  Given User is in an infographic media type
  Then  A upload field titled “1:1 Promotional Image” will appear in the CMS
    And the field name is "field_img_1_1"
    And that field is not required
    And the user has the ability to browse their desktop for a file using the “Choose File” button
    And once the file has been added, the user should be able to click a button that says “remove” to remove the uploaded file and choose a new one 
    And a tooltip appears under the upload field that says “Used for multimedia cards. One file only. 800x800 px minimum dimensions. Keep 1:1 aspect ratio. 10 MB limit. Allowed types: png gif jpg jpeg.”
  Then  when user clicks “Save” on the media type the alt text is saved and added to the infographic media type
```

#### Placement

```gherkin
Scenario: infographic is slotted into a multimedia feature card row 
  Given the user is on a home and landing page 
    And that page has a multimedia row
    And an infographic is slotted in to the multimedia card
  Then the card will display the image attached to the infographic as the 16:9 Promotional Image 
    And the card will show the infographic title under the image
    And the card will show the infographic card description under the title 
    And the image will show an infographic tag on the upper right corner of the image
  Then  when user clicks anywhere on the card, it takes them to the infographic page
```

```gherkin
Scenario: infographic is slotted into a list  
  Given the user is on a mini landing page or home and landing page 
    And that page has a list
    And an infographic is slotted in to the list
    And that list is using the Title, Description, and Image template 
  Then the list will display the image attached to the infographic as the 4:3 Promotional Image 
    And the list will show the infographic title 
    And the list will show "(Infographic)" after the title
    And the list will show the list description 
  Then when user clicks on the image or the title, it takes them to the infographic page
```

### Resources:

* Feature: https://tracker.nci.nih.gov/browse/CGOV-11460
* Mockups: https://publicis.invisionapp.com/share/CJW8VVAV87U

### Notes

* ALT TEXT - to account for correct alt text on the promotional criteria, a new scenario will be written. Likely these will pull from the alt text associated with the Desktop upload of the infographic, but that is TBD based on outcomes of #2733 
*  The current promo image field (that uses CGOV image) will need to be removed. This story is to add upload fields directly on the infographic.  
* Cards and lists already have the ability to feature infographics - this ticket is to ensure that the correct crop is pulled
* This will relate to a migration ticket

---

### Prerequisites
- N/A

### Tasks
- [ ] Add the promo image alt text field , export to config
- [ ] Add 4:3 promo image, export to config
- [ ] Add 16:9 promo image, export to config
- [ ] Add 1:1 promo image, export to config
- [ ] Ensure the infographic type has a 16:9 promo image. If not, add it.
 - [ ] Update the infographic templates to pull correct data.

### Technical Notes
- The Home and Landing page already has the ability to slot an Infographic in the Multimedia Card slot on a Multimedia Row.  For this ticket, just make sure the templates pull the correct aspect ratio for the image, display the correct data, and link to the infographic page. - AC

**Comment by claireblaustein** [comment]
Updated to include field names

**Comment by meglake** [comment]
Per discussions on 4/15, this story is on hold and possibly addressed during redesign work.

Note - when we revisit, need to add the "why" to the notes section.

**Comment by meglake** [comment]
Moving to redesign - design ticket project for consideration during redesign work.

**Comment by sarinapadilla** [comment]
@laurelthrash we have implemented allowing infographics in [NCIDS Feature Card Multimedia](https://github.com/NCIOCPL/cgov-digital-platform/issues/3637) so updating the title of this ticket to only reference lists, which will be done in R3.x with mini landing pages!

**Comment by andyvanavery31** [comment]
Closing as this will be decided with the implementation of lists on MLPs.
