### ISSUE TITLE
Add Modal

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2732]
## As a user, I want to be able to enlarge an infographic that is placed in-line at a medium template, so I can read it without leaving the page

> **ESTIMATE** NEEDS ESTIMATE

#### Add Enlarge Button

```gherkin
Scenario: Infographic inline – medium
Given That the content creator has placed the infographic inline at the Infographic Display: Article: Medium 
  And the user is on a device with a screen of greater than 768px
Then User sees the desktop version of the infographic in-line at 40% of the column width
  And the user will see an enlarge button overlaid on the top right of the image with the text “Enlarge” and the magnifying glass icon
  And when the user clicks on “Enlarge” the image will appear in a modal overlaid on the screen
```

```gherkin
Background
  Given that language is set to “ES"
Scenario: Infographic inline – medium
Given That the content creator has placed the infographic inline at the Infographic Display: Article: Medium template
  And the infographic has a Spanish translation
  And the user is on a device with a screen of greater than 768px
Then User sees the desktop version of the **Spanish** infographic in-line at 40% of the column width
  And the user will see an enlarge button overlayed on the top right of the image with the text “Ampliar” and the magnifying glass icon
  And when the user clicks on the “Ampliar” the image will appear in a modal overlayed on the screen
```

#### View Modal

```gherkin
Scenario: View infographic in a modal – with caption
  Given the user is viewing the infographic on a desktop
    And The infographic appears inline at the medium template (40%)
  When  The user clicks on “Enlarge”
  Then  The image will open in a modal
    And that modal will appear at 930px wide
    And the image inside the modal will appear at 835px wide
    And The modal will display a X in the upper right corner 
  And the caption will appear below the image
  And the user will see "View and Print Infographic" button at the bottom of the modal underneath the caption
  And the "View and Print Infographic" button will open the file in a new tab
```

```gherkin
Scenario: View infographic in a modal - no caption
Given The user is viewing the infographic on a desktop
  And The infographic appears inline at the medium template (40%)  
When  The user clicks on “Enlarge”
Then  The image will open in a modal
  And that modal will appear at 930px wide
  And the image inside the modal will appear at 835px wide
  And The modal will display a X in the upper right corner 
  And the user will see "View and Print Infographic" button at the bottom of the modal
  And the "View and Print Infographic" button will open the file in a new tab
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: View infographic in a modal – with caption
  Given the user is viewing the infographic on a desktop
    And The infographic appears inline at the medium template (40%)
  When  The user clicks on "Ampliar"
  Then  The image will open in a modal
    And that modal will appear at 930px wide
    And the image inside the modal will appear at 835px wide
    And The modal will display a X in the upper right corner 
  And the caption will appear below the image
  And the user will see "Ver y Imprimir Infografía" button at the bottom of the modal underneath the caption
  And the "Ver y Imprimir Infografía" button will open the file in a new tab
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: View infographic in a modal - no caption
Given The user is viewing the infographic on a desktop
  And The infographic appears inline at the medium template (40%)  
When  The user clicks on "Ampliar"
Then  The image will open in a modal
  And that modal will appear at 930px wide
  And the image inside the modal will appear at 835px wide
  And The modal will display a X in the upper right corner 
 And the user will see "Ver y Imprimir Infografía" button at the bottom of the modal underneath the caption
  And the "Ver y Imprimir Infografía" button will open the file in a new tab
```

#### Close Modal

```gherkin
Scenario: Close infographic modal clicking the X
Given the user is viewing the infographic on a desktop 
  And The infographic appears inline at the medium template (40%)
  And The user clicks on “Enlarge” to open it in modal
When  The user clicks on the X on the modal image
Then  The modal will close
```

```gherkin
Scenario: Close infographic modal clicking outside the modal
Given the user is viewing the infographic on a desktop 
  And The infographic appears inline at the medium template (40%)
  And The user clicks on “Enlarge” to open it in modal
When  The user clicks outside the modal 
  Then  The modal will close
```

```gherkin
Scenario: Close infographic modal with esc key
Given the user is viewing the infographic on a desktop 
  And The infographic appears inline at the medium template (40%)
  And The user clicks on "Enlarge" to open it in modal
When the user hits "esc" key on the keyboard
  Then  The modal will close
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: Close infographic modal clicking the X
Given the user is viewing the infographic on a desktop 
  And The infographic appears inline at the medium template (40%)
  And The user clicks on “Ampliar” to open it in modal
When  The user clicks on the X on the modal image
Then  The modal will close
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: Close infographic modal clicking outside the modal
Given the user is viewing the infographic on a desktop 
  And The infographic appears inline at the medium template (40%)
  And The user clicks on “Ampliar” to open it in modal
When  The user clicks outside the modal 
  Then  The modal will close
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: Close infographic modal with esc key
Given the user is viewing the infographic on a desktop 
  And The infographic appears inline at the medium template (40%)
  And The user clicks on "Ampliar" to open it in modal
When the user hits "esc" key on the keyboard
  Then The modal will close
```

#### Analytics

```gherkin
 Scenario: Click events for "Enlarge" button
   Given user is viewing modal infographic
   When user clicks on "Enlarge" button
   And page click request is sent
   Then the following parameters should be captured
     | parameter | value |
     | event71   |       |
     | prop66   |     viewprint|inline|imageTitle  |
     | prop67   |       |
```

```gherkin
  Scenario: Click events for "View and Print Infographic" from the modal
    Given user is viewing modal infographic
    When user clicks on "View and Print Infographic" button
    And page click request is sent
    Then the following parameters should be captured
      | parameter | value |
      | event71   |       |
      | prop66   |     viewprint|inline|imageTitle  |
      | prop67   |       |
```

### Resources

* Feature: https://tracker.nci.nih.gov/browse/CGOV-11460
* Mockups: https://publicis.invisionapp.com/share/CJW8VVAV87U
* Web Page: https://www.cancer.gov/research/areas/biology

### Notes

* Analytics

  * "imageTitle" in the analytics should reference the content in the "Name" field of the infographic media type in the CMS

  * Original Analytics Requirements

  * ```
    On click of “Enlarge” we would like to pass:
    	1.Event71 (infographic click)
    	2.Prop66 to collect enlarge|inline|image title
    	3.Prop67 to collect the pagename
    	
    On click of “View and Print Infographic” from the modal we would like to pass:
    	1.Event71 (infographic click)
    	2.Prop66 to collect viewprint|modal|image title
    	3.Prop67 to collect the pagename
    ```


  
  ​	

---

## Solution

### Prerequisites
- [ ] View infographic in-line #2733

### Tasks
- [ ] Add button that will trigger modal
- [ ] Set modal content to be proper infographic image path

**Comment by claireblaustein** [comment]
story updated to include analytics requirements for Enlarge and Modal link

**Comment by meglake** [comment]
Moving to redesign - design ticket project for consideration during redesign work.

**Comment by andyvanavery31** [comment]
Closing due to this being outdated.
