### ISSUE TITLE
View infographic in-line and on page on desktop and mobile

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2733]
## As a content creator, I want to place an infographic in-line as well as it appearing on it's own page, so that the user can see the infographic in context on any device.

> **ESTIMATE**  8

#### Uploads

```gherkin
Scenario: Change the label of the current field_infographic upload   
  Given User is in an infographic media type
  Then  A upload field titled "Infographic – Desktop Version" will appear in the CMS
     And has a field name of "field_infographic"
     And the field is required
     And user can browse their desktop for a file using the "Choose File" button
    And the allowed file types are .png, .gif, .jpg, .jpeg 
    And max file size is 256MB 
    And a tooltip appears under the field that reads "Desktop version of the infographic." 
    And standard upload tooltips appears under the field reading "One file only. 256 MB limit. Allowed types: png gif jpg jpeg."
 Then when user clicks "Save" on the media item, the file is saved and added to the infographic media type
```

```gherkin
Scenario: Upload a mobile-optimized version of the infographic  
  Given User is in an infographic media type 
  Then  A upload field titled "Infographic – Mobile Version" will appear in the CMS below the field "Infographic – Desktop Version" 
    And has a field name of "field_infographic_mobile"
    And user can browse their desktop for a file using the "Choose File" button 
    And the allowed file types are .png, .gif, .jpg, .jpeg 
    And max file size is 256MB
    And the field is optional
    And a tooltip appears under the field that reads "Mobile version of the infographic. Will appear on devices with a screen size of 768px or smaller."
     And standard upload tooltips appear under the field reading "One file only. 256 MB limit. Allowed types: png gif jpg jpeg." 
 Then  when user clicks "Save" on the media item, the file is saved and added to the infographic media type
```

#### In-Line Medium Template

```gherkin
Scenario: Infographic inline – medium – right
Given That the content creator has placed the infographic inline at the Infographic Display: Article: Medium template
  And The content creator selected Alignment as Right
  And the user is on a device with a screen of greater than 768px
Then User sees the desktop version of the infographic in-line at 40% of the column width
  And the infographic is aligned to the right column
  And the user will see "View and Print Infographic" link in a grey box under the infographic that will open the image file in a new tab
```

```gherkin
Scenario: Infographic inline – medium – left
Given That the content creator has placed the infographic inline at the Infographic Display: Article: Medium template
  And The content creator selected Alignment as Left
  And the user is on a device with a screen of greater than 768px
Then User sees the desktop version of the infographic in-line at 40% of the column width
  And the infographic is aligned to the left column
  And the user will see "View and Print Infographic" link in a grey box under the infographic that will open the image file in a new tab
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: Infographic inline – medium – right
Given That the content creator has placed the infographic inline at the Infographic Display: Article: Medium template
  And the infographic has a Spanish translation   
  And The content creator selected Alignment as Right
  And the user is on a device with a screen of greater than 768px
Then User sees the desktop version of the Spanish infographic in-line at 40% of the column width
  And the infographic is aligned to the right column
  And the user will see "Ver y Imprimir Infografía" link in a grey box under the infographic that will open the image file in a new tab
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: Infographic inline – medium – left
Given That the content creator has placed the infographic inline at the Infographic Display: Article: Medium template
  And the infographic has a Spanish translation   
  And The content creator selected Alignment as Left
  And the user is on a device with a screen of greater than 768px
Then User sees the desktop version of the Spanish infographic in-line at 40% of the column width
  And the infographic is aligned to the left column
  And the user will see "Ver y Imprimir Infografía" link in a grey box under the infographic that will open the image file in a new tab
```

```gherkin
Scenario: source - alt text
Given that the user is on a page with an infographic embededded inline 
	And that infographic is using a medium template 
When the user views the page source, an empty alt text tag (alt text="") appears in the source code
```

#### In-Line Large Template

```gherkin
Scenario: Infographic inline – large
Given That the content creator has placed the infographic inline at the Infographic Display: Article: Large template
  And the user is on a device with a screen of greater than 768px
Then  User sees the desktop version of the infographic in-line at 100% of the column width
  And the user will see "View and Print Infographic" link in a grey box under the infographic that will open the image file in a new tab
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: Infographic inline – large - Spanish translation
Given That the content creator has placed the infographic inline at the Infographic Display: Article: Large template
  And the infographic has a Spanish translation   
  And the user is on a device with a screen of greater than 768px
Then  User sees the desktop version of the infographic in-line at 100% of the column width
  And the user will see "Ver y Imprimir Infografía" link in a grey box under the infographic that will open the image file in a new tab
```

```gherkin	
Scenario: source - alt text
Given that the user is on a page with an infographic embededded inline 
	And that infographic is using a Large template 
When the user views the page source, an empty alt text tag (alt text="") appears in the source code
```

#### Infographic Page

```gherkin
Scenario: Infographic page
Given That the user is on an infographic page
  And the user is on a device with a screen of greater than 768px
Then User sees the desktop version of the infographic at 100% of the column width
  And the user will see "View and Print Infographic" link in a grey box under the infographic that will open the image file in a new tab
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: Infographic page - Spanish
Given That the user is on a Spanish infographic page
  And the user is on a device with a screen of greater than 768px
Then User sees the Spanish desktop version of the infographic at 100% of the column width
  And the user will see "Ver y Imprimir Infografía" link in a grey box under the infographic that will open the image file in a new tab
```

```gherkin	
Scenario: source - alt text
Given that the user is on a page with an infographic embededded inline 
	And that infographic is using a Large template 
When the user views the page source, an empty alt text tag (alt text="") appears in the source code
```

###### Inline

```gherkin
Scenario: View infographic inline on a mobile device – has mobile optimized version
Given The user is using a device with a screen at 768px or smaller
  And The user is viewing a page with an infographic placed inline
  And The infographic has a mobile version 
Then The mobile version is displayed
  And the infographic appears in-line at 100% of column width 
  And the "View and Print Infographic" link will not show
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: View infographic inline on a mobile device – has mobile optimized version
  Given The user is using a device with a screen at 768px or smaller
  And the infographic has a Spanish translation  
  And the Spanish translation has a mobile optimized version
  And The user is viewing a page with an infographic placed inline   
Then The mobile version is displayed
  And the infographic appears in-line at 100% of column width 
  And the "Ver e Imprimir Infografía" link will not show
```

###### Infographic Page

```gherkin
Scenario: View infographic page on a mobile device – has mobile optimized version
Given The user is using a device with a screen at 768px or smaller
  And The user is viewing an infographic page
  And The infographic has a mobile version 
Then The mobile version is displayed
  And the infographic appears at 100% of column width 
  And the "View and Print Infographic" link will not show
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: View infographic page on a mobile device – has mobile optimized version
  Given the user is on a Spanish infographic page
  And the user is using a device with a screen at 768px or smaller
  And the Spanish translation has a mobile optimized version
Then The Spanish mobile version is displayed
  And the infographic appears at 100% of column width 
  And the "Ver e Imprimir Infografía" link will not show
```

###### Inline

```gherkin
Scenario: View infographic on a mobile device – no mobile optimized version
Given The user is using a device with a screen at 768px or smaller
  And The user is viewing a page with an infographic placed inline
  And The infographic does not have a mobile version 
Then The desktop version is displayed
  And the infographic appears in-line at 100% of column width 
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: View infographic on a mobile device – no mobile optimized version
  Given The user is using a device with a screen at 768px or smaller
  And the infographic has a Spanish translation  
  And the Spanish translation does not have has a mobile optimized version
  And The user is viewing a page with an infographic placed inline   
Then The Spanish desktop version is displayed
  And the infographic appears in-line at 100% of column width
```

###### Infographic Page

```gherkin
Scenario: View infographic page on a mobile device – no mobile optimized version
Given The user is using a device with a screen at 768px or smaller
  And The user is viewing an infographic page
  And The infographic does not have a mobile version 
Then The desktop version is displayed
  And the infographic appears in-line at 100% of column width
```

```gherkin
Background
  Given that language is set to "ES"
Scenario: View infographic page on a mobile device – no mobile optimized version
  Given the user is on a Spanish infographic page 
  And the user is using a device with a screen at 768px or smaller
  And the translation does not have a mobile optimized version
Then The Spanish desktop version is displayed
  And the infographic appears at 100% of column width
```

#### Accessibility - Long Desc

```gherkin
Scenario: User wants to view accessible text -  has text (for testing)
  Given the user is viewing the infographic on a page
 	 And the infographic has content in the Accessible Text (longdesc) field 
  When the user views the  page source "img longdesc” attribute appears in the source code 
  Then the "img longdesc” attribute points to a URL that contains the media ID (e.g. /media/923228/long-description) 
```

```gherkin
Scenario: User wants to view accessible text -  no text (for testing)
  Given the user is viewing the infographic on a page
  	And the infographic does not have content in the Accessible Text (longdesc) field 
  When the user views the page source no "img longdesc” attribute appears in the source code
```

### 

### Resources

* Feature: https://tracker.nci.nih.gov/browse/CGOV-11460
* Mockups: https://publicis.invisionapp.com/share/CJW8VVAV87U
* Web Page: https://www.cancer.gov/research/areas/biology

### Notes
* Change the label of the desktop upload field
* existing infographic templates:
```media--cgov-infographic--full.html.twig
media--cgov-infographic--multimedia-card.html.html.twig
media--cgov-infographic--infographic-display-article-medium.html.twig
media--cgov-infographic--enitity-browser-selected-entity.html.twig
media--cgov-infographic--infographic-display-article-large.html.twig
media--cgov-infographic--infographic-display-article-medium.html.twig
```

---

### Prerequisites
*required dependency for identifying the problem, scope and then solution for this issue*

### Tasks
- [ ] Create infographic css rules for mobile, medium(tablet), large and xl breakpoints (with and without caption)
- [ ] Add picture element and configure source tags and fallback images
- [x]  Rename label of existing field, export to config 
- [ ] Add mobile optimized media upload field
       - [ ] Edit form display
       - [ ]  Edit display modes to hide label and manage order
          - [ ] Infographic Display: Article Large 
          - [ ] Infographic Display: Article Medium
          - [ ] Infographic Display: Link
          - [ ] Infographic Display: Multimedia Card
          - [ ] Infographic Display: Image Thumbnail
 - [ ] Export to Features config

**Comment by adriancofie** [comment]
Moving forward additional details to keep track of for new fields should be:

- Is it required?
- What is the machine  / system name for the field?
- Is there associated help text?

**Comment by blilianyu** [comment]
@adriancofie Mobile infographic image upload should be optional

**Comment by meglake** [comment]
@claireblaustein  please update this story to include the acceptance criteria from story 2703 (accessible text/long description)

**Comment by claireblaustein** [comment]
Added empty alt text acceptance to each the medium and large template on desktop, and moved over the longdesc acceptance criteria.

@meglake @acofie @arcepaul

**Comment by adriancofie** [comment]
On ODE 340 : ncigovcdode340.prod.acquia-sites.com

**Comment by claireblaustein** [comment]
@adriancofie @arcepaul In the Mobile section I added scenarios for the infographic pages

**Comment by claireblaustein** [comment]
@adriancofie @arcepaul updated to cover infographic pages and to remove references to captions - capturing caption requirements in a new story.
