### ISSUE TITLE
Add caption to infographic

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2765]
## As a content creator, I want to have the ability to add a caption to an infographic, so the user can get further context of the infographic.

> **ESTIMATE**  NEEDS ESTIMATE

#### Add Field	

```gherkin
Scenario: Add a caption to the infographic
  Given User is in an infographic media type 
  Then  A field titled "Caption" will appear in the CMS
  	And it will be below the field "Body" 
    And has a field name of "field_caption"
    And is a simple WYSIWYG
    And the field is optional
    And a tooltip appears under the field that reads "Enter image caption [Displays below image]"
 Then when user clicks "Save" on the media item, the caption is saved and added to the infographic media type
```

#### Display - In-Line

```gherkin
Scenario: View caption on an inline infographic
  Given that an infographic has text in the caption field
  When a user views a page with an infographic placed in-line
  Then the caption text appears in a grey box under the infographic
 	 And the "View and Print Infographic" button shows below the caption 
```
```gherkin
Background 
	Given that the language is set to "ES"
Scenario: View caption on an inline infographic on a Spanish page
  Given that a Spanish infographic has text in the caption field
  When a user views a page with an infographic placed in-line
  Then the caption text appears in a grey box under the infographic
  	And the "Ver y Imprimir Infografía" button shows below the caption
```

#### Display - Page

```gherkin
Scenario: View caption on an infographic page
  Given that an infographic has text in the caption field
  When a user views the infographic page
  Then the caption text appears in a grey box under the infographic
 	 And the "View and Print Infographic" button shows below the caption 
```

```gherkin
Background 
	Given that the language is set to "ES"
Scenario: View caption on a Spanish infographic page
  Given that a Spanish infographic has text in the caption field
  When a user views a Spanish infographic page
  Then the caption text appears in a grey box under the infographic
 	 And the "Ver y Imprimir Infografía" button shows below the caption
```

### Resources

* Feature: https://tracker.nci.nih.gov/browse/CGOV-11460
* Mockups: Full-width: https://publicis.invisionapp.com/share/CJW8VVAV87U#/408035405_Infographic_Full_Caption
40%: https://publicis.invisionapp.com/share/CJW8VVAV87U#/408035406_Infographic_40-_Caption
 
* Web Page: https://www.cancer.gov/research/areas/biology

### Notes

* existing infographic templates:

```media--cgov-infographic--full.html.twig
media--cgov-infographic--multimedia-card.html.html.twig
media--cgov-infographic--infographic-display-article-medium.html.twig
media--cgov-infographic--enitity-browser-selected-entity.html.twig
media--cgov-infographic--infographic-display-article-large.html.twig
media--cgov-infographic--infographic-display-article-medium.html.twig
```

---

### Prerequisites
#2733

### Tasks

- [ ] Add the caption field and export to config.
- [ ] Update the article_large, article_medium, and full display modes to enable the field.
- [ ] Update the article_large, article_medium, and full templates use caption
- [ ] Update the representative YAML content

**Comment by blilianyu** [comment]
@adriancofie I've updated the comp links in the story but also below:
**Full-width:** https://publicis.invisionapp.com/share/CJW8VVAV87U#/408035405_Infographic_Full_Caption

**40%:** https://publicis.invisionapp.com/share/CJW8VVAV87U#/408035406_Infographic_40-_Caption
