### ISSUE TITLE
Story: Special Report Template for AP

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/cgov-digital-platform#2774]
## As a member of NCI Leadership, I would like to have a unique layout for the AP content, so that it may appear fresh and increase viewing times 

> **ESTIMATE** 

### Acceptance Criteria

```gherkin
Scenario: User views the AP landing page 
  Given the user is viewing the AP landing page 
    And the browser width is 1025px or greater 
  Then the Desktop Hero image should be displayed full width 
    And the page title should appear on top of the desktop hero image, centered over the main content area 
    And the main content area should overlap the bottom of the hero image 
    And no left navigation will display 
```

```gherkin
Scenario: User views the AP landing page on Tablet 
  Given the user is viewing the AP landing page 
    And the browser width is 1024px or less 
  Then the Desktop Hero image should be displayed full width 
    And the page title should appear on top of the desktop hero image, centered over the main content area 
    And the main content area should appear below the hero image 
```

```gherkin
Scenario: User views the AP landing page on Mobile 
  Given the user is viewing the AP landing page 
    And the browser width is 640px or less 
  Then the Tablet Hero image should be displayed full width 
    And the page title should appear on top of the hero image, centered over the main content area 
    And main content area should appear below the hero image 
```

```gherkin
Scenario: Content owner creates a new Special Report landing page  
  Given the user is logged in as an editor 
    And the user adds new content 
    And selects “Home and Landing” as the content type 
  Then a new Home and Landing page is created 
    And a dropdown with the title “Home and Landing Page Style” appears under the language selection and above the site section  
    And under the dropdown the tooltip text appears that reads "Select a template for the page" 
    And the dropdown defaults to "- Standard -" 
    And the dropdown has two options of "Standard" and "Special Report" 
    And the field is required 
```

```gherkin
Scenario: Content owner does not need to enter tagline 
  Given the user is logged in as an editor 
  When the user is creating a Home and Landing page 
    And the user selects "Add Hero Banner" 
  Then upload fields appear for the Desktop Hero and Tablet Hero 
    And a field for Tagline appears 
    And the tagline field has help text that reads "Appears on top of the hero image for Home and Landing pages using the Standard template" 
    And the tagline field is not required 
```
**Analytics** 

```gherkin
Scenario: Page load of AP landing page
Given user views the AP landing page
 Then the following parameters should be captured
      | parameter | value                                                                                                                                                                                                                                                                                                                                                                                               |
      | event1    |                                                                                                                                                                                                                                                                                                                                                                                                     |
      | prop1     | [full URL 1-100]                                                                                                                                                                                                                                                                                                                                                                                    |
      | prop6     | [short title]                                                                                                                                                                                                                                                                                                                                                                                       |
      | prop8     | [language]                                                                                                                                                                                                                                                                                                                                                                                          |
      | prop10    | [browser title]                                                                                                                                                                                                                                                                                                                                                                                     |
      | prop26    | [timestamp]                                                                                                                                                                                                                                                                                                                                                                                         |
      | prop29    | /(year)=(19\|20)\d{2}\s\|\s(month)=(?:Jan(?:uary)? \|Feb(?:ruary)? \|Mar(?:ch)? \|Apr(?:il)? \|May \|Jun(?:e)? \|Jul(?:y)? \|Aug(?:ust)? \|Sep(?:tember)? \|Oct(?:ober)? \|(Nov \|Dec)(?:ember)?)\s\|\s(date)=\d{1,2}\s\|\s(day)=(?:Sun(?:day)? \|Mon(?:day)? \|Tue(?:sday)? \|Wed(?:nesday)? \|Thu(?:rsday)? \|Fri(?:day)? \|Sat(?:urday))\s\|\s(time)=(1[0-2]\|0?[1-9]):([0-5][0-9]) ?([AP][M]) / |
      | prop42    | [font size]                                                                                                                                                                                                                                                                                                                                                                                         |
      | prop61    | [previous page value]                                                                                                                                                                                                                                                                                                                                                                               |
      | prop65    | [page load time]                                                                                                                                                                                                                                                                                                                                                                                    |
      | eVar2     | D=c8                                                                                                                                                                                                                                                                                                                                                                                                |
      | evar5     | [screen breakpoint]                                                                                                                                                                                                                                                                                                                                                                                 |
      | evar1     | [page url]   
```

```gherkin
Scenario: Events for page depth
Given user is viewing the AP landing page
When user scrolls beyond 50% point of page body (excluding main nav and footer)
Then event is fired
  And the following parameters should be captured
      | parameter | value             |
      | event20   |                   |
      | prop66    | page-scroll |
      | prop8     | [language]        |
```

### Resources:
Mockups
- Desktop: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/410081138_AP_Landing_Page_V9_-_Desktop

- Tablet 1024:  https://publicis.invisionapp.com/share/DZWC0VL2B3E#/415867266_AP_Landing_Page_V9_-_Tablet_1024

- Mobile: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/411216125_AP_Landing_Page_V9_-_Mobile


### Notes

*Some complementary notes if necessary:*
prop29 format : year=2020 | month=June | date=1 | day=Monday | time=3:46 PM

- Page Style specs in wiki https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Home-&-Landing-Page#page-style


---

## Solution

### Tasks
- [ ] Augment the Landing Page Content Type (#2785) 
        - [ ] Add new field for template style
        - [ ] Add Theme Suggestions
        - [ ] Add YAML Content  
- [ ] Create new twig template (#2794)
        - [ ] Create Template
        - [ ] Create styles for page options
        - [ ] Add layout styles
        - [ ] Create webpack entrypoint

- [ ] Add analytics for page options (add ACs to story)

**Comment by Andrew-Olsson** [comment]
**Analytics:**

Scenario: Page load of AP landing page
Given user views the AP landing page 
Then the following parameters should be captured (mirror of existing analytics):
•	Event1
•	prop1: full URL 1-100
•	Prop6: short title
•	prop8: language
•	Prop10: browser title
•	prop26: timestamp
•	prop29: date and time
•	prop42: font size
•	prop61: previous page value
•	prop65: page load time
•	eVar1
•	eVar2
•	eVar5

Scenario: Click events for page options
Given user is viewing the AP landing page
When user clicks on a page option link
And page click request is sent
Then the following parameters should be captured
•	Event17
•	Prop4: D=pev1
•	Prop8: language
•	Prop43: [page option type] / “facebook”, “twitter”, “print”, or “email”
•	Prop66: “annualplan_[page option type]”
•	Prop67: D=pagename
•	eVar2: language

Scenario: Events for page depth
Given user is viewing the AP landing page
When user scrolls beyond 50% point of page body (excluding main nav and footer)
And event is fired
Then the following parameters should be captured
•	Event20
•	Prop8: [language]
•	Prop66: “annualplan_scroll”

**Comment by Andrew-Olsson** [comment]
Custom analytics for page options: prop43 and prop66
Custom analytics for the page depth: prop66; the rest should be global analytics as this is a re-purposing of an existing analytics function.
Everything else listed are global analytics.

**Comment by kate-mashkina** [comment]
1. On the mobile breakpoint page title does not stay on top of the hero image, but is overlapping with the area below
2. page option button should be aligned horizontally on mobile breakpoint

<img width="596" alt="Screen Shot 2020-06-15 at 11 58 39 AM" src="https://user-images.githubusercontent.com/56886837/84679931-edef5500-aeff-11ea-939d-8b705c9e560e.png">
