### ISSUE TITLE
Story: Alternating Image List

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/cgov-digital-platform#2778]
## As a content editor, I would like to be able to embed an alternating image list, so that we can engage the user more visually. 

> **ESTIMATE**: 5

### Details

- This will be a new template within the existing List paragraph container
- We will allow for all existing list items (internal, external, media)
- Display changes
  - uses 16:9 image crop
  - text styling consistent with AP landing page template (see inspect on InVision)
  - title has a hover state, image does not
- Click function the same as current lists - title and image

#### Front End Display

```gherkin
Scenario: User views a page with an alternating image list on desktop or tablet 
  Given a user is viewing the AP landing page 
    And the browser width is 768px or greater 
  Then an alternating image list will appear 
    And the 16:9 crop of the promo image associated with the selected list item should appear (following our image rules) 
    And the page title of the selected list item should appear as a H3 
    And the title will turn cranberry on hover or focus 
    And the list description of the selected list item should appear 
    And the whole item will be clickable 
    And the first item will have the image aligned on the left 
    And the second item will have the image aligned on the right 
    And the following items will follow the alternating pattern 
```

```gherkin
Scenario: User views alternating image list on Mobile 
  Given a user is viewing the AP landing page 
    And the browser width is 640px or less 
  Then a background image of a card border will appear behind each list item 
    And the images will not display 
    And the title of the selected list item will appear 
    And the title will turn cranberry on hover or focus 
    And the list description of the selected list item will appear under the title 
    And the whole card will be clickable 
    And clicking on the card will go to the selected list item 
```

```gherkin
Scenario: Internal list item, no overrides 
  Given a user is viewing a page with an Alternating Image List 
    And one of the list items is an Internal Link 
    And the content editor has not put content in any of the override fields 
  Then the featured item’s List Title will appear 
    And the 16:9 crop of the promo image of the selected list item will appear (following our image rules) 
    And the List Description of the selected list item will appear 
```

```gherkin
Scenario: Internal feature card, overrides 
  Given a user is viewing a page with an Alternating Image List 
    And one of the list items is an Internal Link 
    And the content editor has filled in the override fields 
  Then the featured item’s Override Title will appear 
    And the 16:9 crop of the Override Promotional Image will appear (following our image rules) 
    And the Override List Description will appear 
```

```gherkin
Scenario: External feature card 
  Given a user is viewing a page with an Alternating Image List 
    And one of the cards is an External Link 
  Then the content in the item’s Title field will appear 
    And the 16:9 crop of the Promotional Image associated with the item will appear 
    And the content in the item’s List Description field will appear 
    And the whole card will link to the destination in the item’s Link field 
```

```gherkin
Scenario: User views a Spanish page with an Alternating Image List  
  Given language is set to "ES” 
  Then the Spanish content of all fields will display 
```

#### Content Editor

```gherkin
Scenario: Content editor adds an Alternating Image List to the AP landing page 
  Given the user is logged in as an editor 
    And the user edits the AP landing page 
    And expands the drop down to add a paragraph to Contents 
    And selects "Add List" from the list 
  Then the fields for a list appear 
    And a Title field appears 
    And the Title field is not required 
    And a Dropdown titled "List Item Style" appears
    And the dropdown has four options: "Compact" "Title and Description" "Image, Title, and Description" and "Alternating Image"
    And the dropdown defaults to a blank "-Select a Value-"
    And the dropdown has a tooltip that reads "Select the styling for each list item."
    And a container titled "List Items" appears 
    And the first item defaults to an Internal Link 
    And a dropdown button appears at the bottom under text that reads "The list items for this list" 
    And the dropdown button has three options: "Add Internal Link" "Add External Link" and "Add Media Link"
```

**Analytics:**

```gherkin
 Scenario: Analytics for link click in raw HTML block
    Given user is viewing the AP landing page
    When user clicks on an internal link in a raw HTML block
    Then page click request is sent
    And the following parameters should be captured
      | parameter | value      |
      | prop61    | D=pagename |
```

```gherkin
  Scenario: Analytics for link click in raw HTML block
    Given user is viewing the AP landing page
    When user clicks on an external link in a raw HTML block
    Then page click request is sent
    And the following parameters should be captured
      | parameter | value           |
      | event1    |                 |
      | prop6     | [short title]   |
      | prop8     | [language]      |
      | prop10    | [browser title] |
      | prop25    | [exit date]     |
      | prop44    | [exit page tag] |
      | eVar2     | D=c8            |
      | evar7     | D=c7            |
      | evar44    | D=c44           |
```

---

### Fields

- On Home and Landing Wiki: https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Home-&-Landing-Page#alternating-image-list

List: https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Type-List
Link Items: https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Type-Links

---

### Resources

Mockups

- Desktop: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/410081138_AP_Landing_Page_V9_-_Desktop
- Tablet 1024:  https://publicis.invisionapp.com/share/DZWC0VL2B3E#/415867266_AP_Landing_Page_V9_-_Tablet_1024
- Mobile: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/411216125_AP_Landing_Page_V9_-_Mobile
- Desktop - List with media items:
  https://publicis.invisionapp.com/share/DZWC0VL2B3E#/screens/418100299_AP_Landing_Page_V9_-_Desktop_1440_All_MediaI

**Insepect Mode**: https://publicis.invisionapp.com/d/main#/console/19545250/421963235/inspect (see details of styles)

### Notes

- 

---

### Tasks

- [ ] Create alternating image list paragraph type, select allowable list items
- [ ] Add styling 
- [ ] Add YAML content 
- [ ] Add in analytics card click (ACs to be added to story)

**Comment by Andrew-Olsson** [comment]
**Analytics:**

Scenario: Analytics for link click in raw HTML block
Given user is viewing the AP landing page
When user clicks on an internal link in a raw HTML block
And page click request is sent
Then the following parameters should be captured
•	Prop61 should already collect the previous page name on the load of the clicked page

Scenario: Analytics for link click in raw HTML block
Given user is viewing the AP landing page
When user clicks on an external link in a raw HTML block
And page click request is sent
Then the following parameters should be captured
	Exit Link Click:
•	Event1
•	Prop6: short title
•	Prop8: language
•	Prop10: browser title
•	Prop25: exit date
•	Prop44: exit page tag
•	eVar2
•	eVar7
•	eVar44

**Comment by Andrew-Olsson** [comment]
These are all global analytics.

**Comment by bryanpizzillo** [comment]
6/22 - We all decided that we will:
1. Reuse the existing cgov_list paragraph type
2. Add a new alternating list style for cgov_list's list item style
3. Allow media to be added, since we can't stop it. The media title will follow our normal list styling for media links (i.e. [Title as a link](#) (TYPE)
