### ISSUE TITLE
Augment the Landing Page Content Type

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2785]
### Description

Add a new field for template theme containing "Standard" and "Special Report" options.

**Parent Issue:** #2788

### Sub-Tasks
- [ ] Add new 'Home and Landing Page Style” field
- [ ] Add template suggestions for theme based on field
- [ ] Add new scss partial, scoped to new special-report landmark
- [ ] Implement Unit Tests
