### ISSUE TITLE
Enabler: Upgrade to PHP 7.4

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3105]
# Upgrade Drupal to run on PHP 7.4 before Acquia switches it for us.

Acquia is ending support for PHP 7.4 on October 4, ahead of PHP.net ending it at the end of the year.

We need to test our application with PHP 7.4 and update the configuration in ACE and ACSF before then.

**NOTE:** We've spoken a little about going straight to PHP 8, but Acquia doesn't offer that option yet.

> **ESTIMATE** TBD

### Resources:
* [PHP supported versions](https://www.php.net/supported-versions.php)

### Sub-Tasks
- [x] Test on ODE
- [x] Test on ACSF Dev and/or Test environments
- [x] The pipelines configuration needs to be updated
- [x] Update local dev environment (Docker containers)

**Comment by bryanpizzillo** [comment]
I am also marking this as D9.x upgrade as I don't want any surprises...

**Comment by bryanpizzillo** [comment]
Also, to point out, ODEs are defaulting to 7.4 for a while now, so we have "tested" 7.4 on ODEs more than once.

**Comment by bryanpizzillo** [comment]
This passed regression tests on an ODE.

**Comment by bryanpizzillo** [comment]
This passed tests on ACSF. (Well the update itself) There is a PR for local and pipelines, but that has nothing to do with the application itself.

**Comment by bryanpizzillo** [comment]
## Instructions for Updating Local Environments
1. Shut down all CGDP containers
2. Update local PHP
    1. Open a terminal
    2. `brew update && brew install php@7.4`
    2. Follow the instructions for adding to your path
3. Rebuild your docker container
    1. Make sure you are working off a branch that has been updated with this commit
    2. Open a terminal
    2. `cd <repo_root>`
    2. `docker-compose -f ./docker/docker-compose.yml build --no-cache`
