### ISSUE TITLE
[META]: Blog Series Updates

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#3215]
For the c.gov redesign, we will be redesigning the cancer.gov blog series experience.  This ticket is to capture all the tasks related to the changes.

Task List:

- [ ] Update blog series pages
  - [ ] Implement blog subscribe using the text input and button components from the design system
- [ ] Update blog post pages

**Comment by laurelthrash** [comment]
Closing, will create a new ticket with new ticket template when this item is ready to be worked on.
