### ISSUE TITLE
Enabler: Create the NCIDS transitional theme for WWW

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3237]
# Create the NCIDS transitional theme for WWW
> **ESTIMATE** 2

In order to implement a phased approach to our NCIDS rollout, we need to create a transitional theme that mixes NCIDS and the current `cgov_common` theme front-end code. Just to note, #3068 is the creation of an `ncids_cgdp` theme once the design system is fully realized -- this ticket is for a messy theme getting us there. 

The end goal of this ticket is to have a theme that is just like cgov_common and acts like cgov_common. This will be a starting point to begin modifying and introducing NCIDS into the system. We should *reference* CSS/JS over copying where possible unless it becomes really hard to do or impossible. (e.g., entry points will should be copied so we can selectively remove/include libraries and styles) 

### 1. Setup the Theme
- [ ] Create the theme folder in `docroot/profiles/custom/cgov_site/themes/custom/ncids_trans`
   * NOTE: This should NOT go in the `cgov` folder
- [ ] Copy package.json and package-lock.json from `docroot/profiles/custom/cgov_site/themes/custom/cgov` 
   * Add ncids-css && ncids-js as dependencies.
- [ ] Copy the `/templates` folder from `docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common`  
- [ ] Setup webpack and front-end build items leveraging the same process from cgov & cgov_common
   * Currently the webpack configs are split between the cgov & cgov_common folders. This will need to be merged into a single config.
   * Setup aliases for both core and cgov_common
   * NOTE: YOU CANNOT CREATE A CONFIG FOLDER for your configs. This name conflicts with Drupal's configuration management folder.
- [ ] Copy the Drupal Theme layouts and libraries files over, with the new name. (e.g. cgov_common.libraries.yml -> ncids_trans.libraries.yml)
- [ ] Copy the .theme file from cgov_common, but remove anything related to the theme overrides:
   * The global for $_theme_name
   * The color theme overrides in function `cgov_common_preprocess_html`
      * I think the $hasTranslations should be either removed, or default to true.
   * Remove `cgov_common_preprocess_page`
### 2. Update the Build Tools
- [ ] Update BLT to change the front-end build process

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* References: *URL to web site with examples*
* Web Page: *Here goes a URL to an existing web page*

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Sub-Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by sarinapadilla** [comment]
Closing this ticket as it has been fixed by #3393!
