### ISSUE TITLE
Enabler: Update PHP to 8.0

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3266]
# Update PHP to 8.0
> **ESTIMATE** TBD

Acquia is retiring PHP 7.4 10/2022 in lieu of 8.0. Technically PHP 8.1 is out. So if ACSF and ACE support 8.1 when this ticket is being worked on then it would make sense to go to 8.1. **8.1 has issues with our code, so this ticket is just for 8.0.**

> **_NOTE:_** This should probably be done around the time that Acquia starts defaulting ODEs to 8.0.

### Tasks
- [x] Update Docker stack
   * This includes figuring out which PHP module .ini files have to be changed out. (e.g. xdebug.ini changed a bunch from 7.2->7.3)
- [x] Update acquia-pipelines.yaml
- [ ] Change ACE and ACSF web server settings through the UI.
- [ ] Anything else missed from above...

### Previous upgrade tickets
* #3105
* #2523
