### ISSUE TITLE
Build: Integrate Search Component into Header

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#3280]
### Integrate Search component based on design specs/requirements documented in this ticket into the Header for redesign

> **ESTIMATE** TBD

## Design Definition of Done
*When all criteria below are met.*

### Design
- [ ] Design component. Link to design ticket:
- [ ] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [ ] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section*
* Related USWDS Links: *Here goes a URL to an existing web page*

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

### InVision: 
  * DSM link: *insert link here, or enter N/A if not needed*
  * Desktop mockup: *insert link here, or enter N/A if not needed*
  * Tablet mockup: *insert link here, or N/A if not needed*
  * Mobile mockup: *insert link here, or N/A if not needed*

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: User is using Search on desktop
  Given the user is on a screen size 1024px and larger
  When the user clicks on the search box
  Then they will be able to enter text
     And autosuggest up to 10 items show
  When the user presses enter or clicks on the search icon
  Then the user will be taken to a search results page
  When the user clicks on suggested item and clicks on the search icon
  Then the user will be taken to a search results page
```

```gherkin
Scenario: User is using Search on Mobile
  Given the user is on a screen size 1023px or less
  Then the search box appears on the right of the Menu button
  When the user clicks on the search box
  Then they will be able to enter text
     And autosuggest up to 10 items show
  When the user presses enter or clicks on the search icon
  Then the user will be taken to a search results page
  When the user clicks on suggested item and clicks on the search icon
  Then the user will be taken to a search results page
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by bryanpizzillo** [comment]
This is a dupe of #3280
