### ISSUE TITLE
YAML Content Creation for SVPC

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3300]
We need to create YAML content that encompasses the changes that are being made with the SVPC project. This YAML content should have the same structure as what will be put on production. 

**Parent Issues:**
* #3231 
* #3230 
* #3229 
* #3257 

### Sub-Tasks
- [ ] create Liver Cancer SVPC summaries
    * What is Liver Cancer
    * Liver Cancer Causes, Risk Factors, and Prevention
    * Liver Cancer Diagnosis
    * Liver Cancer Treatment
- [ ] create Liver Cancer SVPC summaries Spanish translations
    * What is Liver Cancer - Spanish
    * Liver Cancer Causes, Risk Factors, and Prevention - Spanish
    * Liver Cancer Diagnosis - Spanish
    * Liver Cancer Treatment - Spanish
- [ ] create Liver Cancer CTHP
- [ ] create Liver Cancer CTHP Spanish translation

### Notes
* The CTHP pages do not need to be an exact reflection of what is on Prod. We need shell pages in place that have the correct URLs, so that the left nav on the SVPC pages works correctly.
* We don't currently have Spanish translations of the Liver Cancer SVPCs, so for now we can just set the page language to be Spanish and append " - Spanish" to some titles/browser titles/descriptions/etc for clarification. We need these pages in place now to confirm that language toggles are working correctly. Once we get the translated content, we can update these files.

**Comment by KateMashkinaNIH** [comment]
the only file that I haven't seen before is liver-cthp.yaml - the other 4 looks good
