### ISSUE TITLE
Discovery: Link to DOC of program/initiative in microsite footer

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/cgov-digital-platform#3359]
Design: [1 Discovery Phase](https://lion.box.com/s/r4vh9g37fps4iafbw41cinahthug8ugf)

Feedback from review on sub-branding discovery work (#370) 

### Links to related tickets
- Direction Ticket: ...
- Solution Ticket: ...
- Build Ticket(s): ...

### Timeline
*Identify start and end times for discovery work*

### Definition of Done/Complete
*All findings and synthesis will be documented in a shared Mural board for consistency, communication, and reference*

Mural Board Link: *Add you link here*

### What do you want to learn?
- What are the goals and/or mission?
- Who is our audience?
	- As a [role], I want [feature], so that [benefit]
- What are the known user expectations?
- What goals and tasks should be supported?
- What known user problems do we need to solve?
- What are the required features?

### Organization Goals
1. Goal
2. Goal
3. Goal

### Tasks
*Update the list and remove Potential once the scope of the discovery has been set*
- [ ]  Drupal reporting
	- *Link to report*
- [ ]  Synthesis of any existing analytics data around use and function
	- *Link to report* 
- [ ]  High-level heuristic review of feature
	- *Link to review*  
- [ ]  Technical or accessibility flag
	- *Link to flag report* 
- [ ]  Best practices around use of feature
	- *Link to report*
- [ ]  Persona
	- *Link to personas*  
- [ ]  User empathy exploration and synthesis (Empathy Map as a deliverable)
	- *Link to empathy map* 
- [ ]  Journey Mapping
	- *Link to journey map*  

### Key Opportunities
*Document they discovered key opportunities and add a p1, p2, p3, or p4 to establish its priority*
1. Opportunity one
2. Opportunity two
3. Opportunity three

### Resources and Links
*Related links go here*

### Notes
*Complementary notes if necessary.*
