### ISSUE TITLE
Story: Update Inner Pages for NCIDS Layout

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3379]
## As a user I would like to view inner page content using the NCIDS so that I have a better navigation experience
> **ESTIMATE** 8

This ticket is to update those inner pages that use the default page layout, i.e. the layout with a side nav on the left and a content area on the right. This applies to:
* Articles
* Press Releases
* Events
* Biographies
* Cancer Centers
* Cancer Research Listing Pages
* PDQ Drug Info Summary
* PDQ Cancer Info Summary
* Video
* Infographic

As part of this ticket, the Inner Pages background color should be updated to be #FFFFFF
### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*

---

### Prerequisites
- [x] #3240
- [ ] https://github.com/NCIOCPL/cgov-digital-platform/issues/3237 

### Tasks
- [x] Setup ncids-common.scss to pull in the NCIDS
   - This includes pulling in legacy css and making inner content look correct. Add the legacy wrapper.
- [ ] Setup any of the other entry points (if needed, but they are usually blank)
   - You will need to update the ncids_trans.libraries.yaml to change the "entry points" to have a dependency on ncids-global instead of the legacy-global.
- [x] Update the global page template (`templates/layout/page.html.twig`) to match the Spike template
- [x] Update the node templates (listed below) to:
   - swap out old container divs with new ones
   - update the main-content ids (so the skipnav works) 
   - add the legacy wrapper
   - remove the page options. This should be removing `{{ drupal_block('page_options') }}` in most cases.
- [ ] Work around issues with legacy css. 
  - @sarinapadilla to provide a list of special cases

#### Node Templates
  - `templates/content/article/node--cgov-article--full.html.twig`
    - [ ] Article without on this page (OTP), with Related Resources, Pull Quotes: https://www.cancer.gov/about-cancer/coping/feelings
    - [ ] Article with OTP, Lead Image and Related Resources: https://www.cancer.gov/research/areas/causes
    - [ ] Article with intro text, and OTP: https://www.cancer.gov/about-cancer/coping/survivorship/late-effects
    - [ ] Article with OTP, Image Carousels, Selected References, Related Resources: https://www.cancer.gov/types/skin/moles-fact-sheet
    - [ ] Article with Table: https://www.cancer.gov/grants-training/manage-award/contacts
    - [ ] Article with High Charts and Table: https://www.cancer.gov/about-nci/budget/fact-book/data/extramural
    - [ ] Article with Video Carousel: https://www.cancer.gov/research/nci-role/intramural
    - [ ] Article/ "Factsheet" with video: https://www.cancer.gov/about-cancer/treatment/types/stem-cell-transplant/stem-cell-fact-sheet
    - [ ] Article with callout box (bottom): https://www.cancer.gov/about-cancer/treatment/types/immunotherapy/angiogenesis-inhibitors-fact-sheet
    - [ ] DCEG Article with callout box (right): https://dceg.cancer.gov/about/organization
    - [ ] Physics Article with sortable table: https://physics.cancer.gov/research-funding/funding-opportunities
    - [ ] NCI-Connect Article: https://www.cancer.gov/rare-brain-spine-tumor/tumors/choroid-plexus-tumors
    - [ ] Nano Article: https://www.cancer.gov/nano/cancer-nanotechnology/safety
    - [ ] MyPart Article: https://www.cancer.gov/pediatric-adult-rare-tumor/participate/role-advocacy
   * Syndication?? 
  - `templates/content/event/node--cgov-event--full.html.twig`
    - [ ] DCEG: https://dceg.cancer.gov/news-events/events/sargen-skin-cancer-prevention
    - [ ] DCEG: https://dceg.cancer.gov/news-events/events/ccr-dceg-health-disparity
    - [ ] DCEG: https://dceg.cancer.gov/news-events/events/dceg-seminar-yu
    - [ ] Cancer.gov: https://www.cancer.gov/about-nci/organization/cgh/events/mentorship-and-career-development-roundtable-asco-2022-annual-meeting
    - [ ] CGov: https://www.cancer.gov/about-nci/organization/cgh/events/equity-and-representation-in-global-oncology-research
  - `templates/content/biography/node--cgov-biography--full.html.twig`
    - [ ] DCEG: https://dceg.cancer.gov/about/staff-directory/abnet-christian
    - [ ] DCEG: https://dceg.cancer.gov/fellowship-training/fellowship-experience/meet-fellows/ltg/abdolalizadeh-ehssan
    - [ ] Nano: https://www.cancer.gov/nano/research/ncl/about/teagan-ware
    - [ ] 
  - `templates/content/cancer_center`
    - [ ] CGov: https://www.cancer.gov/research/infrastructure/cancer-centers/find/uvacc
    - [ ] CGov: https://www.cancer.gov/research/infrastructure/cancer-centers/find/dartmouthnorriscotton
    - [ ] CGov: https://www.cancer.gov/research/infrastructure/cancer-centers/find/kucc
  - `templates/content/cancer_research`
    - [ ] With Callout: https://www.cancer.gov/types/lung/research/articles
    - [ ] Without Callout: https://www.cancer.gov/types/brain/research
  - `templates/content/pdq/node--pdq-drug-information-summary--full.html.twig`
    - [ ] https://www.cancer.gov/about-cancer/treatment/drugs/trastuzumab
    - [ ] https://www.cancer.gov/about-cancer/treatment/drugs/bevacizumab
  - `templates/content/pdq/node--pdq-cancer-information-summary--full.html.twig`
    - [ ] PDQ HP summary with tables: https://www.cancer.gov/about-cancer/treatment/cam/hp/cartilage-pdq
    - [ ] PDQ HP summary (longest summary): https://www.cancer.gov/types/breast/hp/breast-ovarian-genetics-pdq
    - [ ] PDQ Patient summary with OTP: https://www.cancer.gov/types/lung/patient/non-small-cell-lung-treatment-pdq
    - [ ] PDQ SVPC Patient content with OTP: https://www.cancer.gov/types/liver/what-is-liver-cancer/treatment
    - [ ] PDQ SVPC Patient content without OTP: https://www.cancer.gov/types/liver/bile-duct-cancer
    - [ ] PDQ SVPC Patient content with intro text above OTP: https://www.cancer.gov/types/liver/bile-duct-cancer/treatment
  - `templates/content/press_release`
    - [ ] With single reference: https://www.cancer.gov/news-events/press-releases/2022/cancer-death-rates-black-people
    - [ ] With no references: https://www.cancer.gov/news-events/press-releases/2022/nci-director-norman-sharpless-steps-down
  - `templates/media/video/media--cgov-video--full.html.twig`
    - [ ] CGov Video with content: https://www.cancer.gov/research/key-initiatives/moonshot-cancer-initiative/seminar-series/cmss-feb-2022-hereditary-cancers-video
    - [ ] CGov Video with content: https://www.cancer.gov/about-nci/organization/cgh/global-cancer-conversations/kamarulzaman-video
    - [ ] Nano Video with content: https://www.cancer.gov/nano/about/nanotechnology-journey-video
    - [ ] MyPart Video: https://www.cancer.gov/pediatric-adult-rare-tumor/rare-tumors/rare-bone-tumors/chordoma/chordomafoundationnhsvideo
    - [ ] DCEG Video with content: https://dceg.cancer.gov/news-events/videos/gameon-oncoarray-video
    - [ ] DCEG Video: https://dceg.cancer.gov/fellowship-training/apply/find-nih-mentor-video
  - `templates/media/infographic/media--cgov-infographic--full.html.twig`
    - [ ] CGov Infographic: https://www.cancer.gov/research/areas/treatment/nci-formulary-infographic
    - [ ] CGov Infographic with content: https://www.cancer.gov/research/areas/childhood/childhood-cancer-data-initiative/molecular-characterization/mci-infographic
    - [ ] NCI Connect Infographic: https://www.cancer.gov/rare-brain-spine-tumor/living/symptoms/sleep-disturbance/ways-to-improve-sleep-infographic
    - [ ] MyPart Infographic with content: https://www.cancer.gov/pediatric-adult-rare-tumor/rare-tumors/mypart-focus-rare-cancer
    - [ ] DCEG Infographic with content: https://dceg.cancer.gov/research/what-we-study/pa-sitting-infographic

### Technical Notes
From #3241:
Inner Page: update templates/layout/page.html.twig (put in placeholder html for the first version) with CSS and JS getting pulled in correctly (so it will be static html in each of the regions)

**Comment by meglake** [comment]
Update from discussion at 6/3 (Redesign: Weekly Requirements Discussions)

- Definitely need to keep syndication templates
- Syndication templates are only used on articles. 
- Will need to test to make sure syndication is displaying properly (Question: Can we test the syndication of pages some how on our side?)

**Comment by sarinapadilla** [comment]
Closing this ticket as it has been fixed by PR #3393!
