### ISSUE TITLE
Story: Update Mini Landing Pages for NCIDS Layout

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3380]
## As a user, I would like to view Mini Landing Page content using the NCIDS, so that I have a better navigation experience.

This ticket is to update the mini landing page template which uses the default page layout, i.e. the layout with a side nav on the left and a content area on the right.

As part of this ticket, the Inner Pages background color should be updated to be #FFFFFF

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] #3240
- [x] #3375

### Tasks
- [ ] Setup mini landing page entrypoint
   - You will need to update the ncids_trans.libraries.yaml to change the "entry points" to have a dependency on ncids-global instead of the legacy-global.
- [ ] Update `templates/content/mini_landing/page--cgov-mini-landing--full.html.twig` to match the Spike template
- [ ] Update the node templates (listed below) to:
   - swap out old container divs with new ones
   - update the main-content ids (so the skipnav works) 
   - add the legacy wrapper
   - remove the page options. This should be removing `{{ drupal_block('page_options') }}` in most cases.
- [ ] Fix the reference to monte in the scss

#### Node templates
- [ ] `templates/content/mini_landing/node--cgov-mini-landing--full.html.twig`
  - Mini Landing with List with Images: https://www.cancer.gov/about-cancer/coping
  - Mini Landing with content: https://www.cancer.gov/types/liver
  - Mini Landing with Dynamic List: https://www.cancer.gov/news-events/press-releases/2022
  - Mini Landing: https://www.cancer.gov/types/by-body-location
  - DCEG Mini Landing with Dynamic List: https://dceg.cancer.gov/news-events/events/past-events
- [ ]  `templates/content/mini_landing/field--paragraph--cgov-two-item-feature-row.html.twig`
  - https://www.cancer.gov/research/cancer-research-partners/research-studies
  - https://www.cancer.gov/about-nci/organization/ccct

### Technical Notes
* `templates/content/mini_landing/page--cgov-mini-landing--full.html.twig` is a new file for this theme

**Comment by bennettcc** [comment]
This is currently being design reviewed on: https://ncigovcdode479.prod.acquia-sites.com/

**Comment by sarinapadilla** [comment]
Closing this ticket as it has been fixed by PR #3431!
