### ISSUE TITLE
Story: Update Blog Series for NCIDS Layout

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3381]
## As a user, I would like to view Blog Series content using the NCIDS, so that I have a better navigation experience.

This ticket is to update blog series templates that display the layout with the content on the left and the blog featured posts/categories/archive on the right.

As part of this ticket, the Inner Pages background color should be updated to be #FFFFFF

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] #3240
- [x] #3375 

### Tasks
- [ ] Setup blog post and series entrypoint
   - You will need to update the ncids_trans.libraries.yaml to change the "entry points" to have a dependency on ncids-global instead of the legacy-global.
- [ ] Update to match the Spike template
  - `templates/content/blog/page--cgov-blog-post.html.twig`
  - `templates/content/blog/page--cgov-blog-series.html.twig`
- [ ] Update the node templates (listed below) to:
   - swap out old container divs with new ones
   - update the main-content ids (so the skipnav works) 
   - add the legacy wrapper
   - remove the page options. This should be removing `{{ drupal_block('page_options') }}` in most cases.
- [ ] fix issue with getting Page Title on breadcrumbs https://github.com/NCIOCPL/cgov-digital-platform/issues/3366
- [ ] What to do with the right sidebar (Feature posts, categories, archive)? Does it make more sense to redo the component or just the existing legacy stuff

#### Node templates
- [ ] `templates/content/blog/node--cgov-blog-post--full.html.twig`
  - https://www.cancer.gov/news-events/cancer-currents-blog/2022/ivosidenib-chemotherapy-aml-idh1
- [ ] `templates/content/blog/node--cgov-blog-series--full.html.twig`
  - https://www.cancer.gov/news-events/cancer-currents-blog
  - https://www.cancer.gov/about-nci/organization/ccg/blog
  - https://www.cancer.gov/grants-training/nci-bottom-line-blog
  - DCEG: https://dceg.cancer.gov/news-events/news
  - NCI Connect: https://www.cancer.gov/rare-brain-spine-tumor/blog
  - 

### Technical Notes
- Series template: https://www.cancer.gov/news-events/cancer-currents-blog, https://www.cancer.gov/news-events/cancer-currents-blog?topic=prevention
- Post template: https://www.cancer.gov/news-events/cancer-currents-blog/2022/nivolumab-chemotherapy-neoadjuvant-lung-cancer
- We need to work on on entrypoints for blog posts and blog series, it doesn't make sense to have the same Common.scss

**Comment by bennettcc** [comment]
Moving this ticket to on hold to focus on header story in S34. Will resume in S35

**Comment by bennettcc** [comment]
5 points accomplished in S35, 3 SP to carry over into S35

**Comment by sarinapadilla** [comment]
Closing this ticket as it has been fixed by PR #3453!
