### ISSUE TITLE
Story: Update Home/Landing Pages for NCIDS Layout

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3383]
## As a user, I would like to view Home/Landing Page content using the NCIDS, so that I have a better navigation experience.

This ticket is to update the home/landing page template which uses a full-page layout without left navigation.

As part of this ticket, the home and landing pages background color should be updated to base-lightest (#F0F0F0)
  - Replaces the tannish background color on current home and landing pages (current page: https://www.cancer.gov/) should be the background color from the bottom of the header/mega menu until the top of the footer, minus the multimedia row that will stay as is (teal background)
  - Replaces the background "sides" on special report template pages (AP, NCA50, Patient Portal) but the current body container white background, header, and footer should stay the same (current page: https://www.cancer.gov/research/annual-plan)

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] #3240

### Tasks
- [ ] Setup ncids-common.scss to pull in the NCIDS
   - This includes pulling in legacy css
- [ ] Setup any of the other entry points (if needed, but they are usually blank)
   - You will need to update the ncids_trans.libraries.yaml to change the "entry points" to have a dependency on ncids-global instead of the legacy-global.
- [ ] Update page templates (listed below)  to match the Spike template
- [ ] Update the node templates (listed below) to:
   - swap out old container divs with new ones
   - update the main-content ids (so the skipnav works) 
   - add the legacy wrapper
   - remove the page options. This should be removing `{{ drupal_block('page_options') }}` in most cases.
- [ ] #3418
  - break out node template between normal home/landing and special report (dceg should die) 

#### Page Templates
- [ ] `templates/content/home_landing/page--cgov-home-landing.html.twig`
  - https://www.cancer.gov
  - https://www.cancer.gov/types
  - https://www.cancer.gov/news-events
  - https://www.cancer.gov/espanol
  - https://dceg.cancer.gov/
- [ ] `templates/content/home_landing/page--cgov-home-landing--special-report.html.twig` ???????????
  - https://www.cancer.gov/news-events/nca50?cid=wl_int_en_ccblog_nca50 
  - https://www.cancer.gov/research/annual-plan
  - https://www.cancer.gov/research/cancer-research-partners

#### Node Templates
- [ ] `templates/content/home_landing/node--cgov-home-landing--full.html.twig`

### Technical Notes
- DCEG will not use the existing template in new theme
- Home and landings should not have page options in new theme
- The logic within the twig files may need to be redone, as Home does not have a page title, and removing the page option block will change the page style
- base-lightest (#F0F0F0) should be the background color from the bottom of the header/mega menu until the top of the footer, minus the multimedia row that will stay as is (teal background)

**Comment by olitharp-nci** [comment]
To future me - talk to designers about home page styling when removing page options

**Comment by laurelthrash** [comment]
As mentioned in the technical comments, #F0F0F0 should be the background color from the bottom of the header/mega menu until the top of the footer, minus the multimedia row that will stay as is (teal background).

**Comment by bennettcc** [comment]
This is currently being design reviewed on: https://ncigovcdode479.prod.acquia-sites.com/

**Comment by sarinapadilla** [comment]
Closing this ticket as it has been fixed by PR #3431!
