### ISSUE TITLE
Story: Update CTHPs for NCIDS Layout

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3384]
## As a user, I would like to view CTHP content using the NCIDS, so that I have a better navigation experience.

This ticket is to update the CTHP template which uses a full-page layout without left navigation.

As part of this ticket, the Inner Pages background color should be updated to be the same for the Health Professional and Patient Version: base-lightest (#F0F0F0). 

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x]  #3240

### Tasks

- [ ] Setup ncids-common.scss to pull in the NCIDS
   - This includes pulling in legacy css
- [ ] Setup any of the other entry points (if needed, but they are usually blank)
   - You will need to update the ncids_trans.libraries.yaml to change the "entry points" to have a dependency on ncids-global instead of the legacy-global.
- [ ] Update page templates (listed below)  to match the Spike template
- [ ] Update the node templates (listed below) to:
   - swap out old container divs with new ones
   - update the main-content ids (so the skipnav works) 
   - add the legacy wrapper
   - remove the page options. This should be removing `{{ drupal_block('page_options') }}` in most cases.
- [ ] fix any |trans tags.

#### Page Templates
- [ ]  templates/content/cthp/page--cgov-cthp.html.twig
  - https://www.cancer.gov/types/lung
  - https://www.cancer.gov/types/leukemia
  - With research list card: https://www.cancer.gov/types/brain

#### Node Templates
- [ ] templates/content/cthp/node--cgov-cthp--full.html.twig

### Technical Notes
- Foundation can be replaced on the cards, but are many different types of cards and card combinations

**Comment by bennettcc** [comment]
This is currently being design reviewed on: https://ncigovcdode479.prod.acquia-sites.com/

**Comment by sarinapadilla** [comment]
Closing this ticket as it has been fixed by PR #3431!
