### ISSUE TITLE
Story: Update Application Pages for NCIDS Layout

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3385]
## As a user, I would like to view Application Page content using the NCIDS, so that I have a better navigation experience.

This ticket is to update the application page templates which use both a full-page layout without left navigation and a layout with left navigation.

As part of this ticket, the Inner Pages background color should be updated to be #FFFFFF

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] #3240 

### Tasks
- [ ] templates/content/application_page/page--cgov-application-page--no-left-nav.html.twig
  - https://www.cancer.gov/search/results?swKeyword=cancer
  - https://www.cancer.gov/about-cancer/treatment/clinical-trials/search
  - https://www.cancer.gov/research/resources
- [ ] templates/content/application_page/page--cgov-application-page--full.html.twig
  - https://www.cancer.gov/publications/dictionaries/cancer-terms
  - https://www.cancer.gov/publications/dictionaries/cancer-drug
  - https://www.cancer.gov/publications/dictionaries/genetics-dictionary

- [ ] update all app modules (new task?)
- [ ] templates/app_module/r4r/app-module--cgov-r4r-app.html.twig
- [ ] templates/layout/html--cgov-application-page.html.twig:
   - [ ] replace skipnav with `.usa-skipnav` 

#### Node templates
- [ ] templates/content/application_page/node--cgov-application-page--full.html.twig

### Technical Notes
- CTS should be moved to be a generic app module by the time we get here.

**Comment by bennettcc** [comment]
5 SP's completed in S36, 3 remaining in S37

**Comment by sarinapadilla** [comment]
Closing this ticket, as it was fixed by PR #3552!
