### ISSUE TITLE
Story: Remove Legacy Regions and CSS/JS from ncids_trans theme

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3387]
In order to still be able to navigate the site and view templates that we have not worked on yet, we will be leaving in the old regions and blocks, as well as the old common.css and common.js. Once we have updated all the page and node templates to use the NCIDS, we need to remove the old regions, blocks added to those regions, and legacy css from the ncids_trans theme.

> **ESTIMATE** 2

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] #3379 
- [x] #3380 
- [x] #3381 
- [x] #3383 
- [x] #3384 
- [x] #3385 
- [x] #3386 

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- [ ] Remove Common.css and Common.js from entrypoints
- [ ] Remove the regions from the theme.info file
- [ ] Update the YAML content to remove 000_ncids_trans_legacy_blocks.content.yml
- [ ] Cleanup skipnav classes to match ONLY USWDS
- [ ] Remove noto sans from html.html.twig
