### ISSUE TITLE
Enabler: Enable virus scanning for uploads

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/cgov-digital-platform#3398]
# Enable virus scanning for uploads

**UPDATE AFTER v2.3.0:** There are a lot of memory issues using the ClamAV Drupal module. Each file upload requires 1GB of RAM for the scan. Our dev/test tier consistently has around .8GB free. Production usually has only around 1.8GB free. Using ClamAV was not a scalable approach and we need to identify a different approach to handling this.  See #3781 for more information on the issue.

----------------------

** OLD TICKET **
We need to enable virus scanning for uploads using the ClamAV module. Acquia provides ClamAV on the Acquia infrastructure. 

We may also want to investigate a cron job to scan files on the server at regular intervals. Or this may only be needed as a one-time task when first enabling ClamAV.

### Tasks

**Development**

- [x] Update dockerfile for local development to [install ClamAV](https://www.drupal.org/project/clamav)
- [x] Install and enable the [ClamAV Drupal module](https://duckduckgo.com/?q=clamav+drupal+module&t=brave&ia=web)
- [x] [Configure ClamAV](https://docs.acquia.com/cloud-platform/manage/antivirus/) module to point to executable

**Ops**

- [ ] Identify whether `clamscan` is present on CI/CD pipelines and if an automated test to scan a file can be created
    - If so, do we add the test file to our code repo? (GitHub might not appreciate it.) 
    - Do we download the test file from a known location?
    - Forego the test entirely and just do the manual test?
    - It looks like the eicar test file is just a text string. We could include this in a test but broken up into pieces, which would avoid making any scanners cranky. It could then be reassembled into a file by the test for scanning.
- [x] Work with QA team to get a manual test with the [EICAR test virus](https://en.wikipedia.org/wiki/EICAR_test_file) added to the regression tests ([download links](https://www.eicar.org/download-anti-malware-testfile/))
- [ ] Initiate a one-time scan on the PROD servers of all previously uploaded material using `clamscan -ri`

> **ESTIMATE** TBD

### Resources:
* Instructions: https://docs.acquia.com/cloud-platform/manage/antivirus/
* Background: https://docs.acquia.com/cloud-platform/arch/security/#cloud-antivirus-uploads
* Module: https://www.drupal.org/project/clamav

### Prerequisites
- None

### Sub-Tasks
- Test using test virus

### Testing Steps
- Log in to CMS and attempt to upload a file (image or otherwise) into the system.
    - Expected:  Upload should complete and you will be able to save the file.
- Extra test: Log in to CMS and attempt to upload the EICAR test virus.
    - Expected: Upload should get rejected.

**Comment by jfrank-nih** [comment]
Assigning to myself to figure out the dockerfile setup.

**Comment by jfrank-nih** [comment]
I've got [a version of CGDP here](https://github.com/jfrank-nih/cgov-digital-platform/tree/ticket/3398-clam-av) that installs clamscan in Docker and performs a clamscan update. Assigning back to @ramu-nih for the Drupal portions when he's ready to look into them.

**Comment by jfrank-nih** [comment]
@ramu-nih I've got a branch created with the updated docker file. I'll add you as a contributor on it so we can collaborate on this one. I've pulled in the changes from https://github.com/NCIOCPL/cgov-digital-platform/pull/3465 to make it work on NIH VPN.

**Comment by ramu-nih** [comment]
@santwuma Drupal side work is completed. I think @jfrank-nih is working on automation tests.
I am assigning this to @jfrank-nih

**Comment by bryanpizzillo** [comment]
Re-opening this ticket as the Drupal module is not scalable. Or maybe not scalable in PHP 8, or who knows what. Our most recent deployment has issues repeatable occurring in dev/test, as well as a number of cases on prod the day after v2.3.0 was deployed.

**Comment by santwuma** [comment]
@James exploring new solution to scan viruses that will not need a platform deployment. Still tracking against the June 5 timeline.

**Comment by blairlearn** [comment]
[This module was deactivated on 3/2/2023](https://github.com/NCIOCPL/cgov-digital-platform/issues/3781#issuecomment-1458856865) and disabled in b0c93d89047b6791beaac8d18bc2d5249e623bbf (ticket #3781).

The module will be completely removed by #4098.
