### ISSUE TITLE
Navigation Structure Epic

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#341]
This Epic is to create the Navigation Structure
- [x] Implement Display and Interaction for Mega Menu #342 
- [x] Section Navigation - Navigation Structure #343
- [x] Mobile Menu/Navigation - Navigation Structure #345 
- [x] Mobile Menu/Navigation - Navigation Structure #173 
- [x] Pretty URL for "Node" Type #174 
- [x] Breadcrumbs on Desktop and Tablet #346
