### ISSUE TITLE
CTS Proactive Chat pop-up update

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3444]
## We need to update the proactive chat pop-up url (due to Livehelp upgrade) so the user experience for Livehelp on CGov will be consistent. Related JIRA ticket https://tracker.nci.nih.gov/browse/CGOV-16414 

> **ESTIMATE** low effort, code change due by 7/30/22

### Acceptance Criteria

```gherkin
Scenario: Proactive pop-up "Chat Now" link
  Given i'm a user on cancer.gov
    And browsing through the Clinical Trial pages
  When  the proactive chat pop up and i click on the "Chat Now" link
  Then  i should be directed to livehelpcancer.gov launch window (url = https://livehelp.cancer.gov/app/chat/chat_launch)

```

### Resources:
* Web Page: [*Here goes a URL to an existing web page*](https://www.cancer.gov/about-cancer/treatment/clinical-trials/search)

### Notes
Approach approved by ODDC leads during 7/15 meeting
- Dynamic Listing Pages configuration object should be updated in Drupal to allow this change to apply to No Trials pages 

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
-  2nd technical solution:  it could be done as a flag so we can “flip a switch” when the Livehelp service goes live

**Comment by venglisch** [comment]
Does a page in the DP container exist that lets me test the Spanish version of the proactive chat pop-up?
Who would know?

**Comment by venglisch** [comment]
Note regarding the link.
The link will point to 
- https://livehelp.cancer.gov (English)
- https://livehelp-es.cancer.gov (Spanish)
The user is automatically directed to "/app/chat/chat_launch"

**Comment by kate-mashkina** [comment]
Test URLs :
Spanish:
https://ncigovcdode491.prod.acquia-sites.com/espanol/cancer/tratamiento/medicamentos
English:
https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search
https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/advanced
https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/r?loc=0&rl=2
https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/v?id=NCI-2014-01507&loc=0&rl=2
https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/disease/breast-cancer
https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/intervention/trastuzumab
https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/intervention/spiroplatin
https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/disease/breast-cancer/treatment/spiroplatin

**Comment by alinai** [comment]
Status is missing on ODE in both English and Spanish:

![image](https://user-images.githubusercontent.com/28455973/183700863-26c6ccfd-b707-416f-b963-a01bc69421eb.png)
![image](https://user-images.githubusercontent.com/28455973/183701100-95643782-dbfd-4a94-9584-bbfdcd653059.png)

**Comment by venglisch** [comment]
I thought we're just testing the proactive chat window?

**Comment by venglisch** [comment]
Yes, the "Status" label has been dropped from the chat window.

I also adjusted the font sizes because some sections used a larger font than others.

(I can't sneak anything passed your eyes, can I? )

**Comment by alinai** [comment]
> Yes, the "Status" label has been dropped from the chat window.
> 
> I also adjusted the font sizes because some sections used a larger font than others.
> 
> (I can't sneak anything passed your eyes, can I? )

Thanks for confirming @venglisch.

**Comment by alinai** [comment]
Noticed Prod issue in the English version:
The Spanish url on the English version has "L" and "H" in upper case in the url in both Prod and ODE.  On clicking "Iniciar Chat" we are redirected to the url https://livehelp-es.cancer.gov/app/chat/chat_launch. Not sure why we show https://LiveHelp-es.cancer.gov/ on the page.
![image](https://user-images.githubusercontent.com/28455973/183705062-6c568667-8ea1-43bf-bb38-ce2ac4b7c9e7.png)

**Comment by alinai** [comment]
@kate-mashkina, @santwuma , verified that 
Clicking "Chat Now" button on **Basic CTS Form** user is redirected to : https://nci--tst.custhelp.com/app/chat/chat_launch
Clicking "Chat Now" button on **CTS Search Results page** user is redirected to :: https://nci--tst.custhelp.com/app/chat/chat_launch
Clicking "Chat Now" button on **Advanced CTS Form** user is redirected to : https://nci--tst.custhelp.com/app/chat/chat_launch
Clicking "Chat Now" button on **CTS View page** user is redirected to : https://nci--tst.custhelp.com/app/chat/chat_launch
Clicking "Chat Now" button on **No trial page** (https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/r?loc=0&q=penguin&rl=1) user is redirected to : 
redirected to https://nci--tst.custhelp.com/app/chat/chat_launch
Clicking "Chat Now" button on **Invalid Param page** (https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/r?a=190&loc=0&rl=1) user is redirected to :
https://nci--tst.custhelp.com/app/chat/chat_launch

**Comment by SupriyaSaxena0605** [comment]
Purple Boxes for Clinical Trials, Cancer Information and Quitting Smoking are bigger in width on ODE(200 px) as compared to Prod(180 px). 
![image](https://user-images.githubusercontent.com/31008800/183709831-f57c8c64-b555-4d70-bcfa-10e92b429090.png)

**Comment by kate-mashkina** [comment]
@welshja the click event on LiveHelp chat popup is gone from CTS pages

**Comment by alinai** [comment]
@santwuma , @kate-mashkina , I don't see the hover color changing on hovering the purple buttons on ODE.

**Comment by santwuma** [comment]
@alinai confirming "status" and font changes are fine and previously passed UX review in JIRA (added related JIRA ticket to this ticket details). I think the https://livehelp-es.cancer.gov/ url on the pop-up box should be fine, since that's what it currently is in prod and was provided by CIS. @venglisch can confirm. 

Test results look good to me. @sarinapadilla can you confirm as well?

**Comment by alinai** [comment]
> @santwuma , @kate-mashkina , I don't see the hover color changing on hovering the purple buttons on ODE.

@santwuma , can you please confirm if the issue I reported above looks good to you as well?

**Comment by SupriyaSaxena0605** [comment]
> Purple Boxes for Clinical Trials, Cancer Information and Quitting Smoking are bigger in width on ODE(200 px) as compared to Prod(180 px). ![image](https://user-images.githubusercontent.com/31008800/183710143-df177f04-0e91-4c99-abfd-102ebd0bb516.png)

@santwuma , please confirm if this issue looks good too.

**Comment by SupriyaSaxena0605** [comment]
@kate-mashkina, @santwuma , verified that
English:
Clicking "Chat Now" button on DLP(https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/disease/breast-cancer), user is redirected to : https://nci--tst.custhelp.com/app/chat/chat_launch
Clicking "Chat Now" button on DLP(https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/intervention/trastuzumab), user is redirected to :: https://nci--tst.custhelp.com/app/chat/chat_launch
Clicking "Chat Now" button on No trial disease DLP(https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/disease/breast-cancer/treatment/spiroplatin), user is redirected to : https://nci--tst.custhelp.com/app/chat/chat_launch
Clicking "Chat Now" button on No trial intervention DLP(https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/intervention/spiroplatin), user is redirected to : https://nci--tst.custhelp.com/app/chat/chat_launch

**Comment by venglisch** [comment]
> Noticed Prod issue in the English version: The Spanish url on the English version has "L" and "H" in upper case in the url in both Prod and ODE. On clicking "Iniciar Chat" we are redirected to the url https://livehelp-es.cancer.gov/app/chat/chat_launch. Not sure why we show https://LiveHelp-es.cancer.gov/ on the page. ![image](https://user-images.githubusercontent.com/28455973/183705062-6c568667-8ea1-43bf-bb38-ce2ac4b7c9e7.png)

The hostname of a URL is not case sensitive, so this isn't an issue.  Additionally, there was no change as this is how PROD displays the URL.
Our logo displays the text with "L" and "H" in upper case.  I assume the URL had been written this way to closely relate to that spelling.

**Comment by venglisch** [comment]
> Purple Boxes for Clinical Trials, Cancer Information and Quitting Smoking are bigger in width on ODE(200 px) as compared to Prod(180 px). ![image](https://user-images.githubusercontent.com/31008800/183710143-df177f04-0e91-4c99-abfd-102ebd0bb516.png)

That's correct, my feeling was that there wasn't enough padding for the button with the "Cancer Information" label.

**Comment by alinai** [comment]
> @santwuma , @kate-mashkina , I don't see the hover color changing on hovering the purple buttons on ODE.

@venglisch , can you please confirm if  this looks good to you?

**Comment by venglisch** [comment]
@alinai , you may need to reload the page because I just updated the CSS within the last 30 minutes or so.

Note to @santwuma, this CSS update is happening as part of the LiveHelp framework update and is not part of the DP code.

**Comment by alinai** [comment]
@santwuma , On ODE491, Verified that for CTS pages (English) urls:
- [ ] Clicking "Chat Now" button on Basic CTS Form user is redirected to : https://nci--tst.custhelp.com/app/chat/chat_launch
- [ ] Clicking "Chat Now" button on Advanced CTS Form user is redirected to : https://nci--tst.custhelp.com/app/chat/chat_launch
- [ ] Clicking "Chat Now" button on CTS Search Results page user is redirected to :: https://nci--tst.custhelp.com/app/chat/chat_launch
- [ ] Clicking "Chat Now" button on CTS View page user is redirected to : https://nci--tst.custhelp.com/app/chat/chat_launch
- [ ] Clicking "Chat Now" button on No Trial page (https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/r?loc=0&q=penguin&rl=1) user is redirected to :
https://nci--tst.custhelp.com/app/chat/chat_launch
- [ ] Clicking "Chat Now" button on Invalid Param page (https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/r?a=190&loc=0&rl=1) user is redirected to :
https://nci--tst.custhelp.com/app/chat/chat_launch
- [ ] Clicking "Chat Now" button on Invalid Page number (https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/r?loc=0&pn=7420&rl=1) user is redirected to :
https://nci--tst.custhelp.com/app/chat/chat_launch

On ODE491, Verified that for Spanish page https://ncigovcdode491.prod.acquia-sites.com/espanol/cancer/tratamiento/medicamentos
- [ ] Clicking "Inciar Chat" button on Spanish page (https://ncigovcdode491.prod.acquia-sites.com/espanol/cancer/tratamiento/medicamentos) user is redirected to : https://nci2--tst.custhelp.com/app/chat/chat_launch

Thanks @kate-mashkina for verifying that Analytics are working as expected.
Thanks @venglisch for fixing the reported issues.

**Comment by SupriyaSaxena0605** [comment]
@kate-mashkina, @santwuma , verified that
English:
Clicking "Chat Now" button on DLP(https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/disease/breast-cancer), user is redirected to : https://nci--tst.custhelp.com/app/chat/chat_launch
Clicking "Chat Now" button on DLP(https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/intervention/trastuzumab), user is redirected to :: https://nci--tst.custhelp.com/app/chat/chat_launch
Clicking "Chat Now" button on No trial disease DLP(https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/disease/breast-cancer/treatment/spiroplatin), user is redirected to : https://nci--tst.custhelp.com/app/chat/chat_launch
Clicking "Chat Now" button on No trial intervention DLP(https://ncigovcdode491.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/intervention/spiroplatin), user is redirected to : https://nci--tst.custhelp.com/app/chat/chat_launch
