### ISSUE TITLE
Update and Restore Highchart: Grant & Contract Awards / Institutions (FY22)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/cgov-digital-platform#3446]
SPs: 5

#### Summary
__Issue:__ The chart on the "[Grant and Contract Awards](https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/grant-contract-awards)" page under the "Grant and Contract Awards by State and Institution" section should be replaced by a highchart that contains the correct data. The data initially included in the highchart under the "Grant and Contract Awards by State and Institution" section contained inaccurate data. As a non-dev, short-term solution, we replaced the highchart with a static table that contains the correct data. 

- New (correct) data that should be reflected in the chart: [awards-by-state-and-institution-fy21 (updated 2022.06.15).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/9939832/awards-by-state-and-institution-fy21.updated.2022.06.15.xlsx)
- Old (incorrect) data that should not be reflected in the chart: [OLD awards-by-state-and-institution-fy21 (retired 2022.06.15).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/9939869/OLD.awards-by-state-and-institution-fy21.retired.2022.06.15.xlsx)

__Goal:__ To restore the highchart on the "[Grant and Contract Awards](https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/grant-contract-awards)" page under the "Grant and Contract Awards by State and Institution" section that contains accurate data (found in the attached Excel document). 

**Parent Issue:** N/A

**Tasks**
- [x] Pre-requisite: #3761 released to production
- [x] Reinstate high chart on the "[Grant and Contract Awards](https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/grant-contract-awards)" page in place of static table
- [x] Correct bug originally reported in #3329
- [x] Implement data for FY2022 
- [x] Verify data is correct and that the chart loads properly

**Note**
- When testing high chart, add test case to ensure issue reported in #3329 is addressed. 
- Initial Jira ticket for this request found here: https://tracker.nci.nih.gov/browse/CGOV-16326

### What's the updated acceptance criteria?
```gherkin
Scenario: Display Grant & Contracts Awards/Institutions HighChart

Given a user is viewing the page with the Grant & Contracts Awards/Institutions chart
When the user views the page
Then the chart loads
  And the chart loads every time!
```

**Comment by laurelthrash** [comment]
@sarinapadilla @andyvanavery to connect with @blairl-nih regarding what information is needed to reinstate the high chart. Connect with @laurelthrash on missing information. @laurelthrash to update description to clearly show previous data and updated data.

**Comment by laurelthrash** [comment]
Determined during mid-sprint check-in on 02/13 that this ticket will be completed after #3761, so that this ticket can utilize our new ability to update high charts without a code deployment.

**Comment by laurelthrash** [comment]
Determined during ODE testing meeting on 03/15 that as part of this ticket, we will address a bug also impacting this chart which is that it occasionally does not appear (initially reported in #3329). In summary, we will address the bug with the chart as well as update the data to reflect the correct data as part of this ticket.

**Comment by laurelthrash** [comment]
Next step: @seyilonge to define level of effort to complete this ticket. Cc: @santwuma

**Comment by laurelthrash** [comment]
Discussed with Factbook POs, Erin S. and Megan W., on 05/15 that we are comfortable launching the FY22 data with this chart remaining as a high chart. We will, however, being dev work to investigate the future fix. Cc: @seyilonge

**Comment by laurelthrash** [comment]
Tagging @andyvanavery31 to bring this ticket into the general O&M board for prioritization. Determined on 09/25/23 with internal Factbook team that this ticket is still a priority to be fixed. Order of priority as of 09/25/23 can be found in the "Factbook Enhancement Project 2023" project board. 

Goal is to complete this ticket by the end of January 2024, ahead of conversations beginning in February 2024 regarding the FY24 Factbook release. This will need to be slotted in around other existing prioritized work for Seyi, should Seyi remain the primary developer. 

Cc: @santwuma @sarinapadilla
