### ISSUE TITLE
Create/Update YAML content for CTS, DLPs, and MLPs

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3471]
With the launch of CTS/DLP/MLP v2, the YA(h-)ML content for the ODEs needs to be updated to reflect the new content item fields and configurations.

**Parent Issue:** #9999

### Sub-Tasks
- [x] Update CTS app module
- [x] Update Disease DLP app module
- [x] Update Intervention DLP app module
- [x] Create NCI-Supported Clinical Trials for Coronavirus MLP app module
- [x] Create Clinical Trials for Complementary or Alternative Medicine Procedure(s) MLP app module
- [x] Create Clinical Trials to Treat Adult Metastatic Brain Tumors MLP app module
- [x] Create Clinical Trials to Treat Kidney (Renal Cell) Cancer MLP app module

### Notes

*Some complementary notes if necessary:*
* This should be merged the day after CTS goes live, so we have the most recent content for testing app modules.
