### ISSUE TITLE
Create Drupal Tickets for Release 2 Iteration 1 (R2.1)

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/cgov-digital-platform#3481]
Create Drupal Dev Tickets for all Drupal tasks and components prioritized for Release 2 Iteration 1 (R2.1). 

Iteration | Component Type | Component Variation | Priority | Ticket
-- | -- | -- | -- | --
R2.1 | Hero | B. NCIDS Hero with Primary Call to Action - Light Theme | 1.1 | #3488 
R2.1 | Hero | E. Hero with Primary and Secondary Calls to Action - Light Theme | 1.1 | #3488
R2.1 | Hero | G. Multiple Calls to Action - Dark Theme | 1.1 | #3488
R2.1 | Guide Cards | A. Audience Guide Card Row | 1.1 | #3489 
R2.1 | Promo Block | B. Alternating Promo Block - Dark Text Box | 1.1 | #3490 
R2.1 | Inline Video | A. Video | 1.1 | #3491 
R2.1 | Feature Card | B.  Feature Card Row - 3 Cards | 2.1 | #3492 

### Sub-Tasks
- [x] Create individual tickets in digital platform repo for each Drupal tasks and components in R2.1
- [x] Review tickets with design/IA team for alignment [PM to schedule meeting]
- [x] Review tickets with dev team for alignment [PM to schedule meeting]
- [x] Once ticket is complete, please include a check list on this ticket for items to include in Drupal dev tickets for future ticket creation (ie always include X type of requirements)
    - Behavior description
    - InVision links
    - Acceptance criteria

**Comment by sarinapadilla** [comment]
R2.1 tickets have been created, so closing this ticket.
