### ISSUE TITLE
User Story: Build NCIDS 2 Guide Card Row

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3489]
## As a content editor, I want to** be able to be able to promote two collections of related links using the NCIDS Guide Card with Image and Description, so that users can easily find and navigate through important groups of related content.

*To be completed separately:*
- [ ] Finalize Acceptance Criteria for Analytics
- [ ] Create Analytics functionalities

**Acceptance Criteria for Analytics**
- Component: guide card
- Variant: image and description
  - Other variants:
    - no image
    - background image
- Theme: light 
- Type of link: internal, external, media
- Card Title (description if no title)
- Button text
- index of button in list of buttons
- number of buttons
- index of card within row
- number of cards in row
- index of component on page
- number of row components on page
- location ("body" maybe)
- current page - the EDDL extension in launch captures and passes this value for all click events

**Other**
- Heading should be an h2
---

### Acceptance Criteria

```gherkin
Scenario: Content editor is able to add a "NCIDS 2 Guide Card Row" to a Home and Landing page
Given the user is logged in as an editor
  And the user edits a Home and Landing content item
  And the user expands the dropdown to add a paragraph to Contents
Then the dropdown displays the "Add NCIDS 2 Guide Card Row" option
When the user selects the "Add NCIDS 2 Guide Card Row" option
Then the fields for a "NCIDS 2 Guide Card Row" paragraph appear
  And the "Guide Cards" field appears
  And the field is required
  And it is a paragraph
  And it has the option "Add NCIDS Guide Card with Image and Description"
  And it shows that it is empty by displaying text that reads "No Guide Cards added yet."
```

### Resources
**Component variant design:** [NCIDS #614](https://github.com/NCIOCPL/ncids/issues/614)

---

### Prerequisites
- #3551
- #3519 

### Tasks
- [ ] #3743 
    - [ ] Create NCIDS Guide Card with Image and Description Image Style
- [ ] Create NCIDS 2 Guide Card Row

### Technical Notes
Content Modeling:
- [NCIDS 2 Guide Card Row](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Type-NCIDS-2-Guide-Card-Row)
