### ISSUE TITLE
[META] NCIDS Hero

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3493]
Build hero component variations based on design specs/requirements.

R2.1:
- [ ] B. #3488 
- [ ]  E. #3486 
- [ ]  G. #3487 

R2.2:
- [ ] D. Hero Image w/o Button, Light Text Box

R2.3:
- [ ] F. Hero Image w/o Button, Light Text Box & CTA Strip

R2.4:
- [ ]  A. Hero Image w/Button & Dark Text Box
- [ ]  C. Hero Image w/o Button, Dark Text Box

**Comment by sarinapadilla** [comment]
Closing this ticket as all of the variations of the hero component have been implemented!
