### ISSUE TITLE
[META] NCIDS Promo Block

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3495]
Build promo block component variations based on design specs/requirements documented in each variant's ticket.

#### R2.1:
- [ ] B. Promo Block #3490
  - [ ] NCIDS Promo Block Internal #3632 
  - [ ] NCIDS Promo Block External #3633 
- [ ] F. Promo Block - No image - Dark Text Box (Included in the above User Stories)

#### R2.2:
- [ ] A. Alternating Promo Block - Light Text Box
- [ ] E. Promo Block - No image - Light Text Box

#### R2.3:
- [ ] D. Full-width Promo Block - Dark Text Box

#### R2.4:
- [ ] C. Full-width Promo Block - Light Text Box

**Comment by sarinapadilla** [comment]
Internal decision was made to not implement the full-width promo block as it is basically just a hero.
