### ISSUE TITLE
[META] NCIDS Feature Card

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3496]
Build feature card component variations based on design specs/requirements documented in each variant's ticket.

#### R2.1:
- [x] B. #3492 

#### R2.3:
- [ ] C.  Multiple Link Feature Card Row (dynamic) - 3 Cards
- [ ] D. Thumbnail Card - Optional Description 

#### R2.4:
- [ ] A. Feature Cards -  2 Cards

**Comment by sarinapadilla** [comment]
Closing this, as we have completed building this component for Home and Landing pages.
