### ISSUE TITLE
Enabler: Update PHP to 8.1

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/cgov-digital-platform#3532]
# Update PHP to 8.1

>NOTE: This is no longer blocked by New Relic/PHP 8.1 incompatibilities.

Drupal 10 will require PHP 8.1. Acquia now supports PHP 8.1. We need to upgrade the stack to support PHP 8.1, probably before Drupal 9.5.

> **_NOTE:_** This should probably deployed around the time that Acquia starts defaulting ODEs to 8.1.

### Tasks
- [ ] Update Docker stack
   * This includes figuring out which PHP module .ini files have to be changed out. (e.g. xdebug.ini changed a bunch from 7.2->7.3)
- [ ] Update acquia-pipelines.yaml
- [ ] Change ACE and ACSF web server settings through the UI.
- [ ] Anything else missed from above...

### Previous upgrade tickets
* #3105
* #2523
* #3266

**Comment by bryanpizzillo** [comment]
## Investigation Notes
Oy vey, this got messy quick.

* The `classy` theme will no longer be supported in D10, so docroot/module tests got changed to use stable9.
* `strlen` and `array_search` got pickier about what gets passed in.
* `$modules` needs to be protected instead of public in most of our Functional tests. 
* `drupal/redirect` needed to be bumped to 1.9 because it did not support PHP 8.1
* Either `drupal/purge` or `drupal/acquia_purge` had issues at runtime. I think it was purge loading the acquia_purge plugin.
   * I decided to update both since it was needed, and while we are testing purge, we should also bump Akamai
   * Akamai has a dependency on `akamai_open/edgegrid-client`, and the edge grid client has a dependency on `guzzlehttp/guzzle`. In a roundabout way, and I mean very roundabout, acquia/blt-behat depends on an older version of `guzzle.` 
   * Updated `acquia/blt-behat` which updated:
   ```
    - Removing behat/mink-extension (2.3.1)
    - Removing bex/behat-extension-driver-locator (2.0.1)
    - Removing bex/behat-screenshot (2.1.0)
    - Upgrading acquia/blt-behat (v1.3.0 => v1.4.0)
    - Upgrading behat/behat (v3.12.0 => v3.13.0)
    - Upgrading friends-of-behat/mink-extension (2.3.1 => v2.7.2)
    - Upgrading symfony/polyfill-intl-grapheme (v1.27.0 => v1.28.0)
    - Upgrading symfony/polyfill-php72 (v1.27.0 => v1.28.0)
    - Upgrading symfony/polyfill-php73 (v1.27.0 => v1.28.0)
    - Upgrading symfony/polyfill-php81 (v1.27.0 => v1.28.0)
    - Upgrading symfony/string (v6.0.19 => v6.3.2)
```

**Comment by alinai** [comment]
@bryanpizzillo . @santwuma . @kate-mashkina , The Automated Regression tests for Front End and CMS passed on test-ac. The SideNavMobile Test that failed while running from the workflow, passed when we ran it locally. Created and verified Article and Mini Landing page (to verify promo image) on test-ac. Looks good. cc: @SupriyaSaxena0605

**Comment by SupriyaSaxena0605** [comment]
@bryanpizzillo @santwuma @kate-mashkina Analyzed the Visual regression results on test-ac. No issues to report. cc: @alinai
