### ISSUE TITLE
Retire Home & Landing Page Styles

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/cgov-digital-platform#3601]
### Description

- Description: Need to retire the 'Standard', 'Special Report', and 'DCEG Connect' Styles available on the Home/Landing Page content type (see screenshot of aspect being referenced). This will follow R2 once all home and landing pages use the newly established style drop downs and corresponding components.
- History: It was determined the week of 10/10/22 with the federal team that this ticket should be added to the backlog to account for the future need of retiring the aforementioned styles.
- Parent Issue: N/A

### Sub-Tasks
- [x] Conduct a discussion with the client ahead of moving forward with any action to ensure we are on the same page
- [x] Create inventory to ensure there are no home/landing pages currently using either the 'Standard', 'Special Report', or 'DCEG Connect' style selections
- [x] Update/Retire all existing Home & Landing Pages using 'Standard', 'Special Report', or 'DCEG Connect' to either use an NCIDS template or retire the page. See tracking report [here](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B3CB5CFF4-B03D-4B4B-91B7-8B94F1629E46%7D&file=landingpageStyle.xlsx&action=default&mobileredirect=true)
- [ ] Remove all existing YAML that use `field_page_style` of "Standard", "Special Report", and "DCEG Connect" from the test site, except main navigation which needs to be replaced with Page Left Intentionally Blank 
- [ ] Once all pages have been retired/converted, remove the 'Standard', 'Special Report', and 'DCEG Connect' options from the `field_page_style` field on the Home & Landing content type
- [ ] Change the default selection of the `field_page_type` for Home and Landing Pages to be "NCIDS with Title"

### Requirements
| ID No. | Requirement Definition | Notes |
| ------- | ----------------------- | ------- |
| 1.0.0 | The allowed options in the Field `field_page_style` shall be "NCIDS with Title" and "NCIDS without Title". | |
| 1.1.0 | The default option for the Field `field_page_style` shall be "NCIDS with Title". | |
| 1.2.0 | The order of available options for the dropdown of the Field `field_page_style` shall be 1. "NCIDS with Title" 2. NCIDS without Title." | |
| 1.2.0 | The option "Standard" for the Field `field_page_style` shall be removed. | |
| 1.3.0 | The option "Special Report" for the Field `field_page_style` shall be removed. | |
| 1.4.0 | The option "DCEG Connect" for the Field `field_page_style` shall be removed. | |

### Acceptance Criteria
**CMS**
1. When a user adds or edits a Home & Landing Page and navigates to the Field `field_page_style`, and clicks the dropdown, they will not see an option for "Standard".
2. When a user adds or edits a Home & Landing Page and navigates to the Field `field_page_style`, and clicks the dropdown, they will not see an option for "Special Report".
3. When a user adds or edits a Home & Landing Page and navigates to the Field `field_page_style`, and clicks the dropdown, they will not see an option for "DCEG Connect".
4. When a user adds a Home & Landing page and navigates to the Field `field_page_style`, the default option will be set to "NCIDS with Title".
5. When a user adds or edits a Home & Landing Page and navigates to the Field `field_page_style`, and clicks the dropdown, they will see the options "NCIDS with Title" and "NCIDS without Title" in this order.

**Front-End**
1. This will have no impact to the front-end experience of the site since all previous Home & Landing Pages uses the styles that will be removed by this ticket have been converted or retired.

**Analytics**
1. There will be no change to how analytics function, as they will still receive the data as to what Style is being used on Home & Landing Pages.

### Testing Notes
- This will break all existing YAML on the test environments, but they should have all been removed by the developer for testing.

### Screen shots
![image](https://user-images.githubusercontent.com/102998716/195185124-bfd019b4-a214-4c5d-a701-4ae5a526b3f9.png)

### YAML Updates
Please update the YAML Content based on the information supplied in the following tables.

**Pages to Delete**
| Trailing URL | Action |
| ------------ | ------ |
| /cgdpl | Delete page |
| /espanol/cgdpl | Delete page |
| /grants-training/cgdpl | Delete page |
| /types/cgdpl | Delete page |
| /espanol/tipos/cgdpl | Delete page |
| /espanol/test-es/borderless-card | Delete page |
| /test/borderless-card | Delete page |
| /espanol/noticias/cgdpl | Delete page |
| /news-events/cgdpl | Delete page |
| /espanol/subvenciones-capacitacion/cgdpl | Delete page |
| /special-report | Delete page |
| /espanol/special-report | Delete page |
| /dceg-connect | Delete page |
| /sbir | Delete page |

**Pages to Update to NCIDS**
| Trailing URL | Action |
| ------------ | ------ |
| /research | Update the page to Left Intentionally Blank |
| /espanol/cancer | Update the page to Left Intentionally Blank |
| /about-cancer | Update the page to Left Intentionally Blank |
| /test/cards/landing-containers | <ul><li>Remove the first Content Block</li><li>Replace the Primary Feature Card Row with an NCIDS Feature Card Row. Add the link to the Unpublished Page to an NCIDS Internal Feature Card in the NCIDS Feature Card Row. Make the title of the Feature Card Row "Feature Card Row, Unpublished"</li><li>Remove the second content block</li><li>Replace the second Primary Feature Card Row with an NCIDS Feature Card Row. Title the Row "Primary Row, No Item". Place an empty NCIDS Internal Feature Card in the Row.</li><li>Remove the 3rd Content block.</li>Remove the first Secondary Feature Card Row.</li><li>Remove the 4th Content Block.</li><li>Remove the second Secondary Feature Card Row.</li><li>Remove the 5th content block.</li><li>Replace the Guide Card Row with an NCIDS 3 Guide Card Row with no cards in it. Label the row Empty Guide Row.</li><li>Remove the 6th content block.</li><li>Remove the Multimedia Row.</li>Remove the 7th content block.</li><li>Remove the second Multimedia Row.</li> |
