### ISSUE TITLE
[META] Update cgov_image with new override fields needed for NCIDS Home & Landing Page components

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3609]
## As a content owner, I want the ability to add NCIDS Home & Landing Page specific images to cgov_image, so that images can be added that follow the art direction of the new components.

We need to update the cgov_image media type with new override fields for the NCIDS Home & Landing Page components.
* NCIDS Promo Art 1:1
* NCIDS Promo Art Thumb 1:1
* NCIDS Promo Art 16:9
* NCIDS Promo Art 4:3

### Requirements

- [x] - 3609.1 The cgov_image media type shall allow the user to add an image to the optional NCIDS Promo Art 1:1 Override field. See #3758 for the subcomponent requirements.
- [x] - 3609.2 The cgov_image media type shall allow the user to add an image to the optional NCIDS Promo Art Thumbnail 1:1 Override field. See #3757 for the subcomponent requirements.
- [x] - 3609.3 The cgov_image media type shall allow the user to add an image to the optional NCIDS Promo Art 16:9 Override field. See #3662 for the subcomponent requirements.
- [x] - 3609.4 The cgov_image media type shall allow the user to add an image to the optional NCIDS Promo Art 4:3 Override field. See #3635 for the subcomponent requirements

    
> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario: Image editor is able to create a cgov_image and add an image to the <NCIDS Promo Art 1:1, NCIDS Promo Art Thumbnail 1:1, NCIDS Promo Art 16:9, NCIDS Promo Art 4:3> field
Given the user is logged in as an image manager
  And the user adds a new cgov_image media item
Then the cgov_image displays the <NCIDS Promo Art 1:1, NCIDS Promo Art Thumbnail 1:1, NCIDS Promo Art 16:9, NCIDS Promo Art 4:3> field
  And the field is optional
  And the field is a file upload type
  And the field shall display the tooltip text as defined in 3609.1.2, 3609.2.2, 3609.3.2, 3609.4.2 respectively
When the user clicks the "Choose File" option
Then the file explorer only allows for the selection of .png, .gif, .jpg, or .jpeg files
When the user successfully uploads a file to the field
Then the Alternative Text field displays
  And the field is optional
  And the field is a text input
  And the field has the tooltip:
    Short description of the image used by screen readers and displayed when the image is not loaded. This is important for accessibility.
  And the user has the option to Remove the uploaded file.
When the user clicks Save
Then the cgov_image media type is successfully added to the system
```

```gherkin
Scenario: Image editor is able to edit a cgov_image and add an image to the <NCIDS Promo Art 1:1, NCIDS Promo Art Thumbnail 1:1, NCIDS Promo Art 16:9, NCIDS Promo Art 4:3> field
Given the user is logged in as an image manager
  And the user edits an existing cgov_image media item
Then the cgov_image displays the <NCIDS Promo Art 1:1, NCIDS Promo Art Thumbnail 1:1, NCIDS Promo Art 16:9, NCIDS Promo Art 4:3> field
  And the field is optional
  And the field is a file upload type
  And the field shall display the tooltip text as defined in 3609.1.2, 3609.2.2, 3609.3.2, 3609.4.2 respectively
When the user clicks the "Choose File" option
Then the file explorer only allows for the selection of .png, .gif, .jpg, or .jpeg files
When the user successfully uploads a file to the field
Then the Alternative Text field displays
  And the field is optional
  And the field is a text input
  And the field has the tooltip:
    Short description of the image used by screen readers and displayed when the image is not loaded. This is important for accessibility.
  And the user has the option to Remove the uploaded file.
When the user clicks Save
Then the cgov_image media type is successfully added to the system
```

### Resources:
* NCIDS: https://github.com/NCIOCPL/ncids/issues/586
* Mural: [Image requirements](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1663698618353/28c0e3412e473a41817044386ee09b90823aa6eb?sender=uc0870c1f8489401535da0005)

**Children:** #3635  #3662 

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by bennettcc** [comment]
Closing this meta - all component tickets have been completed
