### ISSUE TITLE
User Story: Build NCIDS Feature Card Internal

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/cgov-digital-platform#3611]
## User Story:
**As a** content editor, 
**I want to** be able to add an NCIDS Feature Card Internal to my Home and Landing page,
**so that I** can use the component to feature internal content.

**Parent Issue:** #3492 

> **ESTIMATE** TBD

### Image Sizes
Breakpoint | 1x Magnification | 1.5x Magnification | 2x Magnification
--- | --- | --- | --- 
Widescreen | 350px x 262.5px | 525px x 393.75px | 700px x 525px
Desktop |  298px x 223.5px | 525px x 393.75px |  700px x 525px
Tablet Large | 704px x 396px | 1056px x 594px | 1408px x 792px
Tablet | 504px x 283.5px | 756px x 425.25px | 1008px x 567px
Mobile Large | N/A | N/A | N/A
Mobile | N/A | N/A | N/A
    
### Acceptance Criteria

*Drupal Display:*
``` gherkin
Scenario: User can see fields for an NCIDS Feature Card Internal
  Given user is logged in to the CMS
    And user edits a "Home and Landing" content item
  When user adds an "NCIDS 3 Feature Card Row" to the "Contents" field
    And user adds an "NCIDS Feature Card Internal" to the "Feature Cards" field
  Then user will see the fields for an "NCIDS Feature Card Internal"
    And first field will be "Featured Item"
    And "Featured Item" field will be required
    And "Featured Item" field will be an entity reference to a node
    And next field will be "Override Card Title"
    And "Override Card Title" field will be optional
    And "Override Card Title" field will be a text input
    And next field will be "Override Card Description"
    And "Override Card Description" field will be optional
    And "Override Card Description" field will be a text input
    And next field will be "Override Promotional Image"
    And "Override Promotional Image" field will be optional
    And "Override Promotional Image" field will be an image select
```

*Drupal Functionality:*
``` gherkin
Scenario: User can add an NCIDS Feature Card Internal to an NCIDS 3 Feature Card Row
  Given user is logged into the CMS
  When user creates a new "Home and Landing" content item
  Then the editing page for a "Home and Landing" content item displays
    And user fills out the following fields
      | fieldLabel                  | value                                                          | field_name                     |
      | Home and Landing Page Style | NCIDS with Title                                               | field_page_style               |
      | Pretty URL                  | home-and-landing-page                                          | field_pretty_url               |
      | Page Title                  | Automated Test NCIDS Feature Card Internal                     | title                          |
      | Browser Title               | Automated Test NCIDS Feature Card Internal - Browser Title     | field_browser_title            |
      | Card Title                  | Automated Test NCIDS Feature Card Internal - Card Title        | field_card_title               |
      | Meta Description            | Automated Test NCIDS Feature Card Internal Meta Description    | field_page_description         |
      | Feature Card Description.   | Automated Test NCIDS Feature Card Internal - Feature Card Desc | field_feature_card_description |
  When user selects "Add NCIDS 3 Feature Card Row" from "Contents" dropdown
  Then "NCIDS 3 Feature Card Row" section appears
    And user fills out the following fields
      | fieldLabel | value                    | field_name              |
      | Heading    | NCIDS 3 Feature Card Row | field_container_heading |
  When user selects "Add NCIDS Feature Card Internal" from "Feature Cards" dropdown
  Then "NCIDS Feature Card Internal" section appears
    And user clicks on "Featured Item" link in the "NCIDS Feature Card Internal" area
    And user clicks on "Select content" button item
    And user selects "Article to test Related Resources" item from the list
    And user clicks on "Select content" button to select item
    And "Article to test Related Resources" had been selected
    And user fills out the following fields
      | fieldLabel                | value                                                 | field_name                      |
      | Override Card Title       | Override Card Title NCIDS Feature Card Internal       | field_override_card_title       |
      | Override Card Description | Override Card Description NCIDS Feature Card Internal | field_override_card_description |
    When user saves the content page
    Then user can see NCIDS Feature Card Internal on the page
      And card displays an image
      And card displays the title "Override Card Title NCIDS Feature Card Internal"
      And card displays the description "Override Card Description NCIDS Feature Card Internal"
```

*Front-End Field Display Rules:*
Card Title
``` gherkin
Scenario: The title set on an NCIDS Feature Card Internal is displayed
  Given user is logged in to the CMS
    And user edits a "Home and Landing" content item
    And the "Home and Landing" content item has an "NCIDS Feature Card Internal"
  When user sets the "Override Card Title" field
  Then the front-end will display the "Override Card Title" on the card
  When the user does not set the "Override Card Title"
    And the Featured Item has a "Feature Card Title"
  Then the front-end will display the "Feature Card Title" on the card
  When the user does not set the "Override Card Title"
    And the Featured Item does not have a "Feature Card Title"
  Then the front-end will display the "Browser Title" on the card
```

Card Description
``` gherkin
Scenario: The title set on an NCIDS Feature Card Internal is displayed
  Given user is logged in to the CMS
    And user edits a "Home and Landing" content item
    And "Home and Landing" content item has an "NCIDS Feature Card Internal"
  When user sets the "Override Card Description" field
  Then front-end will display the "Override Card Description" on the card
  When user does not set the "Override Card Description"
    And Featured Item has a "Feature Card Description"
  Then front-end will display the Featured Item's "Feature Card Description" on the card
  When user does not set the "Override Card Description"
    And Featured Item does not have a "Feature Card Description"
  Then front-end will display the Featured Item's "Feature Card Description" on the card
  When user does not set the "Override Card Description"
    And Featured Item does not have a "Feature Card Description"
    And Featured Item has a "List Description"
  Then front-end will display the Featured Item's "List Description" on the card
  When user does not set the "Override Card Description"
    And Featured Item does not have a "Feature Card Description"
    And Featured Item does not have a "List Description"
  Then front-end will not display a description on the card
```

Card Image
``` gherkin
Scenario: The image set on an NCIDS Feature Card Internal is displayed
  Given user is logged in to the CMS
    And user edits a "Home and Landing" content item
    And "Home and Landing" content item has an "NCIDS Feature Card Internal"
  When user has set the "Override Promotional Image"
  Then the front end will display the "Override Promotional Image" on the card
  When user has not set the "Override Promotional Image"
    And Featured Item has a "Promotional Image"
  Then the front end will display the Featured Item's "Promotional Image" on the card
  When user has not set the "Override Promotional Image"
    And Featured Item does not have a "Promotional Image"
    And the Featured Item has a "Lead Image"
  Then the front end will display the Featured Item's "Lead Image" on the card
  When user has not set the "Override Promotional Image"
    And Featured Item does not have a "Promotional Image"
    And the Featured Item does not have a "Lead Image"
  Then the placeholder image will be displayed on the card
```

``` gherkin
Scenario: The image set on an NCIDS Feature Card Internal is displayed at different aspect ratios at different breakpoints
  Given user is logged in to the CMS
    And user is viewing the home page
    And home page has an NCIDS Feature Card Internal with an image
  When the browser width is at least 880x (Widescreen, Desktop, and Tablet Large)
  Then the displayed image will have an aspect ratio of 4:3
  When the browser width is at least 640px and less than 880px (Tablet)
  Then the displayed image will have an aspect ratio of 16:9
  When the browser width is less than 640px (Mobile Large and Mobile)
  Then no image will be displayed
```

### Resources:
* Component variant design: [NCIDS #605](https://github.com/NCIOCPL/ncids/issues/605)
* **Parent**: #3492 
* **Siblings**: #3612, #3637, #3613

---

### Prerequisites
- #3551
- #3519

### Tasks
- [x] [Create NCIDS Feature Card Internal paragraph](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Type-NCIDS-Feature-Card#ncids-feature-card-internal)
- [x] #3690
- [x] #3691
- [x] Create basic twig templates
- [x] Evaluate component using acceptance criteria in the Parent Issue, #3492

### Technical Notes
**Content Modeling:**
- [NCIDS Feature Card Internal](https://github.com/NCIOCPL/cgov-digital-platform/wiki/paragraph-type-ncids-feature-card#ncids-feature-card-internal)
- [NCIDS 3 Feature Card Row](https://github.com/NCIOCPL/cgov-digital-platform/wiki/paragraph-type-ncids-3-feature-card-row)

**Drupal image display flow:**

![image](https://user-images.githubusercontent.com/115043734/208689365-abdfc6c6-1006-4f81-86bf-6f7431740e86.png)
