### ISSUE TITLE
Task: Build NCIDS Link Button Internal

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3744]
## User Story:
**As a** content editor, 
**I want to** have the Development Solution for Drupal, 
**so that I** can create NCIDS Call to Action component on an NCI website

**Parent Issue:** #3490 

> **ESTIMATE** TBD

### Acceptance Criteria
**Drupal Field display:**
``` gherkin
Scenario: A content editor can add an NCIDS Internal Call to Action to an NCIDS Alternating Promo Block
Given a content editor is in the Drupal UI
  And the Development Solution for the component is completed in the DS
  And the Development Solution for the component has been implemented in Drupal
When the user adds an NCIDS Internal Call to Action to the NCIDS Alternating Promo Block on the home/landing page content type
Then the user will see the fields for an NCIDS Internal Call to Action
  And the first field will be for the "Featured Item"
  And the Featured Item field will be required
  And the Featured Item field will be an entity reference to a node
  And the second field will be for the "Call to Action Text"
  And the Override Card Title field will be required
  And the Override Card Title field will be a text input
  And the third field will be for the "Call to Action Alt Text"
  And the Override Card Description field will be optional
  And the Override Card Description field will be a text input
```

**Display Rules**
Card Title
``` gherkin
Scenario: The Call to Action Text set on an NCIDS Internal Call to Action is displayed
Given a content editor has set the required field entries in Drupal for an NCIDS Internal Call to Action
  And the content editor has saved the component in Drupal
  And the Development Solution for the component is completed in the DS
  And the Development Solution for the component has been implemented in Drupal
  And the user is viewing the NCIDS Internal Call to Action Card
When the content editor has set the Call to Action Text
Then the Call to Action Text will be displayed on the NCIDS Internal Call to Action
When the content editor has set the Call to Action Alt Text
Then the Call to Action Alt Text will be set as the alt text attribute on the NCIDS Internal Call to Action
When the content editor has not set the Call to Action Alt Text
Then the no alt text will be set as the alt text attribute on the NCIDS Internal Call to Action
```

### Resources:
* Component variant design: [NCIDS #548](https://github.com/NCIOCPL/ncids/issues/548)

---

### Prerequisites
- #3551
- #3519

### Tasks
- [ ] [Create NCIDS Internal Call to Action paragraph](https://github.com/NCIOCPL/cgov-digital-platform/wiki/paragraph-type-ncids-call-to-action#internal-call-to-action)
- [ ] Create basic twig templates
- [ ] Evaluate component using acceptance criteria in the Parent Issue, #3490

### Links
**Parent**: #3490
**Siblings**: #3745 

### Technical Notes
**Content Modeling:**
- [NCIDS Internal Link Button](https://github.com/NCIOCPL/cgov-digital-platform/wiki/paragraph-type-ncids-link-button#ncids-link-button-internal)
