### ISSUE TITLE
Task: Build NCIDS Link Button External

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3745]
This task defines the subsystem requirements to build the NCIDS External Call to Action which is linked to:

**Parent Issue:** #3487 

### Sub-Tasks
- [ ] Create [NCIDS External Link Button component](https://github.com/NCIOCPL/cgov-digital-platform/wiki/paragraph-type-ncids-link-button#ncids-link-button-external)
- [ ] Create basic twig templates
- [ ] Confirm component using acceptance criteria listed in the Parent Story #3487

### Resources
Component variant design: [NCIDS #548](https://github.com/NCIOCPL/ncids/issues/548)

### Links
Parent: #3487 
Siblings: #3744 

### Technical Notes
Content Modeling:
[NCIDS External Link Button](https://github.com/NCIOCPL/cgov-digital-platform/wiki/paragraph-type-ncids-link-button#ncids-link-button-external)
