### ISSUE TITLE
Refactor high charts code to load JSON data from content - Part 2

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/cgov-digital-platform#3761]
> **Parent Issue:** #3008 

### Issue description
The high charts functionality for the Fact Book uses data which is encoded directly into the JavaScript files. Although this was expedient when the charts went live several years ago, it means that all updates and corrections to the data require developer time and a software release.

Link to High chart - https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/grant-contract-awards

> **ESTIMATE**
> - First: 2
> - Subsequent: 1

Impacted files include (this list may be incomplete):
* [aids-funding.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/aids-funding.js)
* [bypass-appropriations.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/bypass-appropriations.js)
* [grants-contracts.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/grants-contracts.js)
* [html-amount.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/html-amount.js)
* [html-bar.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/html-bar.js)
* [html-extramural.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/html-extramural.js)
* [html-nrsa.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/html-nrsa.js)
* [kawards-pie.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/kawards-pie.js)
* [management-fund.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/management-fund.js)
* [moonshot-obligations.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/moonshot-obligations.js)
* [number-rpg-awards.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/number-rpg-awards.js)
* [obligations-mechanism.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/obligations-mechanism.js)
* [program-structure.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/program-structure.js)
* [rms-funding.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/rms-funding.js)
* [rpg-cost-per-award.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/rpg-cost-per-award.js)
* [rpg-funding.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/rpg-funding.js)

Next steps:
1. Review SOP - https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLPlatformSupport/Shared%20Documents/Boundary%20-%20CGDP/Standard%20Operating%20Procedures/deploy-acsf-site-to-local.md?csf=1&web=1&e=jhXwx8
2. Review affected files and update as needed
3. Define an approach 
4. Implement approach

### What's the expected change?
- The data should be loaded from JSON files stored as content in the CMS.

### What's the current functionality?
- The data is hard-coded in .JS files which are part of the front end code.

### What are the updated requirements?
- 3008 . JSON files uploaded to the CMS will provide the data for an individual HighChart .JS file used in the Factbook.
    - 3008.1. The CDEConfig object shall have a property that contains for the base URL for data files used by Factbook charts.
        - 3008.1.1. The CDEConfig object shall have a "ChartData" property.
        - 3008.1.2. The "ChartData" property shall have a "Factbook" property.
        - 3008.1.3. The "Factbook" property shall have a "BaseUrl" property.
            - 3008.1.3.1. The "BaseUrl" property will be a string.
            - 3008.1.3.1. The "BaseUrl" property value will be the base URL for all files uploaded to the CMS containing chart data.
        - 3008.1.4. The "Factbook" property shall have a "DataType" property.
            - 3008.1.4.1. The "DataType" property will be a string, and allow the value "json".
    - 3008.2. The individual HighChart .JS file shall hardcode the file name associated with the CMS file containing JSON data for the chart.
    - 3008.3. The individual HighChart .JS file shall use the "BaseUrl" value and the hardcoded file name to determine the path for the CMS file containing JSON data for the chart.
    - 3008.4. The individual HighChart.JS file shall read in the JSON data in the file and create the chart using that data.

### What's the updated acceptance criteria?
```gherkin
Scenario: CDEConfig object is updated with ChartData parameter

Given a user is viewing a page with a HighChart
When the user views the page source
Then the CDEConfig JSON object literal has a property "ChartData"
  And the value for the "ChartData" property is an object with the property "Factbook"
  And the value for the "Factbook" property is an object with properties "BaseUrl" and "DataType"
  And the "BaseUrl" property is a string with the base path where the HighChart data files live (update this with the base URL)
  And the "DataType" property is an object with a string, "json"
```

```gherkin
Scenario: Individual chart JS files use hardcoded JSON file names to load data

Given a developer creates a new HighChart .JS file
  And the .JS file has a hardcoded value with the filename containing the JSON data
  And the user uploads a JSON file containing the data to the CMS
When the user views the page containing the chart
Then the chart will display the data in the JSON file
```

#### Automated Testing

- Automated regression testing

#### Manual Testing

1. The charts in the pages listed have to be compared to their corresponding charts in production to ensure charts remain the same. In particular, things to watch out for within the charts, title, subtitle, chart data, tooltips, and chart drill-down should all remain the same.
    * [https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/aids-funding](https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/aids-funding)
    * [https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/bypass-appropriations](https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/bypass-appropriations)
    * [https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/grant-contract-awards](https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/grant-contract-awards)
    * [https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/comparison](https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/comparison)
    * [https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/k-awards](https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/k-awards)
    * [https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/data/extramural](https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/data/extramural)
    * [https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/nrsa](https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/nrsa)
    * [https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/data/management-fund](https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/data/management-fund)
    * [https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/cancer-moonshot/moonshot-obligations](https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/cancer-moonshot/moonshot-obligations)
    * [https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/rpg](https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/rpg)
    * [https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/data/obligations](https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/data/obligations)
    * [https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/data/program-structure](https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/data/program-structure)
    * https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/extramural-intramural-rms
    * https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/rpg

2. Update chart data through CMS in order to ensure chart is rendered with updated content. Chart data is updated by loading json formatted data file particular to each chart, which matches the name of the chart.   To update chart data for “AIDS Funding History” located at “https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/aids-funding”, go to “https://ncigovcdode537.prod.acquia-sites.com/admin/content/media”.  
    1. Enter “aids-funding” in the “Media name” field and click on the “Filter” button 
    2. Click on the Edit button in the OPERATIONS field for the aids-funding filtered result 
    3. For the required File field, click on the Remove button to remove the chart data file 
    4. Click on the “Choose File” button and select your desired data file to replace the previously removed one. Note the spinning icon, and allow to complete before proceeding to next step 
    5. Once step above is complete, click the Save button at the bottom of the page
    6. Filter again for “aids-funding” entry just edited, and click on edit again
    7. At the bottom of the page for the “Change to” field, select ‘Published, and then click Save
    8. In order to let the chart pick up the recent data file you just uploaded, go to https://ncigovcdode537.prod.acquia-sites.com/admin/structure/block/block-content, enter "aids-funding" into the "Block description" field and click on the "Apply" button to filter
    9. For "aids-funding" under the "Operations" column, click on the "Edit" button
    10. In the "Body" field, look for the HTML div block that contains the attribute "data-chart-revision", and update it's value to match existing format "YYYYMMDD_revision-number" (e.g 20230314_1, 20230314_2, ...), and click on the "Save" button
    11. Visit or refresh page containing chart data just updated to see your changes (https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/aids-funding). 
    
    #### List of chart data files and their corresponding pages  :
    
    1. aids-funding - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/aids-funding
    2. bypass-appropriations - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/bypass-appropriations
    3. grants-contracts - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/grant-contract-awards **(CURRENTLY NOT DISPLAYED ON PAGE)** #3446 Created to resolve this
    4. html-amount - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/comparison
    5. html-bar - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/k-awards
    6. html-extramural - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/data/extramural
    7. html-nrsa - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/nrsa
    8. kawards-pie - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/k-awards
    12. management-funds - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/data/management-fund
    13. moonshot-obligations - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/cancer-moonshot/moonshot-obligations
    14. number-rpg-awards - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/rpg
    15. obligations-mechanism - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/data/obligations
    16. program-structure - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/data/program-structure
    17. rms-funding - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/historical-trends/extramural-intramural-rms
    18. rpg-cost-per-award - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/rpg **(CURRENTLY NOT DISPLAYED ON PAGE)**
    19. rpg-funding - https://ncigovcdode537.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/rpg
      
    
    
  > **NOTE:** 
  > 16 charts in total for FactBook, but only 14 of these charts are currently being displayed in production.

  Chart Data Files (Reflects Data in Production): [Found in Boundary CGDP > Content Maintenance > factbook > factbook-chart-data-files](https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLPlatformSupport/Shared%20Documents/Boundary%20-%20CGDP/Content%20Maintenance/factbook/[factbook-chart-data-files](https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLPlatformSupport/Shared%20Documents/Boundary%20-%20CGDP/Content%20Maintenance/factbook/factbook-chart-data-files?csf=1&web=1&e=VxbR48)?csf=1&web=1&e=VxbR48)

  Chart Data Test Files (Reflects Data for Testing): [test-files.zip](https://github.com/NCIOCPL/cgov-digital-platform/files/10945310/test-files.zip)

3. Malformed JSON chart data files can be uploaded to test, and ensure it doesn't break the whole site or page. Result of this test should be that the chart just doesn't get displayed due to the malformed data, and everything else should work as usual.
    Malformed data test file for chart "moonshot-obligations. Rename to `factbook-moonshot-obligations-malformed.json` before uploading.
    [factbook-moonshot-obligations-malformed.json.txt](https://github.com/NCIOCPL/cgov-digital-platform/files/10885360/factbook-moonshot-obligations-malformed.json.txt)

4. Remove the `chartData` property from `CDEConfig` object in frontend globals that contains configuration for chart data to ensure site doesn't break when configuration object for chart data does not exist. This should only result in charts not being displayed on chart pages.
  https://ncigovcdode537.prod.acquia-sites.com/cgov_core/form/frontend_globals?uid=1&key=value

NOTE: Previous tasks for this ticket completed in #3008 

### Tasks
- [x] Addressing issue with #3733 (SP 1)
- [x] Retest all charts
- [x] Move json data files into CMS (SP 1)
- [x] Update CDEConfig (SP 1)
- [x] Load json data from CMS into chart (SP 5)

**Comment by laurelthrash** [comment]
Re-established during Factbook mid-sprint check-in on 02/13 that this ticket is to make it so that a code deployment is not needed to update high charts. This ticket does not establish that the process is such that product team members or clients can make the update.

**Comment by laurelthrash** [comment]
@blairlearn to conduct code review
