### ISSUE TITLE
Replace Page Manager with Layout Builder for Blogs

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3807]
### Issue description
> **ESTIMATE** TBD

Layout Builder is a core module used for complicated page layouts and was still being developed at the time we were building the digital platform. When we got to blogs in our development cycle we had to fall back to using Page Manager and Panels to handle the complicated layouts. Page Manager and Panels were two VERY popular Drupal 7 modules that had been ported to Drupal 8. The goal for Layout Builder was to have a core feature that handles the basic use cases of Page Manager and Panels. Now that Layout Builder has been out for a while, Page Manager is getting long in the tooth. The biggest issue with Page Manager is that it is not integrated with core - such as the problem with the `latest` route in #3804. Additionally, it may be the cause of the issue in #3806. Page Manager was never to be a long term solution for handling the complicated layout for Blog Series and Blog Posts.

This ticket is to replace Page Manager & Panels with Layout builder for handling Blog Series and Blog Posts.

## Subtasks
- [ ] Remove Page Manager and Panels from any dependencies. (But leave in composer as the code needs to be there so it will not break.)
   1. Remove the configs from the repo:
       * cgov_blog/config/install/page_manager.page_variant.node_view-panels_variant-blog-post.yml 
       * cgov_blog/config/install/page_manager.page_variant.node_view-panels_variant-blog-series.yml
   2. Update cgov_blog.info.yml and cgov_site.info.yml to remove dependencies on `panels` and `page_manager`.
   3. Add `drupal:layout_builder` as a dependency to cgov_blog.info.yml.
   4. Create cgov_blog update hook to:
       1. Uninstall the `panels` and `page_manager` modules.
       2. Delete the configs:
           * cgov_blog/config/install/page_manager.page_variant.node_view-panels_variant-blog-post.yml 
           * cgov_blog/config/install/page_manager.page_variant.node_view-panels_variant-blog-series.yml
       3. Enable the `layout_builder` module.
- [ ] Setup a new view mode for `node` entities for rendering the primary content of a Node (e.g. the body) in a region of a sublayout. This should go into cgov_core.
   * The view mode details are:
      * **name:**  `lb_primary_content`
      * **label:** "Layout Builder: Primary Content
- [ ] Define all the regions and layouts needed for this conversion.
- [ ] Fix all the blog blocks so they work with Layout Builder. The blocks are pretty brittle and make very strict assumptions about what it being viewed. So you will need a liberal sprinkling of [$this->inPreview](https://www.drupal.org/node/3272267).
- [ ] Update the theme
   * Create a new `node--cgov-blog-post--lb-primary-content.html.twig` template. Copy the contents of `node--cgov-blog-post--full.html.twig` to start. This should basically output the main body content for the page without blocks.
      * The <footer> element should probably get turned into a region. In the layout builder layout we would stack the various components in order.
   * Change the contents of `node--cgov-blog-post--full.html.twig` to be `{{content}}`
   * Modify the `ncids_trans.layouts.yml` file to make 3 new layouts:
      * `cgov_blog_two_col` - this is a layout to replace cgov_blog. It represents 2 columns.  
      * `cgov_blog_post` - this is the layout template to layout the contents of the blog post.
      * `cgov_blog_series`- this is the template to layout the contents of the series.
      * The key thing here is that with layout builder you can nest templates. so `cgov_blog_two_col` will be the wrapper with the right rail and main contents. The `cgov_blog_post` might be the "main contents" and "footer" regions. (two bullets up)
* Configure the full display mode for blogs and blog series to use layout builder. Layout the pages. Poop the configs out.

## Related Links
- [Add visibility control conditions to blocks within Layout Builder](https://www.drupal.org/project/drupal/issues/2916876): This would allow us better control over whether or not blocks should show. We really do not want to output lots of empty HTML if we do not need to.
