### ISSUE TITLE
Update YAML for Test Pages

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3810]
The YAML for several home and landing pages needs to be updated. It comes up often during internal and client testing as a potential issue, when really it is just bad content.

**Parent Issue:** #3785 

### Sub-Tasks
- [ ] Update Spanish homepage
- [ ] Update El cáncer
- [ ] Update Grants & Training

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction
