### ISSUE TITLE
Story: Include Audio Description for Videos

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/cgov-digital-platform#3819]
### Tasks

- [x] Brainstorm possible solutions
    - [ ] Follow up with Bryan for feedback on proposed solutions
- [ ] Select solution to create with client
- [ ] Create AC's for selected solution

### Possible Solutions

**Changes to Current Video Player**
- Allow captions to be able to include links within its text
- Button that allows opens the transcript below the audio/video player (see the current audio player solution on https://www.cancer.gov/news-events/press-releases/2023/nci-launches-persistent-poverty-initiative). Would require code to be built out every time. Increased complexity and work required to meet a11y requirement.
- Add feature that allows for linking to audio-description file
- Only make videos with audio description

**Using a Better, More Accessible Video Player**
- [AblePlayer](https://ableplayer.github.io/ableplayer/). Open source, used on other projects before. Has blessing from Alison Walden's team. Handles YouTube videos. Experience not much different. Supports Transcripts, autoscrolling, highlighting current speech, side-by-side with video. There is a switch to change to the audio-described version of the video. No large change needed due to links being passed from YouTube to AblePlayer. Would need links to the transcript and audio-description. Also handles Vimeo videos, mp4's, and can replace the audio player (would include transcripts of audio content). Need to investigate the fit of the new video and audio player on the pages from a content perspective. Uses jquery (something that is trying to be removed from the site) it is old and adds file size to the website. Impact isolated to pages that have video.
- Other Federally Recommended Players: - MediaFront Module, OSM Player (both work with Drupal) 
- Other option: [Plyr](https://plyr.io/) (no dependencies on jquery, will need further investigation)

### Solution Selection Notes
- 

### Acceptance Criteria
_How site visitor interacts with solution_
```gherkin
Scenario: 
Given
Then
```

_How content editor adds solution to site_
```gherkin
Scenario: 
Given
Then
```

### Additional details / screenshot
- Utilize information from https://digital.gov/2014/06/30/508-accessible-videos-how-to-make-audio-descriptions/

### Related Tickets
* Accessibility - #3820

**Comment by bennettcc** [comment]
Adding to Redesign project - will eventually need to be added to a release 3 project (for work in 2024)

**Comment by andyvanavery31** [comment]
Solution determined that Audio Description and Transcript will be handled in the same solution. Closing this ticket.
