### ISSUE TITLE
Spike Claro

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3847]
### History/what is Claro
- Claro is the default administration theme for Drupal since 9.4 (https://www.drupal.org/docs/core-modules-and-themes/core-themes/claro-theme)
- Our current Drupal Admin theme on the digital platform, SVN, will go away with the implementation of Drupal 10
- We must implement a new Drupal Admin theme prior to Drupal 10 implementation

### Sub-tasks for Spike

- [x] Option # 1 - Determine if Claro can be modified to fit our needs
    - [x] Add to ODE for review/validation
- [x] Option # 2 - Determine if Gin can be modified to fit our needs
    - [ ] See if we can add the Gin toolbar across the top to show on the front-end (from page-view) and back-end in CMS
    - [ ] Add to ODE for review/validation 
- [x] Option # 3 - Determine if SVN (current admin theme) can be modified to fit our needs
    - [ ] Determine if we want to pursue this
    - [ ] If adopted, add to ODE for review/validation 
- [x] Identify dependent module(s) that need to be upgraded (e.g., paragraphs, fonts, Admin toolbar) prior to implementation of Admin theme
    - [x] Determine if new tickets may need to be created

### Next steps
- [x] Internal kick off (7/6) - Bryan, Lindsay, Sarina, Naveen, Laurel (prioritized after R2.1 June deployment) 
- [x] Conduct spike ticket outlined above (1.5 weeks starting week of 7/10) - Naveen
- [x] Add results of spike for Claro and Gin to ODE (x2) to review and validate - Naveen 
- [x] Review results of spike and determine next steps - Bryan, Lindsay, Sarina, Naveen, Laurel, Sandra

### Notes
_07/06/23 Internal Kick-Off:_
- Timing: aim to go live with Admin theme change in mid-September, ahead of November 2023 date for Drupal 10 upgrade
- Paragraphs module has to be updated prior to Claro implenetation
- Admin theme must be implemented prior to Drupal 10 implementation
- Admin theme must be implemented/reviewed in conjunction with CK Editor
- Need to incorporate feedback from Anna and other stakeholders prior to selecting an Admin theme

**Comment by navsunka** [comment]
Claro on ODE -- https://ncigovcdode595.prod.acquia-sites.com/

@santwuma @bryanpizzillo @kate-mashkina

**Comment by laurelthrash** [comment]
Initial reactions to Claro Admin theme on ODE ahead of regroup on 7/20 Cc: @lburack 

Pros
- Like that the admin toolbar remains horizontal at the top throughout. Helps keep continuity from item to item. 

Flags (I acknowledge these are likely my personal preference/what my eyes are used to!)
- It is slightly distracting that the fields for content types are not left aligned on the page. Is it possible to be left aligned, such as how media items present themselves?
- Feels like there is more space in between fields compared to the existing Admin UI which is slightly distracting. Flagging in case others feel the same and it can be revisited.

**Comment by lburack** [comment]
Here are my notes ahead of our regroup this afternoon:

- Like @laurelthrash, I wish the Content items had their fields left aligned, which would make them wider (like they are on Media items)
- List Description field allows for resizing (to make taller or shorter), but this doesn't appear possible on other content fields. Our current version of Drupal has this resizer on all fields in the Drupal content form. 
- Overall, the modals to select content don't allow you to see as much as we can view now. In the Claro theme, the text is much larger with more (line) spacing. The two screenshots of the site section selector show the differences between what we have currently versus what's in Claro
- Do we have any control on styling of the button to add paragraphs, like Related Resources, Citations, Body sections, Cards on landing pages, etc.? The buttons are gray/styled in a way that makes them seem disabled or unable to be selected.
- On Images, the crops as links are a little odd. Functionally they work, but it's visually not great. 
![Current CMS Site Section Browser Modal](https://github.com/NCIOCPL/cgov-digital-platform/assets/29731392/7f694e19-c209-4f9f-910e-33ee913d7da6)
![Claro Select Site Section Browser Modal](https://github.com/NCIOCPL/cgov-digital-platform/assets/29731392/19e73740-746d-47cc-9591-fee76117ba77)

**Comment by santwuma** [comment]
Home and Landing page paragraph cutting off
![Screenshot (3)](https://github.com/NCIOCPL/cgov-digital-platform/assets/80473282/7a99b544-0430-4b3b-93ef-c616a20c30b7)

**Comment by santwuma** [comment]
**8/9 Meeting Notes:**
Home and Landing page - good to go
Dev to look into yellow warning signs
Article configs good to go
Same article configs apply to other Content types
No paragraph config changes for CTHP content types - leave as-is
