### ISSUE TITLE
Update YAML with new app module configs

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3862]
The YAML content for the app modules needs to be updated with the new configs so that they match production.

### Sub-Tasks
- [ ] Update SWS configs
  - Cgov
  - Cgov Spanish
  - NCI-CONNECT
  - NCI-CONNECT Spanish
  - DCEG
- [ ] Update Glossary configs
  - Cancer Terms
  - Genetics
- [ ] Update Drug Dictionary configs
- [ ] Listing Pages
  - Dynamic
  - Manual
- [ ] Update CTS config

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction
