### ISSUE TITLE
Technical Item: Enable Better Development Settings

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#393]
## Description 

Do the thing.

## Tasks:
- [ ] Get twig changes to update without a `drush cr`
- [x] Install kint for local development environments
- [x] Increate PHP memory limit to 256mb
- [x] Enable and document XDebug (#14)

**Comment by bryanpizzillo** [comment]
The twig cache disabling is actually in our development environments. What needed to be set to get more responsive changes on updates is to update the untracked local.settings.php. There is a caveat though, a number of places, including the settings file and Drupal.org notes that you should NOT keep these settings one. They recommend that you develop and test with them on.

Uncomment the following settings in docroot/sites/default/settings/local.settings.php :
`$settings['cache']['bins']['render'] = 'cache.backend.null';`
`$settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';`

This will disable render caching and changes to templates should appear quickly.
