### ISSUE TITLE
META: Fix PHPStan issues

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3964]
Update Drupal Core in PHPStan

### Modules to be updated
- [x] app_module
- [x] json_data_field
- [x] cgov_application_page
- [x] cgov_blog
- [ ] cgov_event
- [ ] cgov_core
- [ ] cgov_home_landing
- [ ] cgov_image
- [ ] cgov_infographic
- [ ] cgov_list
- [ ] cgov_mail
- [ ] cgov_schema_org
- [ ] cgov_site_section
- [x] cgov_vocab_manager
- [x] pdq_cancer_information_summary
- [x] pdq_core
- [x] pdq_drug_information_summary
- [x] pdq_glossifier

**Comment by blairlearn** [comment]
## phpstan errors as of May 28, 2025

```
 ------ ------------------------------------------------------------------------------------------- 
  Line   modules/custom/json_data_field/src/Plugin/Field/FieldFormatter/JsonDataFieldFormatter.php  
 ------ ------------------------------------------------------------------------------------------- 
  53     Access to an undefined property Drupal\Core\Field\FieldItemInterface::$format.             
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property       
 ------ ------------------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.module                  
 ------ ------------------------------------------------------------------------------------------------------------- 
  28     Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_application_module.               
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                         
  30     Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_application_module.               
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                         
  59     Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_application_module.               
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                         
  61     Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_application_module.               
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                         
  107    Access to an undefined property Drupal\Core\Entity\ContentEntityInterface::$field_app_module_page_template.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                         
 ------ ------------------------------------------------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module                                  
 ------ ----------------------------------------------------------------------------------------------------- 
  120    Call to an undefined method Drupal\workflows\WorkflowTypeInterface::appliesToEntityTypeAndBundle().  
  221    Call to an undefined method Drupal\Core\Entity\EntityInterface::set().                               
  223    Access to an undefined property Drupal\Core\Entity\EntityInterface::$preferred_admin_langcode.       
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                 
  227    Call to an undefined method Drupal\Core\Entity\EntityInterface::set().                               
  322    Access to an undefined property Drupal\views\Plugin\views\query\QueryPluginBase::$where.             
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                 
  329    Access to an undefined property Drupal\views\Plugin\views\query\QueryPluginBase::$orderby.           
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                 
  451    Call to an undefined method Drupal\Core\Entity\ContentEntityInterface::isPublished().                
  843    Variable $map might not be defined.                                                                  
 ------ ----------------------------------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovConfigOverrider.php  
 ------ -------------------------------------------------------------------------------- 
  22     \Drupal calls should be avoided in classes, use dependency injection instead    
  31     \Drupal calls should be avoided in classes, use dependency injection instead    
  42     \Drupal calls should be avoided in classes, use dependency injection instead    
  51     \Drupal calls should be avoided in classes, use dependency injection instead    
 ------ -------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php                         
 ------ ------------------------------------------------------------------------------------------------- 
  205    Call to an undefined method Drupal\workflows\WorkflowTypeInterface::addEntityTypeAndBundle().    
  206    Method Drupal\Core\Config\Entity\ConfigEntityBase::save() invoked with 1 parameter, 0 required.  
  217    Call to an undefined method Drupal\workflows\WorkflowTypeInterface::addEntityTypeAndBundle().    
  218    Method Drupal\Core\Config\Entity\ConfigEntityBase::save() invoked with 1 parameter, 0 required.  
  647    Call to an undefined method Drupal\Core\Access\AccessResultInterface::getCacheMaxAge().          
  648    Call to an undefined method Drupal\Core\Access\AccessResultInterface::getCacheTags().            
  649    Call to an undefined method Drupal\Core\Access\AccessResultInterface::getCacheContexts().        
  679    Call to an undefined method Drupal\Core\Form\FormInterface::getEntity().                         
 ------ ------------------------------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_core/src/Controller/CgovMediaController.php                                 
 ------ -------------------------------------------------------------------------------------------------------------------------- 
  28     PHPDoc tag @param for parameter $media with type Drupal\cgov_core\Controller\Drupal\media\Entity\Media is not subtype of  
         native type Drupal\media\Entity\Media.                                                                                    
  28     Parameter $media of method Drupal\cgov_core\Controller\CgovMediaController::longDescription() has invalid type            
         Drupal\cgov_core\Controller\Drupal\media\Entity\Media.                                                                    
 ------ -------------------------------------------------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------------------------------ 
  Line   profiles/custom/cgov_site/modules/custom/cgov_core/src/NavItem.php                                                      
 ------ ------------------------------------------------------------------------------------------------------------------------ 
  153    Access to an undefined property Drupal\cgov_core\NavItem::$isBreadcrumbRoot.                                            
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                    
  163    PHPDoc tag @var has invalid value ([['value' => string], ['value' => string]]): Unexpected token "[", expected type at  
         offset 9                                                                                                                
  222    Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                                  
  334    Method Drupal\cgov_core\NavItem::getChildren() has invalid return type Drupal\cgov_core\NavItemInterface.               
  395    Call to method hasDisplayRule() on an unknown class Drupal\cgov_core\NavItemInterface.                                  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                     
  396    Call to method isNavigable() on an unknown class Drupal\cgov_core\NavItemInterface.                                     
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                     
 ------ ------------------------------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------------------------------------------------ 
  Line   profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/Breadcrumb.php                                      
 ------ ------------------------------------------------------------------------------------------------------------------------ 
  106    Method Drupal\cgov_core\Plugin\Block\Breadcrumb::getBreadcrumbs() should return array but return statement is missing.  
  111    Call to method isCurrentSiteSection() on an unknown class Drupal\cgov_core\NavItemInterface.                            
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                     
  112    Call to method getChildren() on an unknown class Drupal\cgov_core\NavItemInterface.                                     
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                     
  119    Call to method getIsInCurrentPath() on an unknown class Drupal\cgov_core\NavItemInterface.                              
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                     
  131    Call to method isCurrentSiteSectionLandingPage() on an unknown class Drupal\cgov_core\NavItemInterface.                 
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                     
  138    Call to method getHref() on an unknown class Drupal\cgov_core\NavItemInterface.                                         
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                     
  139    Call to method getLabel() on an unknown class Drupal\cgov_core\NavItemInterface.                                        
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                     
 ------ ------------------------------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/DisqusComments.php                                   
 ------ ------------------------------------------------------------------------------------------------------------------------- 
  29     Property Drupal\cgov_core\Plugin\Block\DisqusComments::$cgovCoreTools has unknown class                                  
         Drupal\cgov_core\Plugin\Block\Drupal\cgov_core\CgovCoreTools as its type.                                                
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                      
  70     PHPDoc tag @param for parameter $cgov_core_tools with type Drupal\cgov_core\Plugin\Block\Drupal\cgov_core\CgovCoreTools  
         is not subtype of native type Drupal\cgov_core\CgovCoreTools.                                                            
  77     Parameter $cgov_core_tools of method Drupal\cgov_core\Plugin\Block\DisqusComments::__construct() has invalid type        
         Drupal\cgov_core\Plugin\Block\Drupal\cgov_core\CgovCoreTools.                                                            
  107    Method Drupal\cgov_core\Plugin\Block\DisqusComments::getCurrEntity() has invalid return type                             
         Drupal\cgov_core\Plugin\Block\Drupal\Core\Entity\ContentEntityInterface.                                                 
  124    Method Drupal\cgov_core\Plugin\Block\DisqusComments::getNodeStorage() has invalid return type                            
         Drupal\cgov_core\Plugin\Block\Drupal\Core\Entity\EntityStorageInterface.                                                 
  126    Variable $node_storage on left side of ?? always exists and is not nullable.                                             
  139    Call to method bundle() on an unknown class Drupal\cgov_core\Plugin\Block\Drupal\Core\Entity\ContentEntityInterface.     
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                      
  140    Call to method language() on an unknown class Drupal\cgov_core\Plugin\Block\Drupal\Core\Entity\ContentEntityInterface.   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                      
  151    Call to method get() on an unknown class Drupal\cgov_core\Plugin\Block\Drupal\Core\Entity\ContentEntityInterface.        
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                      
  152    Call to method load() on an unknown class Drupal\cgov_core\Plugin\Block\Drupal\Core\Entity\EntityStorageInterface.       
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                      
  164    Call to method isProd() on an unknown class Drupal\cgov_core\Plugin\Block\Drupal\cgov_core\CgovCoreTools.                
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                      
 ------ ------------------------------------------------------------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/MainNav.php                                  
 ------ ----------------------------------------------------------------------------------------------------------------- 
  119    Method Drupal\cgov_core\Plugin\Block\MainNav::getMainNav() should return array but return statement is missing.  
  138    Call to method hasDisplayRule() on an unknown class Drupal\cgov_core\NavItemInterface.                           
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                              
  149    Call to method getHref() on an unknown class Drupal\cgov_core\NavItemInterface.                                  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                              
  150    Call to method getLabel() on an unknown class Drupal\cgov_core\NavItemInterface.                                 
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                              
  156    Call to method getMegamenuContent() on an unknown class Drupal\cgov_core\NavItemInterface.                       
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                              
  192    Call to method hasDisplayRule() on an unknown class Drupal\cgov_core\NavItemInterface.                           
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                              
  203    Call to method getHref() on an unknown class Drupal\cgov_core\NavItemInterface.                                  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                              
  204    Call to method getLabel() on an unknown class Drupal\cgov_core\NavItemInterface.                                 
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                              
 ------ ----------------------------------------------------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/SectionNav.php                                     
 ------ ----------------------------------------------------------------------------------------------------------------------- 
  85     Method Drupal\cgov_core\Plugin\Block\SectionNav::getSectionNav() should return array but return statement is missing.  
  143    Call to method hasDisplayRule() on an unknown class Drupal\cgov_core\NavItemInterface.                                 
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                    
 ------ ----------------------------------------------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/CgovNavigationManager.php                                
 ------ ------------------------------------------------------------------------------------------------------------------------- 
  285    Method Drupal\cgov_core\Services\CgovNavigationManager::getParentTerm() should return Drupal\taxonomy\TermInterface but  
         return statement is missing.                                                                                             
  388    Method Drupal\cgov_core\Services\CgovNavigationManager::findNavRootTerm() should return                                  
         Drupal\taxonomy\TermInterface|null but return statement is missing.                                                      
  413    Method Drupal\cgov_core\Services\CgovNavigationManager::getNavRoot() should return Drupal\cgov_core\NavItem|null but     
         return statement is missing.                                                                                             
  676    Method Drupal\cgov_core\Services\CgovNavigationManager::newNavItem() has invalid return type                             
         Drupal\cgov_core\NavItemInterface.                                                                                       
  818    Cannot call method getId() on string.                                                                                    
  819    Call to an undefined method Drupal\Core\Entity\EntityInterface::hasTranslation().                                        
  820    Call to an undefined method Drupal\Core\Entity\EntityInterface::getTranslation().                                        
 ------ ------------------------------------------------------------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.module                    
 ------ ----------------------------------------------------------------------------------------- 
  119    Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                   
  168    Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                   
  221    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_media_image.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property     
  306    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_media_image.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property     
 ------ ----------------------------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_infographic/cgov_infographic.module  
 ------ ----------------------------------------------------------------------------------- 
  83     Call to an undefined method Drupal\Core\Entity\EntityInterface::get().             
  87     Call to an undefined method Drupal\Core\Entity\EntityInterface::get().             
 ------ ----------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_list/cgov_list.module                          
 ------ --------------------------------------------------------------------------------------------- 
  107    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_list_item_style.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property         
  128    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_media_link.       
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property         
 ------ --------------------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_mail/src/Controller/MailAPIController.php    
 ------ ------------------------------------------------------------------------------------------- 
  48     Property Drupal\cgov_mail\Controller\MailAPIController::$cgovMailConfig has unknown class  
         Drupal\Core\Config\EditableConfigInterface as its type.                                    
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                        
  62     Property Drupal\cgov_mail\Controller\MailAPIController::$mailPlugin has unknown class      
         Drupal\Core\Config\EditableConfigInterface as its type.                                    
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                        
  135    Call to method get() on an unknown class Drupal\Core\Config\EditableConfigInterface.       
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                        
  196    Call to method get() on an unknown class Drupal\Core\Config\EditableConfigInterface.       
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                        
  202    Variable $recaptchaResponseField might not be defined.                                     
  271    Call to method get() on an unknown class Drupal\Core\Config\EditableConfigInterface.       
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                        
  286    Call to method set() on an unknown class Drupal\Core\Config\EditableConfigInterface.       
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                        
 ------ ------------------------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_schema_org/cgov_schema_org.module                     
 ------ ---------------------------------------------------------------------------------------------------- 
  14     Access to an undefined property Drupal\Core\Entity\ContentEntityInterface::$field_schema_org_data.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                
 ------ ---------------------------------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_schema_org/src/Plugin/Field/FieldType/CgovSchemaOrgFieldItem.php  
 ------ ---------------------------------------------------------------------------------------------------------------- 
  60     Variable $page_itemtype in empty() always exists and is not falsy.                                              
 ------ ---------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_schema_org/src/Plugin/Field/FieldWidget/CgovSchemaOrgWidget.php  
 ------ --------------------------------------------------------------------------------------------------------------- 
  51     Access to an undefined property Drupal\Core\TypedData\TypedDataInterface::$page_itemtype.                      
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                           
 ------ --------------------------------------------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module                     
 ------ -------------------------------------------------------------------------------------------------------- 
  56     Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  56     Call to an undefined method Drupal\Core\Entity\EntityInterface::hasField().                             
  57     Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  61     Call to an undefined method Drupal\Core\Entity\EntityInterface::set().                                  
  68     Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  81     Call to an undefined method Drupal\Core\Entity\EntityInterface::set().                                  
  91     Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  94     Call to an undefined method Drupal\Core\Entity\EntityInterface::set().                                  
  114    Call to an undefined method Drupal\Core\Entity\EntityInterface::hasField().                             
  118    Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  119    Call to an undefined method Drupal\Core\Entity\EntityInterface::getTranslation().                       
  196    Access to an undefined property Drupal\Core\Entity\EntityInterface::$original.                          
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  196    Access to an undefined property Drupal\Core\Entity\EntityInterface::$status.                            
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  197    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_yaml_content.                
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  197    Access to an undefined property Drupal\Core\Entity\EntityInterface::$original.                          
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  226    Access to an undefined property Drupal\Core\Entity\EntityInterface::$langcode.                          
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  226    Access to an undefined property Drupal\Core\Entity\EntityInterface::$parent.                            
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  252    Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  274    Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  280    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_ncids_mega_menu_contents.    
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  280    Access to an undefined property Drupal\Core\Entity\EntityInterface::$original.                          
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  318    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_section_nav_root.            
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  350    Access to an undefined property Drupal\Core\Entity\EntityInterface::$original.                          
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  356    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_main_nav_root.               
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  357    Access to an undefined property Drupal\Core\Entity\EntityInterface::$original.                          
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  480    Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  480    Call to an undefined method Drupal\Core\Entity\EntityInterface::hasField().                             
  495    Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  498    Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  524    Access to an undefined property Drupal\Core\Entity\EntityInterface::$original.                          
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  524    Call to an undefined method Drupal\Core\Entity\EntityInterface::getWeight().                            
  531    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_section_nav_root.            
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  537    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_navigation_display_options.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  543    Access to an undefined property Drupal\Core\Entity\EntityInterface::$original.                          
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  596    Access to an undefined property Drupal\Core\Entity\EntityInterface::$original.                          
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  596    Call to an undefined method Drupal\Core\Entity\EntityInterface::getWeight().                            
  603    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_main_nav_root.               
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  609    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_navigation_display_options.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  615    Access to an undefined property Drupal\Core\Entity\EntityInterface::$original.                          
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  637    Variable $values might not be defined.                                                                  
  658    Access to an undefined property Drupal\Core\Entity\EntityInterface::$original.                          
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  660    Access to an undefined property Drupal\Core\Entity\EntityInterface::$status.                            
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  663    Access to an undefined property Drupal\Core\Entity\EntityInterface::$original.                          
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  663    Access to an undefined property Drupal\Core\Entity\EntityInterface::$status.                            
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  670    Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  673    Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  678    Call to an undefined method Drupal\Core\Entity\EntityInterface::get().                                  
  716    Access to an undefined property Drupal\Core\Entity\EntityInterface::$field_landing_page.                
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  1048   Call to an undefined method Drupal\Core\Entity\EntityInterface::validate().                             
 ------ -------------------------------------------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.tokens.inc  
 ------ ----------------------------------------------------------------------------------------- 
  79     Variable $tid might not be defined.                                                      
  169    Variable $alias in isset() always exists and is not nullable.                            
 ------ ----------------------------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Controller/CgovNavTreeController.php  
 ------ ----------------------------------------------------------------------------------------------------- 
  478    Method Drupal\cgov_site_section\Controller\CgovNavTreeController::getParentTerm() should return      
         Drupal\taxonomy\TermInterface but return statement is missing.                                       
 ------ ----------------------------------------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/src/Form/CgovVocabManagerForm.php  
 ------ ----------------------------------------------------------------------------------------------- 
  226    Variable $complete_tree in isset() is never defined.                                           
  294    Cannot access property $depth on int|object.                                                   
  314    Cannot access property $tid on int|object.                                                     
 ------ ----------------------------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/src/Manager/CgovVocabManager.php  
 ------ ---------------------------------------------------------------------------------------------- 
  26     Variable $parent_tid in isset() always exists and is not nullable.                            
 ------ ---------------------------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/src/OrphanCleanup.php       
 ------ ---------------------------------------------------------------------------------------------------- 
  126    Variable $paragraph_id might not be defined.                                                        
  127    Call to deprecated method deleteRevision() of interface Drupal\Core\Entity\EntityStorageInterface:  
         in drupal:10.1.0 and is removed from drupal:11.0.0. Use                                             
         \Drupal\Core\Entity\RevisionableStorageInterface::deleteRevision instead.                           
 ------ ---------------------------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------------------------ 
  Line   profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/src/Plugin/rest/resource/PDQResource.php  
 ------ ------------------------------------------------------------------------------------------------------------------ 
  248    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::hasTranslation().                           
  249    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::getTranslation().                           
  252    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::addTranslation().                           
 ------ ------------------------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------ 
  Line   profiles/custom/cgov_site/modules/custom/pdq_core/src/PDQConfigOverrider.php  
 ------ ------------------------------------------------------------------------------ 
  21     \Drupal calls should be avoided in classes, use dependency injection instead  
  29     \Drupal calls should be avoided in classes, use dependency injection instead  
 ------ ------------------------------------------------------------------------------ 

 ------ ----------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/pdq_core/src/RevisionPruner.php                 
 ------ ----------------------------------------------------------------------------------------- 
  67     Call to an undefined method Drupal\Core\Entity\RevisionableInterface::hasTranslation().  
  68     Call to an undefined method Drupal\Core\Entity\RevisionableInterface::getTranslation().  
 ------ ----------------------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/src/Plugin/rest/resource/PDQResource.php  
 ------ ---------------------------------------------------------------------------------------------------------------- 
  197    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::setTitle().                               
  198    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::setOwnerId().                             
  199    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::set().                                    
  200    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::set().                                    
  201    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::set().                                    
  202    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::set().                                    
  203    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::set().                                    
  204    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::set().                                    
  205    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::set().                                    
  206    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::set().                                    
  207    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::set().                                    
  208    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::set().                                    
  218    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::setRevisionCreationTime().                
  219    Call to an undefined method Drupal\Core\Entity\RevisionableInterface::setRevisionUserId().                      
  220    Access to an undefined property Drupal\Core\Entity\RevisionableInterface::$moderation_state.                    
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                            
 ------ ---------------------------------------------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------------------------- 
  Line   profiles/custom/cgov_site/modules/custom/pdq_glossifier/src/Plugin/rest/resource/PDQResource.php  
 ------ -------------------------------------------------------------------------------------------------- 
  129    \Drupal calls should be avoided in classes, use dependency injection instead                      
 ------ -------------------------------------------------------------------------------------------------- 

                                                                                                                        
 [ERROR] Found 168 errors                                                                                               
                                                                                                                        
```

**Comment by blairlearn** [comment]
# Groups

## Group 1 - App Module / App module page / Blog

- docroot/modules/custom/app_module/src/AppPathManager.php
- docroot/modules/custom/json_data_field/src/Plugin/Field/FieldFormatter/JsonDataFieldFormatter.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogArchive.php

## Group 2 - Cgov Core -- General Utility

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovConfigOverrider.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php

## Group 3 - Cgov Core -- Navigation

- docroot/
- docroot/
- docroot/

**Comment by blairlearn** [comment]
Overtaken by events, #5381
