### ISSUE TITLE
Create NCIDS Dynamic List

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#4070]
## As a user on the News & Events landing page, I want to see a list of news releases, so that I can be updated on the latest cancer research news.

### Requirements
- Create a new NCIDS Dynamic List to display press releases on the News & Events page
- Use the usa-collections with the patch created in the NCIDS
- Below the press releases, there will be a View More link
- This component will match the Content Model

### Drupal DoR

- [ ] Content Model:
  - [x] Drafted
  - [x] Reviewed
  - [ ] Approved
- [ ] Acceptance Criteria:
  - [ ] Drafted
  - [ ] Reviewed
  - [ ] Approved
- [ ] YAML Created (make YAML for [News & Events Landing Page](https://www.figma.com/file/XH87Z6GvJ0MWoX16l0FzKo/News-%26-Events-Landing-Page?type=design&node-id=0-1&mode=design&t=asi2XMCLfH1MPRqE-0))

### Drupal DoD

- [ ] Drupal Governance Drafted
- [ ] Internal Testing
- [ ] Client Review

### Acceptance Criteria

```gherkin
Scenario: A content editor adds an NCIDS Dynamic List on a Home and Landing page
  Given a content editor is logged into the CMS
    And the user creates a new Home and Landing page content item
  When the user adds an NCIDS 2 Column Container paragraph to the Contents field
      And the user adds an NCIDS Dynamic List to the Main Contents field
  Then the paragraph fields will exactly match the content model

```

```gherkin
Scenario: User can add an NCIDS Dynamic List to a Home and Landing Page
  Given user is logged into the CMS
  When user creates a new "Home and Landing" content item
  Then the editing page for a "Home and Landing" content item displays
    And user fills out the following fields
      | fieldLabel                  | value                                                   | field_name                     |
      | Home and Landing Page Style | NCIDS without Title                                     | field_page_style               |
      | Pretty URL                  | ncids-dynamic-list-page                                 | field_pretty_url               |
      | Page Title                  | Automated Test NCIDS Dynamic List                       | title                          |
      | Browser Title               | Automated Test NCIDS 2 Dynamic List - Browser Title     | field_browser_title            |
      | Card Title                  | Automated Test NCIDS 2 Dynamic List - Card Title        | field_card_title               |
      | Meta Description            | Automated Test NCIDS 2 Dynamic ListMeta Description     | field_page_description         |
      | Feature Card Description    | Automated Test NCIDS 2 Dynamic List - Feature Card Desc | field_feature_card_description |
  When user selects "Add NCIDS 2 Column Container" from "Contents" dropdown
  Then "NCIDS 2 Column Container" section appears
  When user selects "Add NCIDS Dynamic List" from "Main Contents" dropdown
  Then "NCIDS Dynamic List" section appears
    And user fills out the following fields
      | fieldLabel         | value                      | field_name        |
      | List Title         | NCIDS Dynamic List Heading | field_list_title  |
      | Source View        | Press Releases             | ???               |
      | Display            | Home List Block            | ???               |
      | Include View Title | unchecked                  | ???               |
      | Items per page     |                            | ???               |
      | Pagination         | Default settings           | ???               |
      | Arguments          |                            | ???               |
  When user selects "Add Raw HTML Content" from "Secondary Contents" dropdown
  Then "NCIDS Raw HTML Content" section appears
    And user fills out the following fields
      | fieldLabel       | value                                                                                                                                                                                                    | field_name           |
      | Raw HTML Content | <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Curabitur gravida arcu ac tortor dignissim convallis aenean et.</p> | field_card_raw_html  |
    When user saves the content page
    Then user can see NCIDS 2 Column Container on the page
      And the Main Contents heading displays "NCIDS Dynamic List Heading"
      And the Main Contents dynamic list shows 5 items
      And the Secondary Contents displays "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Curabitur gravida arcu ac tortor dignissim convallis aenean et."
```

``` gherkin
Scenario: Analytics event for clicks on collections component
Given a user is on any page of cancer.gov with a collections component
When the user clicks on a link within the collections component
Then there should be an NCIDataLayer Other event 
  And the event has the name “LP:Collection:LinkClick”
  And the event has the the linkname “LP:Collection:LinkClick”
  And this event should have the following data:
    | key              | value                                                                                                                                                                                                                                                                                                                                                                                             |
    | location         | Body                                                                                                                                                                                                                                                                                                                                                                                              |
    | pageRows         | This should return the number of rows on the page overall                                                                                                                                                                                                                                                                                                                                                           |
    | pageRowIndex     | This should return the index of the row number on the page that was clicked |
    | rowItems         | This should return the total number of components in the row that is clicked|
    | rowItemIndex     | This should return the index of the component in the rows that was clicked |
    | componentType    | Collection |
    | componentTheme   | This should be “Light” or “Dark”. In cases where a theme option is not yet available, this match whatever the available theme color is.|
    | componentVariant | This value represents the component design options available for a component type. For Collections, this value should be set to “Standard”. |
    | title            | This value should represent the collection component overall. If there is a title field or some other value that can help make this more specific, that would be great. If not, we can pass “Collection” for this value. (Ideally, something like the heading above it would be great, but know that is a different component and not connected to this.)|
    | linkType         | This value can be set to “internal”, “external”, or “media” based on the destination/type of links clicked.|
    | linkText         | This should capture the title of the collection item clicked. In the case that a user clicks the button at the bottom of the component, this value should pass the text used on the button. This value should be truncated after 50 characters. |
    | linkArea         | This value represents the link or area that was clicked. For Collections, this value will be “Collection Item” and if the button at the end of collection is clicked pass “View All Button”. (If text and image on the collection item are individual clickable elements, this should be updated so that clicks on the title pass “Collection Item Title” and for the image “Collection Item Image”|
    | totalLinks       | This should pass the total number of collection items shown in the collections component. (Ex: if the component shows 4 items in the list, then pass this value as 4.) |
    | linkPosition     | This should pass the index of the link clicked in the component evaluated by counting the items top to bottom. (Ex: If the third item in the list is clicked, pass 3.)|
```

### Resources:
* [Mockups](https://www.figma.com/file/XH87Z6GvJ0MWoX16l0FzKo/News-%26-Events-Landing-Page?type=design&mode=design&t=nL9qJIUa7smfJMSF-0)
* [DS Collections component](https://github.com/NCIOCPL/ncids/issues/1149)
* [DS Headings component](https://github.com/NCIOCPL/ncids/issues/1150)


### Notes

### Prerequisites
- [ ] [NCIDS Headings](https://github.com/NCIOCPL/ncids/issues/1150)
- [ ] [NCIDS Collections](https://github.com/NCIOCPL/ncids/issues/1149)


### Tasks
- [ ] Create NCIDS Home List Block view (maybe? if so, let's rename this)


### Technical Notes
* [Content Model](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Type-NCIDS-Dynamic-List)

**Comment by welshja** [comment]
Per discussion with @arcepaul, @dev-rana-publicis, and @nicolecrom, rowItems and rowItemIndex should consider all items within a 2 column layout as 1 "row". Though multiple components could be stacked within that column, we want to use these values to count the rows at the higher level. Other values will help us determine layout/position within the columns.

So, for the dynamic list on the News and Events landing page, the rowItems should be 2 and the rowItemIndex should be 1 based on the above.
