### ISSUE TITLE
Create Institution Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#417]
This story is to create the content type for Institution with all the fields and permissions.

**User Story:**
- As a content author I would like to create a [Institution ](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution) on cancer.gov. 

**Acceptance Criteria:**

- I am required to enter the following Common Fields:
    * [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
    * [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
    * [Posted Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Updated Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Reviewed Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

- I have the option to enter the following Common Fields:
    * [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
    * [Browser Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Browser-Title)
    * [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
    * [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
    * [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
    * [Date Display Mode](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Body](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body)
    * [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Lead-Image)
    * [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)
    * [Related Resources](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Related-Resources)
    * [Citations](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Citations)

- I am required to enter the following Local Fields:
   * [Institution Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#institution-name)

- I have the option to enter the following Local Fields:
  * [Parent University/Institution Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#parent-universityinstitution-name)
  * [Organization Head 1 Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#organization-head-1-name)
  * [Organization Head 1 Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#organization-head-1-title)
  * [Organization Head 2 Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#organization-head-2-name)
  * [Organization Head 2 Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#organization-head-2-title)
  * [Address Line 1](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#address-line-1)
  * [Address Line 2](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#address-line-2)
  * [City](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#city)
  * [State](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#state-dropdown)
  * [Zip code](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#zip-code)
  * [Phone Label 1](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#phone-1-label)
  * [Phone Number 1](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#phone-1-number)
  * [Phone Label 2](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#phone-2-label)
  * [Phone Number 2](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#phone-2-number)
  * [Website Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#website-title)
  * [Website URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#website-url)
  * [Institution Type](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#institution-type)

- [Things Still to Discuss](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution#things-to-discuss)

[Example of Institution Page](https://www.cancer.gov/research/nci-role/cancer-centers/find/dfharvard)

**Tasks/Subtasks:**
- [ ] Add workflow transitions for institution content type 
- [ ] Add content author and content reviewer permissions for institution content type  
- [ ] Create Local fields
- [ ] Attach all fields

**Comment by nicolecrom** [comment]
Duplicate of #156
