### ISSUE TITLE
Create Biography Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#418]
This story is to create the content type for Biography with all the fields and permissions.

**User Story:**
- As a content author I would like to create a [Biography](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography) on cancer.gov. 

**Acceptance Criteria:**

- I am required to enter the following Common Fields:
    * [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
    * [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
    * [Posted Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Updated Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Reviewed Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

- I have the option to enter the following Common Fields:
    * [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
    * [Browser Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Browser-Title)
    * [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
    * [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
    * [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
    * [Date Display Mode](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Body](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body)
    * [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Lead-Image)
    * [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)
    * [Related Resources](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Related-Resources)

- I am required to enter the following Local Fields:
   * [System Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#system-title)
   * [First Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#first-name)
   * [Last Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#last-name)

- I have the option to enter the following Local Fields:
  * [Middle Name/Middle Initial](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#middle-namemiddle-initial)
  * [Prefix](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#prefix)
  * [Suffix](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#suffix)
  * [Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#title)
  * [Organization 1 Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#organization-1-name)
  * [Organization 1 URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#organization-1-url)
  * [Organization 2 Name](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#organization-2-name)
  * [Organization 2 URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#organization-2-url)
  * [Campus](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#campus)
  * [Building/Room Number](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#buildingroom-number)
  * [Phone Number](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#phone-number)
  * [Email Address](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#email-address)
  * [LinkedIn Profile handle](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#linkedin-profile-handle)
  * [Twitter Profile handle](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#twitter-profile-handle)
  * [Scientific Publications](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#scientific-publications)

- [Things Still to Discuss](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#system-title)

**Tasks/Subtasks:**
- [ ] Add workflow transitions for biography content type 
- [ ] Add content author and content reviewer permissions for biography content type  
- [ ] Create Local fields
- [ ] Attach all fields

**Comment by nicolecrom** [comment]
Duplicate of #157
