### ISSUE TITLE
Task: Create Initial Cancer Type Landing Page YAML

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#4223]
### Tasks

- [ ] Create that JS/CSS entry point in the front-end code
- [ ] Add the Drupal library
- [ ] Make the YAML content that references that Drupal library
  - Home and Landing Page Style: NCIDS with Title
  - Site Section: Make this the new Cancer Types. Make current Cancer Types into Cancer Types /cgdpl
  - Page Title: Cancer Types
  - Browser Title: A to Z List of Cancer Types
  - Card Types: Cancer Types
  - Meta Description: A to Z list of cancer types, with links to disease-specific and general information about treatment, supportive care, screening, prevention, clinical trials, and other topics.
  - Contents: One Column Container
    - Main Contents: Raw HTML Content (add basic structure if able. Otherwise, leave for the future tickets that will build out the rest of the work in R2.4.
  - Enable using CSS/JS on the right column once added per #4236 
  - For all other fields, if not indicated, leave blank.
