### ISSUE TITLE
Update to next NCIDS

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#4355]
### Issue description
> **ESTIMATE** TBD

This will most likely be NCIDS 3.0 when we launch, but there are breaking changes in develop right now.

### Technical Requirements
**These are also noted on the PR**
- [Wide Guide Card](https://www-dev-ac.cancer.gov/test/ncids-mini-landing-template):
  - If there is a title and a description, then there will be 1 rem of space (16px) between the title and the description and the title will have 24px between the top of the box that contains the text and the top of the title.
  - If there is no title, then the top of the description will be 24px of space between the top of the box containing the text and the top of the description text ([see comp](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=8172-18131&node-type=frame&m=dev))
  - If there is a title and no description, then there will be 16px of space between the title and the top of the first button
- [Content Block](https://www-dev-ac.cancer.gov/test/ncids-mini-landing-template):
  - The first item in the block will be set to be at the top of the content block (including both a heading or a paragraph)
  - The spacing between a title and a paragraph or between two paragraphs will be 1em
- [Summary Box](https://www-dev-ac.cancer.gov/test/ncids-mini-landing-template):
  - The first item in the Summary box will be set 24px below the top of the summary box container
- The Content Block and Summary Box need the first paragraph (if it is the first item in the component) to not have top padding
- The Content Block and Summary Box need the last paragraph in the component (including if it is the only item in the component) to not have bottom padding
- The Raw HTML needs a way to make the first paragraph (if it is the first item in the Raw HTML) to not have top padding
- The Raw HTML needs a way to make the last paragraph in the Raw HTML (including if it is the only item in the Raw HTML) to not have bottom padding

## Tasks

- [x] **Workaround Changes**
  - [x] Summary Box Heading (#4379 and [1815 on the DS](https://github.com/NCIOCPL/ncids/issues/1815)) this will need to be changed with this update. The size of the heading was reduced for MLPs compared to its original.
  - [x] List heading and size of the link titles were both reduced a token size down on #4360
  - [x] Feature Card card title and description were changed to token size md and xs (20px and 16px) respectively #4434 
- [x] **Update `Updating NCIDS Packages` in the front-end `README.md`.**
   We no longer need to read from a tarball for NCIDS.  We can now use the normal `npm install` process.

- [ ] **"Non-breaking changes": NCIDS 2.8.0**
   - [ ] **Footer back to top analytics:**
   The back to top DOM element is not created until on scroll, meaning we need to wait until it is available before we can attach event listener analytics. The following mutation observer may work:
      ```ts
      const bttObserver = new MutationObserver(() => {
        const selector = '.usa-footer__nci-return-to-top a';
        if (document.querySelector(selector)) {
          bttObserver.disconnect();
          const backToTopLink = footerElement.querySelector(selector) as HTMLAnchorElement;
          backToTopLink.addEventListener('click', backToTopAnalyticsHandler());
        }
      });
      ```
   - [x] **Footer back to top SPANISH:**
      Legacy back top top Spanish is no longer supported, this is a bug as this ticket was meant to be backwards compatible. Fix this for now with:
      ```ts
      NCIBigFooter.create(footerElement, {
        subscribeInvalidEmailAlert: 'Ingrese su dirección de correo electrónico',
        backToTopText: 'Volver Arriba',
      });
      ```
      
   - [x] **Site alert:** 
      Analytics are breaking for expected received values - possibly due to changes to the cookie or that the default version of the site alert is now collapsed to prevent CLS. However, the functionality has been tested and is working as expected.
   
- [x] **Breaking changes: NCIDS 3.0.0**      
   - [x] **All module imports paths should be updated to point directly to the component and not the ncids module.** 
      Use `import { NCIBigFooter } from '@nciocpl/ncids-js/usa-footer'` instead of 
          `import { NCIBigFooter } from 
 '@nciocpl/ncids-js'`
   - [x] **Removed modules**
      - [x] `NCISubscribe`
      - [x] `NCISubscribeOptions`
   - [x] **Banner**
      - [x] `.usa-banner .usa-button` has been replaced by `.usa-banner__language-toggle`
   - [x] **Header mega menu**
      - [x] `AutocompleteAdaptor` module has been replaced by `AutocompleteAdapter`
      - [x] `MegaMenuAdaptor` module has been replaced by `MegaMenuAdapter`
      - [x] `useUrlForNaviationId` has been removed
      - [x] `data-megamnu-disabled` has been removed. Add `data-menu-id` attribute to a primary navigation item if it truly has a mega menu.
      - [x] `.nci-header--extended` has been replaced by `.nci-header--megamenu`
   - [x] **Site Alert**
      - [x] `NCISiteAlert` module has been replaced by `USASiteAlert`
      - [x] `NCISiteAlertOptions` has been replaced by `USASiteAlertOptions`
      - [x] `.usa-site-alert--nci-standard` has been replaced by `.usa-site-alert` (Default variant)
      - [x] `.usa-site-alert--nci-slim` has been replaced by `.usa-site-alert--slim`
      - [x] `.usa-site-alert--nci-info` has been replaced by `.usa-site-alert--info`
      - [x] `.usa-site-alert--nci-emergency` has been replaced by `.usa-site-alert--emergency`
      - [x] `.usa-site-alert .usa-alert__nci-list` has been replaced by `.usa-list.usa-list--two-column`
   - [x] Removed unused theme variables `$theme-section-padding-height-first` and `$theme-section-padding-height-first-mobile`
   - [x] usa-prose removed margin-y 0 and user-agent style sheet adding 1em 
   - [x] breadcrumb list item update to allow wrapping of long text https://github.com/uswds/uswds/issues/5257

**Comment by karlikpj** [comment]
Note: Footer Back To Top uses Opacity to hide / show the link, and it's there on initial load from JS / so analytics change not needed.
