### ISSUE TITLE
Fix Header Skips for Article things

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#4409]
### Issue description
> **ESTIMATE** TBD

This ticket is to fix header skipping on the main issues on articles and other inner content pages that reuse the components. 

A couple of notes:
1. Do not touch any styles in `themes/custom/cgov` - they are legacy and will cause issues on another site. Any styles should go into `docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/legacy`, but let's connect on where. (This is a mirror of `themes/custom/cgov` where we had to diverge. So if we are adding classes we have a lot more wiggle room than if we have to modify some classes.)
2. All URLs below are available on your local.
3. Always `drush cr` after rebuilding the front-end code. It tells Drupal to clear its caches.

### Tasks
* Citations - These all should be the same visual styling, but check the URLs first to make sure.
  - [x] Change Citations (Selected References) on Articles and Blogs to be visually styled the same as they are today, but be an `<h2>` element.
    * Article:
      * https://www-dev-ac.cancer.gov/about-cancer/treatment/side-effects
      * https://www-dev-ac.cancer.gov/espanol/cancer/tratamiento/efectos-secundarios
    * Blog:
      * https://www-dev-ac.cancer.gov/news-events/cancer-currents-blog/2019/transition-lowy-nci-acting-director
    * ***Template:*** `docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/field/citation/field--field-citation.html.twig`
    * ***Current Code*** 
      ```
      <h6>
        {% if items|length == 1 %}
          {% trans %}
            Selected Reference
          {% endtrans %}
        {% else %}
          {% trans %}
            Selected References
          {% endtrans %}
        {% endif %}
      </h6>
      ```    
  - [x] Change Citations on Press Releases to be visually styled the same as they are today, but be an `<h2>` element.
      * URLS:
        * Press Release:
          * https://www-dev-ac.cancer.gov/news-events/press-releases/2018/leukemia-cll-ibrutinib-trial
          * https://www-dev-ac.cancer.gov/espanol/noticias/comunicados-de-prensa/2018/leucemia-llc-ibrutinib-estudio
      * ***Template:*** `docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/press_release/field--node--field-citation--cgov-press-release.html.twig`
      * ***Current Code*** 
        ```
        <h6>
              {% if items|length == 1 %}
              {% trans with {'context': 'CGov Press Release' } %}
                 Reference
              {% endtrans %}
              {% else %}
              {% trans with {'context': 'CGov Press Release' } %}
                 References
              {% endtrans %}
              {% endif %}
        </h6>
        ```
- Related Resources
  - [x] Change Related Resources on all content that has related resources (Article, Blogs, Press Releases, etc)
    * URLS
      * Article:
        * https://www-dev-ac.cancer.gov/about-cancer/treatment/side-effects
        * https://www-dev-ac.cancer.gov/espanol/cancer/tratamiento/efectos-secundarios
      * Blog:
        * https://www-dev-ac.cancer.gov/news-events/cancer-currents-blog/2019/transition-lowy-nci-acting-director
      * Press Release:
        * https://www-dev-ac.cancer.gov/news-events/press-releases/2018/leukemia-cll-ibrutinib-trial
        * https://www-dev-ac.cancer.gov/espanol/noticias/comunicados-de-prensa/2018/leucemia-llc-ibrutinib-estudio
    * ***Template:*** `docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/field/related_resources/field--field-related-resources.html.twig`
    * ***Current Code***
      ```
      <h6>{% trans %}Related Resources{% endtrans %}</h6>
      ```
- [x] Change On the Page on Articles to a span, but keep the visual appearance.
  * URLS
    * Article:
      * https://www-dev-ac.cancer.gov/about-cancer/treatment/side-effects
      * https://www-dev-ac.cancer.gov/espanol/cancer/tratamiento/efectos-secundarios
      * https://www-dev-ac.cancer.gov/about-cancer/coping/feelings
      * https://www-dev-ac.cancer.gov/espanol/cancer/sobrellevar/sentimientos
    * PDQ CIS
       * https://www-dev-ac.cancer.gov/types/breast/patient/breast-treatment-pdq
       * https://www-dev-ac.cancer.gov/espanol/tipos/seno/paciente/tratamiento-seno-pdq
  * ***Template:*** `docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/article/field--field-article-body.html.twig`
  * ***Current Code***
    ```
    <h6>{% trans %}On This Page{% endtrans %}</h6>
    ```
