### ISSUE TITLE
Remove pdq_importer user from pdq_core install

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/cgov-digital-platform#4521]
The `pdq_core` module creates the `pdq_importer` user upon install of the module.

https://github.com/NCIOCPL/cgov-digital-platform/blob/aa9bd958c58b1740eb3afcd5988c98ea4a966500/docroot/profiles/custom/cgov_site/modules/custom/pdq_core/pdq_core.install#L24-L32

This user is now [created/updated via the user `.yml` files on each environment](https://github.com/NCIOCPL/cgov-digital-platform/blob/aa9bd958c58b1740eb3afcd5988c98ea4a966500/blt/src/Blt/Plugin/Commands/CgovAcsfCommands.php#L27). It does not need to be created by the module anymore. And the module depends on a `PDQ_IMPORTER_PASS` environment variable, which we'd rather not do.

## Tasks

- [ ] Remove the lines of code referenced above
- [ ] Add the `pdq_importer` user to our [local development users](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/cgov-drupal-users.yml) so it's created locally
- [ ] Remove the `PDQ_IMPORTER_PASS` environment variable from each environment as we test/deploy

## Testing

NOTE: To test this, you must use an environment where the `cgov-drupal-users.yml` file does not have the PDQ user present. Otherwise the other user processes will create the user and you can't test its non-creation.

- Standard regressions
- Verify that the PDQ importer user can log in
