### ISSUE TITLE
Create Mini Landing Page Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#461]
This story is to create the content type for Mini Landing Page with all the fields and permissions.

**User Story:**
- As a content author I would like to create a [Mini Landing Page ](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Mini-Landing-Page) on cancer.gov. 

**Acceptance Criteria:**
- I am required to enter the following Common Fields:
    * [Page Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#title-fields)
    * [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
    * [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
    * [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

- I have the option to enter the following Common Fields:
    * [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
    * [Browser Title](#Browser-Title)
    * [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
    * [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
    * [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
    * [Body](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body)
    * [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Lead-Image)
    * [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)
   * [Related Resources](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Related-Resources)

- I have the option to enter the following Local Fields:
  * [Primary Feature Cards](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Mini-Landing-Page#primary-feature-cards)
  * [Thumbnail Cards](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Mini-Landing-Page#thumbnail-cards)
  * [Banner Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Mini-Landing-Page#banner-image-aka-body-header-slot)

- [Things still to discuss](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Mini-Landing-Page#things-to-discuss)

**Tasks/Subtasks:**
- [x] Add workflow transitions for Mini Landing Page content type 
- [x] Add content author and content reviewer permissions for Mini Landing Page content type  
- [x] Create Local fields
- [x] Attach all fields 

![mini-landing-list-templates](https://user-images.githubusercontent.com/29731392/52825452-cc235b00-308a-11e9-9597-15a2f50dec69.png)

**Comment by lburack** [comment]
@bryanpizzillo  - created #699 for additional display option for thumbnail card block (without image)
