### ISSUE TITLE
Press Release Epic

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#582]
Includes the functionality to create and manage press releases and press release archive listing pages as well as the press release styling for these pages.

- [x] Create Press Release Content Type #155
- [x] Attach Article/Promo Image fields to Press Release content type #389
- [x] Attach Public Use Text Field to Press Release #391
- [x] Make Press Release Type Field Text Field #440
- [x] Press Release Field - Subtitle #441
- [x] Remove Press Release Field - Sort Date #442
- [ ] Create Press Release Listing Page #297
- [ ] Create Press Release RSS Feed #298
- [ ] Create Press Release Listing Block for Landing Pages #299
- [ ] Create Press Release Contact Us Block #300
- [ ] Updates to Press Release Content Type #387
- [ ] Attach Pretty URL to Press Release Content Type with Validation #388
- [ ] Attach Citations Fields to Press Release Content Type #390
- [ ] Press Release Date Display Rules #439
- [ ] Attach Related Resources to Press Release #446
- [ ] Attach Recommended Content (clickbait) to Press Release #448
- [ ] Front end look and Feel for Press Release and Archives listing pages #607

**Comment by amydugan** [comment]
Press Releases have been merged to dev.
