### ISSUE TITLE
Home/Landing Page Epic

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#593]
Home/Landing Page Epic Includes:
- [ ] Build out Home/Landing Page using Paragraphs module #486
- [ ] Attach Site Section to Home/Landing Page Type with Validation #183
- [ ] Attach Pretty URL to Home/Landing Page Content Type with Validation #182
- [ ] Landing Page Components: Feature Cards Display #308
- [ ] Landing Page Components: Guide Cards Display #309
- [ ] Landing Page Components: Image Banner #310
- [ ] Create YAML Content for Feature Card Display on home and landing pages #574
- [ ] Create YAML content for guide card display on home and landing pages #575
- [ ] Create YAML content for DOC Carousel #610
- [ ] Implement front end look and feel for display #609 
- [ ] Override Image Field on managed links added to feature card and list item with thumbnail image #783
