### ISSUE TITLE
Cancer Centers Epic

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#596]
Includes the content type creation, templates, and front end styling for Cancer Centers.
Tickets:
- [x] Create Cancer Center Content Type #156
- [ ] Implement Cancer Centers dynamic view (and list page) #590
- [ ] Implement front-end look and feel for Cancer Centers & Cancer Center Dynamic Page #591
