### ISSUE TITLE
Related Resources Epic

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#599]
Includes all of the tickets necessary to implement related resources functionality and attach it to all applicable content types.
- [ ] Create Related Resources Common Field #202
- [ ] Attach Related Resources to Article Page #248
- [ ] Attach Related Resources to Press Release #446

**Comment by BrendanBeltzNIH** [comment]
"The old man was dreaming about the lions."
