### ISSUE TITLE
Mini Landing Page Epic

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#603]
Includes all tickets to support mini landing pages (content type, templates, front end styling, etc.):
- [ ] Create Mini Landing Page Content Type #461 
- [ ] Override Image Field on managed links added to feature card and list item with thumbnail image #783
- [ ] Thumbnail Card Display Options (Image and No Image) #699  
- [ ] Implement Mini-Landing Page look and feel on the front-end #661 

See https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Mini-Landing-Page

**Comment by BrendanBeltzNIH** [comment]
And they lived happily ever after. Said no one ever about Durpal.
