### ISSUE TITLE
PDQ Cancer Information Summaries Epic

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#615]
Implement the import from the CDR, content type, template, and front end styling for PDQ Cancer Information Summaries.
- [x] Define Data Structure of PDQ Summary #164
- [x] Build Data Structure for PDQ Cancer Info Summary #165
- [x] Technical Item: Create PDQ Summary content type #395
- [x] Technical Item: Attach the Page Title field to the PDQ Summary #396
- [x] Technical Item: Attach the Short Title field to PDQ Summary #397
- [x] Technical Item: Define the PDQ Summary Page paragraph type #492
- [x] Technical Item:Attach the Public Use field to PDQ Summary #402
- [x] Technical Item: Set permissions for PDQ Summary type #413
- [x] Technical Item: Create the Audience field for the PDQ Summary type #405
- [x] Technical Item: Create the CDR ID field for PDQ Summary #403
- [x] Technical Item: Connect PDQ Summary to the PDQ workflow #414
- [x] Technical Item: Create the Summary Type field for PDQ Summary #404
- [x] Technical Item: Attach the Posted Date field to PDQ Summary (#165) #400
- [x] Technical Item: Attach the Updated Date field to PDQ Summary #401
- [x] Technical Item: Attach the List Description field to PDQ Summary #398
- [x] Build RESTFUL APIs for PDQ Cancer Information Summaries
- [x] Technical Item: Import PDQ Cancer Information Summaries #568
- [ ] YAML Demo Content for PDQ Cancer Info Summaries #651 
- [ ] Implement PDQ Cancer Information Summary look and feel on the front end #739

**Comment by BrendanBeltzNIH** [comment]
This one was epic. The show's over, make sure you have all your belongings before you exit.
