### ISSUE TITLE
Video Epic

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#657]
Epic includes the content type, workflow, and front end implementation for Video pages.
- [x] Create Video Content Type #220 
- [x] Implement Video look and feel on the front end #658

Also includes the supporting content type, workflow, and front end implementation for Video Carousels
- [x] Create Video Carousel Media Type #221 
- [x] Implement Video Carousel look and feel on the front end #660
