### ISSUE TITLE
Create contextual image content type

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#918]
This is the story to create the [contextual image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#cgov_context_image) content type.

#### I have the option to enter the following common media fields:
Alt Text
Caption
Accessible Text Version

#### I am required to enter the following field on this content type:
The Image (with only the freeform crop available once the image has been uploaded)

#### I have the option to enter the following local Fields on this Content Type
Credit
Original Source
Display Enlarge

Additional Behaviors
If accessible text is provided, the text needs to become a page.
If there's no accessible text provided, display a 404 

**Tasks/Subtasks:**
- [ ] Add workflow transitions for Infographic Multimedia page type. 
- [ ] Add content author and content reviewer permissions for Infographic Multimedia page type. 
- [ ] Create Local fields
- [ ] Attach all fields

**Comment by bryanpizzillo** [comment]
This looks incorrect as it would incongruous with cgov_image. 
>I am required to enter the following common media fields:
>Alt Text

**Comment by VictoriaSunNIH** [comment]
Ah yes - I have removed that requirement.
